Enable subdomain restrictions on app
etalab/data_pass pull request #128
Opened 2024-03-18 16:56 UTC by skelz0r

Cf README.

Principalement pour préparer la migration en N étapes, avec API Entreprise en premier.

2024-03-21 10:43 UTC, skelz0r commented
Sur http://localhost:3000/tableau-de-bord/moi
<img width="1512" alt="Screenshot 2024-03-21 at 10 41 24" src="https://github.com/etalab/data_pass/assets/1279968/6bb4bdca-9983-4334-958e-5a53705f64ea">

Sur http://api-entreprise.localtest.me:3000/tableau-de-bord/moi
<img width="1507" alt="Screenshot 2024-03-21 at 10 35 55" src="https://github.com/etalab/data_pass/assets/1279968/86914787-d423-46db-b49e-7eed1f7fef1c">

2024-03-26 09:24 UTC, Isalafont requested changes

2024-03-26 09:24 UTC, Isalafont commented on config/routes.rb
> +    get 'local-sign-in', to: 'authenticated_user#bypass_login'
Pourra t'on toujours détecter les bugs liés à MCP en local ?

2024-03-26 09:24 UTC, Isalafont commented on app/policies/authorization_request_policy.rb
> +    rescue ActiveRecord::RecordNotFound
Si le sous-domaine n'existe pas, ne serait il pas mieux de rediriger l'url sans sous-domaine ?

2024-03-26 09:24 UTC, Isalafont commented on features/sous-domaine_tableau_de_bord.feature
> +Fonctionnalité: Tableau de bord poyr un sous-domaine spécifique
Typo au mot `pour`

2024-03-26 09:24 UTC, Isalafont commented on app/models/subdomain.rb
>    attr_accessor :id,
Peux tu utiliser un `attr_reader` ? Il me semble qu'à aucun moment nous n'utilisons la fonction `writer`.

2024-03-26 10:49 UTC, skelz0r commented on config/routes.rb
> +    get 'local-sign-in', to: 'authenticated_user#bypass_login'
Oui, c'est juste histoire de pouvoir bypass par exemple `dgfip.localtest.me` sans avoir à aller quémander à MCP d'ajouter milles domaines.

2024-03-26 10:54 UTC, skelz0r commented on app/policies/authorization_request_policy.rb
> +    rescue ActiveRecord::RecordNotFound
Dans ce contexte on veut extraire, en fonction de l'host, les demandes d'autorisations valident. La gestion d'une potentiellement redirection est géré au niveau du controller (en fonction par exemple des autorisations lié à la policy).

2024-03-26 10:56 UTC, skelz0r commented on app/models/subdomain.rb
>    attr_accessor :id,
A la construction si. `ActiveModel::Model#new` se base sur les `attr_accessor` pour affecter les valeurs. C'est le cas d'ailleurs sur l'ensemble des modèles (l'`id` est systématiquement un `attr_accessor` sur `ActiveModel::Model`, au même titre que les autres attributs défini dans le modèle. Pour le cas spécifique d'ActiveRecord, c'est lié aux champs de la db (où `id` est présent)).

2024-03-26 10:57 UTC, Isalafont commented on app/policies/authorization_request_policy.rb
> +    rescue ActiveRecord::RecordNotFound
Mais il ne me semble pas avoir vu de gestion de redirection si le sous domaine n'est pas valide chez nous dans le controller.

2024-03-26 11:03 UTC, skelz0r commented on app/policies/authorization_request_policy.rb
> +    rescue ActiveRecord::RecordNotFound
Tu as tout à fait raison, mais je ne pense pas que ça soit la responsabilité de l'applicatif de déterminer les possibles noms de domaines associé à cette application mais au serveur/host (dans notre cas, nginx). 
De manière général la configuration du nom de domaine n'est jamais embed dans l'application.

Un autre argument: si le serveur nginx ne configure pas le nom de domaine `dgfip.datapass.api.gouv.fr` pour pointer sur cette application, on ne pourra jamais y accéder.

2024-03-26 15:52 UTC, Isalafont commented on app/policies/authorization_request_policy.rb
> +    rescue ActiveRecord::RecordNotFound
Donc nous sommes d'accord, mais nous ne ferons aucun white listing de sous domaine de notre côté ?

2024-03-26 16:03 UTC, skelz0r commented on app/policies/authorization_request_policy.rb
> +    rescue ActiveRecord::RecordNotFound
Faudrait lister dans l'application tous les domaines possibles, donc par exemple staging1.v2.datapass.api.gouv.fr, ou encore staging3.v2.datapass.api.gouv.fr pour les whitelister.

On se retrouverait donc à maintenir 2 listes de domaines: une côté serveur et une côté applicatif. De plus cela implique de donner la connaissance archi à l'applicatif, ce qui n'est pas sa responsabilité.

Et l'argument le plus important pour moi : ça n'apporte rien fonctionnellement. La seule chose que ça va faire c'est rediriger sur le domaine "principal" (qui d'ailleurs devrait aussi être renseignée, mais quelle est le domaine principal ?) sans aucun différence fonctionnelle.

2024-03-26 16:54 UTC, mehdi-farsi commented on app/models/subdomain.rb
>    attr_accessor :id,
On va surement passer ça en ActiveModel::Attributes à l'avenir.

2024-03-26 16:58 UTC, skelz0r commented on app/models/subdomain.rb
>    attr_accessor :id,
Je pensais que c'était inclut avec ActiveModel::Model, interesting. PI Je trimballe ce `StaticApplicationRecord` parce qu'il est pratique pour manipuler de l'ActiveModel et simuler de la db. Si demain on décide de passer n'importe quel descendant de cette classe en db y'a juste la couche modèle à modifier, which is nice.

2024-04-01 14:15 UTC, skelz0r commented
PI j'ai rebase par rapport à la branche de multiple bugfix, je vais déployer celle-ci en staging pour avoir un vrai E2E "final"

2024-04-03 16:01 UTC, merged