API-2116: Système de webhooks
etalab/data_pass pull request #129
Opened 2024-03-19 16:36 UTC by mehdi-farsi

Le but de cette PR est d'avoir un système de webhook ISO avec l'ancien datapass pour API Entreprise.

TODO

- [x] ajout d'un job pour envoyer le webhook
- [x] envoie d'un email en cas de failure successifs du job
- [x] préparation du payload du webhook via un ensemble de serializers
- [x] création d'un interactor qui prépare le payload et enqueue le job d'envoi du webhook
- [ ] appeler cet interactor dans chaque organizer concerné
- [ ] mettre les credentials d'envoie du webhook dans `Rails.application.credentials`
- [ ] test cucumber
- [ ] specs

closes https://linear.app/pole-api/issue/API-2116/systeme-de-webhooks

2024-03-22 12:44 UTC, mehdi-farsi commented
Je n'ai bien sûr pas la `config/production.key` en local. Du coup j'ai pu ajouter que les rails credentials que pour les environnements locaux.

Du coup, il ne faudra pas oublier de les rajouter en prod.

2024-03-22 15:25 UTC, skelz0r requested changes
Je pense que le code n'est pas fonctionnel à 100%: tu as laissé trainer un `comment` qui n'est pas valide, et tous les tests sont verts. 
Je pense qu'il faut soit faire un test E2E un peu plus robuste, par exemple en appelant le job avec une authorization request ayant tous les types d'events.

Ensuite, il manque tous les tests de chaque organizer : il faut vérifier que les webhooks partent bien ici (d'ailleurs je pense que ça t'aurais détecté le souci sur le comment).

Ensuite niveau conception il y a 3 points à tacler à mon sens:

* La configuration sur `webhook?` dans la définition (cf le com associé)
* Le fait d'introduire un organizer qui regroupe les 3 interactors event/notification/webhooks car ils sont indissociables à mon sens 
* Le model `Contact` qui j'avoue fait plus propre, mais qui du coup apporte plus de confusion que de clarification à mon sens (car celui-ci n'est pas utilisé partout). Limite je ferai un revert ici en faisant une serialisation plus simple, et j'ouvrirai un ticket pour remplacer de manière globale dans le code.

2024-03-25 09:12 UTC, mehdi-farsi commented on app/jobs/deliver_authorization_request_webhook_job.rb
> +  TOTAL_ATTEMPTS = 5
ISO datapass v1

2024-03-25 09:28 UTC, Isalafont commented on app/jobs/deliver_authorization_request_webhook_job.rb
> +      linked_token_manager_id: json['token_id']
Ce naming étant raccord avec la V1, cela permet une meilleure compréhension du code tant que la V1 est en activité.

2024-03-25 09:29 UTC, skelz0r commented on app/jobs/deliver_authorization_request_webhook_job.rb
> +  TOTAL_ATTEMPTS = 5
En regardant le code de DataPass v1, il n'y a pas de max, ça retry à l'infini, juste à la 5e tentative loupée ça envoi un email. Et en réalité on veut ce comportement pour éviter de perdre de l'information.

2024-03-25 09:30 UTC, mehdi-farsi commented on app/mailers/webhook_mailer.rb
> +    init_fail!
Je préfère qu'il y est le mot `fail` dedans pour qu'on comprenne que c'est en lien avec la view `fail.text.erb`.

2024-03-25 09:30 UTC, skelz0r commented on app/jobs/deliver_authorization_request_webhook_job.rb
> +  def serialize
Ok trouvé c'est ici https://api.rubyonrails.org/classes/ActiveJob/Core.html#method-i-serialize

J'avais peur que ça soit une méthode pas réellement documenté (et donc potentiellement qui break plus tard).

2024-03-25 09:37 UTC, skelz0r commented on app/jobs/deliver_authorization_request_webhook_job.rb
> +      linked_token_manager_id: json['token_id']
Il y a 0 dépendance avec la v1 sur cette codebase c'est dommage de propager de la dette.
Si c'était une simple variable c'est pas critique (ça se rename en 2s), mais comme là c'est un champ en base c'est [un peu plus complexe à migrer](https://github.com/ankane/strong_migrations?tab=readme-ov-file#renaming-a-column).

C'est pas bloquant, ça sera juste brainfuck. Donc as u ouiche.

2024-03-25 09:37 UTC, skelz0r commented on app/mailers/webhook_mailer.rb
> +    init_fail!
```suggestion
    instanciate_fail_view_variables
```

?

2024-03-25 09:38 UTC, mehdi-farsi commented on app/models/authorization_definition.rb
> +  def webhook? = value_or_default(@webhook, false)
Je suis pas fan, car j'aimerais bien que chaque definition dans le `definitions.yml` m'indique toutes les features disponible (ou non).

Là, ca rajoute de la compléxité de comprehension dans le code.

2024-03-25 09:42 UTC, mehdi-farsi commented on app/models/concerns/authorization_core/contacts.rb
> +
C'est un pattern vraiment classique. Qui fait appel au `reload` classique et qui vient empty les contacts qui seront reload à la volée au prochain call de `authorization_request.contacts`.

2024-03-25 09:49 UTC, mehdi-farsi commented on app/models/contact.rb
> +class Contact
C'est une V1.

Dans la V2, on va passer via des `ActiveModel::Attributes` en faisant du reshaping du contenu de `authorization_request.data`. Ca permettra d'enlever pas mal de méthodes de méta-programmation dans `contacts.rb`.

2024-03-25 09:52 UTC, mehdi-farsi commented on app/organizers/reopen_authorization.rb
> +    DeliverAuthorizationRequestWebhook
Tu veux faire de la composition d'organizer?

2024-03-25 09:52 UTC, skelz0r commented on app/models/contact.rb
> +class Contact
Ok

2024-03-25 09:53 UTC, skelz0r commented on app/organizers/reopen_authorization.rb
> +    DeliverAuthorizationRequestWebhook
Oui, ça me semble logique vu qu'on va (et veut) systématiquement les 3 ensemble.

2024-03-25 09:54 UTC, skelz0r commented on app/models/concerns/authorization_core/contacts.rb
> +
Je comprends à quoi cela sert, ce que je ne comprends pas c'est pourquoi on en a besoin ? 
C'est pas critique juste étonnant.

2024-03-25 09:57 UTC, mehdi-farsi commented on app/serializers/webhook_event_serializer.rb
> +    :comment,
Ici `:comment` correspond à `AuthorizationRequestEventDecorator#comment`

2024-03-25 10:00 UTC, skelz0r commented on app/serializers/webhook_event_serializer.rb
> +    :comment,
mybad indeed 👍

2024-03-25 10:03 UTC, mehdi-farsi commented on features/support/authorization_request_helpers.rb
> +require 'rspec/expectations'
c'est involontaire.

2024-03-25 10:08 UTC, mehdi-farsi commented on app/jobs/deliver_authorization_request_webhook_job.rb
> +    super.merge('tries_count' => (@attempts || 1) + 1)
`serialize` est appelé au moment ou le job est enqueued. `deserialize` est appelé au moment ou le job est consommé.

2024-03-25 10:13 UTC, mehdi-farsi commented on app/models/authorization_definition.rb
> +  def webhook? = value_or_default(@webhook, false)
On a déjà des tests pour vérifier ça: https://github.com/etalab/data_pass/pull/129/files/787e8439b92207c07e06b9c6956bc647ae9ca5c9#diff-498e93e7a6fd78716fafe85fe2efe540978e0a5eb842a9ac4e81a4037869e3bdR53

2024-03-25 10:14 UTC, mehdi-farsi commented on app/organizers/reopen_authorization.rb
> +    DeliverAuthorizationRequestWebhook
Ok.

2024-03-25 10:16 UTC, skelz0r commented on app/models/authorization_definition.rb
> +  def webhook? = value_or_default(@webhook, false)
En effet ! Cool.

2024-03-25 10:31 UTC, mehdi-farsi commented on features/instruction/historique_habilitation.feature
> +  @DisableBullet
Je me mange des autres erreurs bullets qui me demandent de l'enlever dans les specs:

<img width="1157" alt="Screenshot 2024-03-25 at 11 31 16" src="https://github.com/etalab/data_pass/assets/1397982/df452f79-a04d-45ec-b15c-376c369a26f5">

2024-03-25 10:34 UTC, skelz0r commented on features/instruction/historique_habilitation.feature
> +  @DisableBullet
Tain relou cette erreur quand même..

Du coup laisse comme avant imo, faudra songer à restreindre (avec `stacktrace_excludes` ou un truc du genre)

2024-03-25 11:00 UTC, Isalafont approved these changes

2024-03-25 13:34 UTC, Isalafont approved these changes
LGTM

2024-03-25 13:44 UTC, skelz0r requested changes
Je request un change uniquement pour mon premier commentaire sur l'organizer pour y ajouter celui des notifiers + potentiellement le naming.

Le 2e sur le naming c'est as u ouiche, vu que j'avance exactement le même argument que pour le `linked_token_manager_id` je vous laisse trancher là dessus.

2024-03-25 13:44 UTC, skelz0r commented on app/organizers/trigger_event_deliver_webhook.rb
> +class TriggerEventDeliverWebhook < ApplicationOrganizer
J'aurais ajouté `DeliverAuthorizationRequestNotification` aussi dedans (il a le même comportement que les webhooks en vrai)

Niveau naming ça ne me parait pas assez explicite non plus. 
`ExecuteAuthorizationRequestTransition` / `ExecuteAuthorizationRequestTransitionWithCallbacks` ? Je suis pas très inspiré.

2024-03-25 13:44 UTC, skelz0r commented on app/interactors/deliver_authorization_request_webhook.rb
> +  def target_api = context.authorization_request.definition.id
J'avais pas remarqué à la première review mais c'est brainfuck d'introduire une autre notion. Ça reste certes cantonné dans cet interactor/dans le webhook, mais je ne vois pas l'intérêt d'ajouter une nouvelle notion métier (qui est approximative. `target` c'est vague, `api` c'est faux (dans le cadre de FranceConnect par exemple).

2024-03-25 13:51 UTC, mehdi-farsi commented on app/organizers/trigger_event_deliver_webhook.rb
> +class TriggerEventDeliverWebhook < ApplicationOrganizer
Les notifs ne sont pas appelées à chaque triggering d'event. Du coup,  la seule logique commune entre tous les organizers sont, le triggering de l'event et l'envoi du webhook.

2024-03-25 13:54 UTC, mehdi-farsi commented on app/interactors/deliver_authorization_request_webhook.rb
> +  def target_api = context.authorization_request.definition.id
T'as une idée de nom

2024-03-25 14:49 UTC, skelz0r commented on app/organizers/trigger_event_deliver_webhook.rb
> +class TriggerEventDeliverWebhook < ApplicationOrganizer
> Les notifs ne sont pas appelées à chaque triggering d'event.

C'est clairement un oubli/bug. Comme pointé dans https://github.com/etalab/data_pass/pull/129#discussion_r1535678897 avant les notifs embarquaient les webhooks, ici tu as décidé de split en 2 (ce que je trouve mieux en vrai) mais par contre ça devrait avoir la même logique. A chaque trigger d'event -> webhook + notifier.

2024-03-25 14:51 UTC, skelz0r commented on app/interactors/deliver_authorization_request_webhook.rb
> +  def target_api = context.authorization_request.definition.id
`authorization_definition_id`, c'est ce qui est utilisé partout dans l'app.

(après ici le souci c'est que `AuthorizationDefinition` n'est pas 100% accurate comme nom, faudrait trouver mieux mais dans ce cas là on renomme partout aussi).

2024-03-25 15:12 UTC, mehdi-farsi commented on app/interactors/deliver_authorization_request_webhook.rb
> +  def target_api = context.authorization_request.definition.id
J'ai pas encore d'idée pour un naming clair. Je t'avoue que cette PR est bloquante pour un lancement de Reborn et j'aimerais bien la faire passer. Surtout si c'est juste un problème de renaming qui ne touche pas au fonctionnel.

2024-03-25 15:55 UTC, skelz0r approved these changes

2024-03-25 16:01 UTC, merged