Feat/dat 271/etq instructeur je vois la liste des demandes en cours
etalab/data_pass pull request #143
Opened 2024-04-03 14:41 UTC by Isalafont

2024-04-03 15:22 UTC, skelz0r requested changes
Il faut à minima changer la ligne sur l'organisation qui est fausse.

Ensuite, il y a le `target_api` qui pour moi n'est toujours pas clair, moins précis et inexacte dans certaines situations. 
C'est pas bloquant vu que ça reste dans de la vue, mais au fur et à mesure que ça va grossir dans la code base, on ne comprendra pas pourquoi on appelle un félin aussi un lion, ou un puma, pour parler de la même chose (avec des noms qui ne représentent par ailleurs pas la même chose).

2024-04-03 15:22 UTC, skelz0r commented on app/views/instruction/authorization_requests/index.html.erb
>            </td>
Je trouve ça étrange de renommer `definition-name` en `target-api`, qui est pour le coup moins précis, et faux à 2 égards:

1. `definition` n'est pas forcément une API (ex: FranceConnect) ;
2. `target-api` ne traduit pas qu'il s'agit du nom de la donnée (mais de la donnée elle-même).

Pour illustrer, c'est équivalent à mettre `user` pour `applicant-full-name` par exemple:
1. `user` n'est pas forcément un `applicant` (moins précis) ;
2. `user` ne traduit pas qu'il s'agit du nom du user.

Renommer dans le cadre de cette PR `definition-name` en `target-api` est hors scope imo, ça mériterait à minima un renaming globale dans toute la codebase, histoire d'être consistant.

2024-04-03 15:22 UTC, skelz0r commented on app/views/instruction/authorization_requests/index.html.erb
> +            <%= authorization_request.applicant.current_organization.raison_sociale %>
Ce code est faux: `applicant.current_organization` n'est pas forcément l'organisation de la demande d'habilitation.

```suggestion
            <%= authorization_request.organization.raison_sociale %>
```

2024-04-03 15:22 UTC, skelz0r commented on config/locales/fr.yml
> +            target_api: Nom de l'API
@evaspae je vois que c'est dans tes mockups, en pratique c'est faux, FranceConnect n'est pas une API par exemple.

2024-04-03 15:22 UTC, skelz0r commented on app/views/instruction/authorization_requests/index.html.erb
> +            <%= authorization_request.created_at.strftime("%d/%m/%y") %>
Je pose ça là en remarque (ça méritera imo d'être taclé dans un autre ticket): on veut quelle date ici ? `Date` n'est pas assez clair à mon sens @evaspae cc @SchweisguthN

2024-04-04 06:43 UTC, evaspae commented
> Cette PR ne couvre que les points suivants du ticket
> 
> * [x]  Les colonnes ne correspondent pas à la maquette
> * [ ]  Le titre de la page devrait être au dessus des filtres
> 
> ![Capture d’écran 2024-04-03 à 16 42 20](https://private-user-images.githubusercontent.com/43042737/319233307-b03c0c02-4adc-4174-bc36-3fcd93d77992.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMTI4OTMsIm5iZiI6MTcxMjIxMjU5MywicGF0aCI6Ii80MzA0MjczNy8zMTkyMzMzMDctYjAzYzBjMDItNGFkYy00MTc0LWJjMzYtM2ZjZDkzZDc3OTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA2MzYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNGFhYWU1ZmVmN2U1Y2Q2YmFkOThkY2ExZTg0YmNiYWJmZGFlZjM5ZjE5NzE1OTJkZTg0NWFlYzgxNmQ1M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nuZjw2kYlX8xrWcxZARPmjsYo6d7srlBpMdSw228OCI)
> 
> Petite interrogation
> 
> * Est ce qu'il y a un hover sur la ligne d'habilitation pour ouvrir l'habilitation en place du bouton consulter ?
> * Rappel des deux boutons (messagerie Demandeur / instructeur - demande d'opinion ou demande d'avis entre instructeurs ? )

Effectivement, j'avais pensé à un hover sur la ligne plutôt qu'un bouton "consulter". 

Dans la dernière colonne, le but était de montrer : 
- qu'un nouveau message envoyé par le demandeur a été reçu pour cette habilitation / demande
- qu'une nouvelle réponse à une demande d'avis a été donnée (entre instructeurs)

2024-04-08 09:01 UTC, mehdi-farsi commented
<img width="1272" alt="Screenshot 2024-04-08 at 10 59 48" src="https://github.com/etalab/data_pass/assets/1397982/a7f9c53b-97ca-4544-8c9e-146112434306">

On a trouvé un label `Archivée/Supprimée` pour une demande archivée. Nous allons changer le label en `Archivée`.

@evaspae ca te convient?

2024-04-08 09:08 UTC, skelz0r commented
PI ce renaming est lié à https://linear.app/pole-api/issue/API-2267/transformer-le-archiver-en-soft-delete

2024-04-08 09:53 UTC, mehdi-farsi commented
@evaspae N'hésite pas à refaire une review graphique quand tu peux! 😊

2024-04-08 10:01 UTC, skelz0r approved these changes
La disjonction sur le badge me semble overkill, mais ce n'est pas bloquant.

2024-04-08 10:01 UTC, skelz0r commented on app/helpers/application_helper.rb
> +  def authorization_request_status_badge_translation(authorization_request, scope)
Je me rends compte qu'il n'y a qu'une différence c'est sur le status `submitted`, où il y a côté demandeur `En cours d'instruction` et côté instructeur `En cours`.

imo ça n'a pas de sens de faire une disjonction, le status d'une demande n'est pas lié à qui regarde la demande. Je trouve `En cours d'instruction` plus clair que `En cours` (le `En cours` peut se traduire comment étant dans un état non finie, donc "en construction" (wording de DS btw)).

D'autres suggestions:

* `En cours de validation`
* `En cours de modération`
* `En attente de modération` / `Attente de modération`

On peut combiner les mots/termes aussi à voir.

2024-04-09 09:13 UTC, SchweisguthN commented on app/helpers/application_helper.rb
> +  def authorization_request_status_badge_translation(authorization_request, scope)
Pourquoi je pense que c'est ok : 
- "En cours d'instruction" partout serait en effet plus clair, mais le fait que le label soit long est relou en design du tableau Toutes les habilitations. Et je vois pas de label clair et court.
- Je pense que "En cours d'instruction" et "En cours" se ressemblent assez pour que instructeurs et demandeurs comprennent qu'ils parlent de la même chose. On avait le problème dans le passé où changes_requested s'appelait "A modifier" et "Modifications demandées", et demandeurs et instructeurs se comprenaient pas quand ils en parlaient. Là j'ai l'espoir que les termes soient assez clairs pour que ça soit ok.

2024-04-09 15:23 UTC, merged