Bootstrap API Particulier - Aiga editor
etalab/data_pass pull request #181
Opened 2024-05-07 14:47 UTC by skelz0r

2024-05-07 16:16 UTC, skelz0r commented
Il manquait UN PEU quelques scopes que j'ai ajouté dans un commit supplémentaire.

2024-05-13 08:15 UTC, Isalafont requested changes
Merci pour ta PR !! 
Il y a juste un petit problème d'affichage d'URL et du coup de test cucumber qui ne fail pas alors qu'il devrait ? 🤔 

J'ai également proposé de rajouter 2 margin top et bottom sur l'alert et les submit buttons pour plus de clarté sur la page.  :)

2024-05-13 08:15 UTC, Isalafont commented on app/views/authorization_request_forms/api_particulier_aiga.html.erb
> +  <p class="fr-alert fr-alert--info">
Peut-on rajouter du margin pour ne pas coller l'alerte ? `fr-my-3w`

2024-05-13 08:15 UTC, Isalafont commented on app/views/authorization_request_forms/api_particulier_aiga.html.erb
> +  <%= render partial: 'authorization_request_forms/shared/submit_buttons', locals: { f: f } %>
et également du margin top et bottom autour des submits buttons `fr-my-3w`
fichier : `app/views/authorization_request_forms/shared/_submit_buttons.html.erb`

2024-05-13 08:15 UTC, Isalafont commented on config/authorization_request_forms.yml
> +      cadre_juridique_url: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000045213315
L'url ne s'affiche pas pour le `formulaires/api-particulier-aiga/demande/xx` ? 

<img width="1140" alt="Capture d’écran 2024-05-13 à 10 09 57" src="https://github.com/etalab/data_pass/assets/43042737/0a0631e6-815c-49a6-be23-a72dbf710776">


Capture screenshot de la demande 
![screencapture-localhost-3000-formulaires-api-particulier-aiga-demande-12-2024-05-13-10_11_37](https://github.com/etalab/data_pass/assets/43042737/53108384-c878-447c-aa0e-4789eacfd9c8)

2024-05-13 08:15 UTC, Isalafont commented on features/habilitations/api_particulier/soumission.feature
> +  Scénario: Je soumets une demande d'habilitation Aiga valide
Du coup, je me demande comment la feature peut quand même passer alors que l'url ne s'affichant pas sur le formulaire bloquant ainsi la soumission de l'habilitation ?

2024-05-13 08:21 UTC, skelz0r commented on app/views/authorization_request_forms/api_particulier_aiga.html.erb
> +  <p class="fr-alert fr-alert--info">
J'ai c/c `app/views/authorization_request_forms/api_entreprise_through_editor.html.erb`, donc je vais l'ajouter au 2.

2024-05-13 08:23 UTC, skelz0r commented on config/authorization_request_forms.yml
> +      cadre_juridique_url: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000045213315
Je l'ai retiré plus loin https://github.com/etalab/data_pass/pull/181/commits/dcdd8382af39c0dc016a6928397c72b4adf35f20

2024-05-13 08:24 UTC, skelz0r commented on features/habilitations/api_particulier/soumission.feature
> +  Scénario: Je soumets une demande d'habilitation Aiga valide
Je ne comprends pas ta remarque sur l'url. Ici c'est la ligne 39+40 qui font la création de la demande.

2024-05-13 08:25 UTC, skelz0r commented on app/views/authorization_request_forms/api_particulier_aiga.html.erb
> +  <%= render partial: 'authorization_request_forms/shared/submit_buttons', locals: { f: f } %>
Il faut avoir en tête que si je fais cette modification ça sera sur l'ensemble des formulaires, on est d'accord ?

2024-05-13 08:26 UTC, skelz0r commented on features/habilitations/api_particulier/soumission.feature
> +  Scénario: Je soumets une demande d'habilitation Aiga valide
C'est la même logique que pour API Entreprise, je n'ai rien modifié comme logique (je n'ai d'ailleurs rien écrit c'est copilot qui a écrit le code).

2024-05-13 08:27 UTC, skelz0r commented on app/views/authorization_request_forms/api_particulier_aiga.html.erb
> +  <%= render partial: 'authorization_request_forms/shared/submit_buttons', locals: { f: f } %>
Je l'ai ajouté là https://github.com/etalab/data_pass/pull/181/commits/eed85f83eb37aee6d44ab14116770151d57d2f2d ça se revert facilement dtf

2024-05-13 08:35 UTC, Isalafont commented on features/habilitations/api_particulier/soumission.feature
> +  Scénario: Je soumets une demande d'habilitation Aiga valide
Je ne sais pas non plus pourquoi l'url ne s'affiche pas mais en testant en local, l'url ne s'affiche pas sur le formulaire bloquant ainsi la soumission de la demande. Est ce que tu as également ce cas la en local ?

2024-05-13 08:38 UTC, Isalafont commented on config/authorization_request_forms.yml
> -      cadre_juridique_url: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000045213315
Pourquoi tu supprimes l'url ici ?

2024-05-13 08:46 UTC, skelz0r commented on features/habilitations/api_particulier/soumission.feature
> +  Scénario: Je soumets une demande d'habilitation Aiga valide
Je viens de tester en local j'ai pu créer et soumettre une demande via ce formulaire. Qu'est-ce qui ne fonctionne pas selon toi ?

2024-05-13 08:54 UTC, Isalafont commented on config/authorization_request_forms.yml
> -      cadre_juridique_url: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000045213315
Donc l'utilisateur doit remplir lui même l'URL ?

2024-05-13 08:58 UTC, skelz0r commented on config/authorization_request_forms.yml
> -      cadre_juridique_url: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000045213315
Oui (ou dans la plupart des cas téléverser la délibération). 

Si tu veux explorer voir à quoi ressemble des délibérations API Particulier pour ce cas d'usage -> https://metabase.entreprise.api.gouv.fr/dashboard/50-datapass-exploration?nom_de_l%27api_(target_api)=api_particulier&d%25C3%25A9marche=aiga&status_de_l%27habilitation=validated

2024-05-13 09:03 UTC, Isalafont commented on app/views/authorization_request_forms/api_particulier_aiga.html.erb
> +  <%= render partial: 'authorization_request_forms/shared/submit_buttons', locals: { f: f } %>
Merci ! 
Oui j'ai en tête que ce sera sur tous les formulaires, mais dans tous les cas, nous manquions de margin (les submits buttons sont tout le temps collés à la div de fin de formulaire et du footer et ce n'est pas idéal visuellement parlant)

2024-05-13 09:03 UTC, Isalafont commented on config/authorization_request_forms.yml
> -      cadre_juridique_url: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000045213315
merci pour la précision, dans ce cas effectivement ça prend sens ! 
tout est ok pour moi 👍🏻

2024-05-13 09:05 UTC, Isalafont commented on features/habilitations/api_particulier/soumission.feature
> +  Scénario: Je soumets une demande d'habilitation Aiga valide
J'avais en tête que l'url était automatiquement pré-rempli mais si on doit la rajouter manuellement (ou un document à joindre), tout fonctionne oui.

2024-05-13 09:06 UTC, Isalafont approved these changes

2024-05-13 09:06 UTC, skelz0r commented on features/habilitations/api_particulier/soumission.feature
> +  Scénario: Je soumets une demande d'habilitation Aiga valide
l'url dont tu parles est celui de l'url du cadre juridique okkkk je ne comprenais pas !
Donc dans ce cas là OK c'est résolu plus bas.

2024-05-13 09:06 UTC, merged