Introduce duree_conservation_donnees_caractere_personnel_justification
etalab/data_pass pull request #191
Opened 2024-05-15 12:08 UTC by skelz0r

Same logic as v1: only displayd if > 36 months.

2024-05-15 12:09 UTC, skelz0r commented
related https://mattermost.incubateur.net/betagouv/pl/zso1qukf63rcugeb38ijxmchkr

2024-05-15 14:35 UTC, Isalafont requested changes

2024-05-15 14:35 UTC, Isalafont commented on app/views/authorization_request_forms/shared/_personal_data.html.erb
> +    <div class="fr-alert fr-alert--warning">
peux tu me rajouter du margin s'il te plait ? `fr-my-3w`
merci :)

2024-05-15 15:06 UTC, Isalafont commented on app/views/authorization_request_forms/shared/_personal_data.html.erb
> +    <div class="fr-alert fr-alert--warning">
Si tu veux on push nous le changement ;)

2024-05-16 07:45 UTC, skelz0r commented on app/views/authorization_request_forms/shared/_personal_data.html.erb
> +    <div class="fr-alert fr-alert--warning">
Vous pouvez faire des suggestions btw comme ça ça s'applique tout de suite.

2024-05-16 07:46 UTC, skelz0r commented on app/views/authorization_request_forms/shared/_personal_data.html.erb
> +    <div class="fr-alert fr-alert--warning">
Vous pouvez faire des suggestions btw comme ça ça s'applique tout de suite.

2024-05-16 07:46 UTC, skelz0r commented on app/views/authorization_request_forms/shared/_personal_data.html.erb
> +    <div class="fr-alert fr-alert--warning">
```suggestion
    <div class="fr-alert fr-alert--warning fr-my-3w">
```

2024-05-16 07:46 UTC, merged