Instruction: implement search on ID, redirects matches and authorized
etalab/data_pass pull request #224
Opened 2024-06-04 14:57 UTC by skelz0r

<img width="1255" alt="Screenshot 2024-06-04 at 18 00 44" src="https://github.com/etalab/data_pass/assets/1279968/280b14c8-b5ab-4d75-a404-d286bb53f570">

2024-06-04 16:06 UTC, skelz0r commented
Thread de discussion ici https://mattermost.incubateur.net/betagouv/pl/54rf5y18bj8izqk4gdchx3iohy

Les 2 autres PRs qu'on ne conservera pas du coup https://github.com/etalab/data_pass/pull/223 https://github.com/etalab/data_pass/pull/222

2024-06-05 11:19 UTC, Isalafont requested changes
Si je récapitule bien, on fait actuellement une recherche uniquement par ID d'authorization_request (demande) ici.

Or si on ne trouve pas d'exact matching d'ID, on se retrouve avec une liste de demande dans le tableau pouvant récupérer des infos de date se trouvant par dans le cadre légal... 
voir screenshot 
<img width="1287" alt="Capture d’écran 2024-06-05 à 12 58 45" src="https://github.com/etalab/data_pass/assets/43042737/879495a1-e79e-41d2-8d14-125e0aa77232">
 
Le filtre de recherche ne fonctionne pas actuellement pour faire des recherches par Nom de famille ou email de demandeur, ni pour toute autres info de la demande comme nom du projet contact tech, intitulé de la demande comme demandé / suggéré par Charlotte.
<img width="1287" alt="Capture d’écran 2024-06-05 à 13 17 31" src="https://github.com/etalab/data_pass/assets/43042737/9645fd09-6490-4d0d-8399-2bba1984c931">

<img width="1287" alt="Capture d’écran 2024-06-05 à 13 17 46" src="https://github.com/etalab/data_pass/assets/43042737/8da234c0-6884-4813-a2bc-9bccd1080a1a">

 Je suggère dans ce cas de retirer dans le hint l'information relative à l'intitulé pouvant induire en erreur nos utilisateurs. 
 
La demande de Charlotte est également de pouvoir voir toutes les demandes rattachées au nom du demandeur. Donc ne pas forcement être redirigée vers une demande spécifique mais vers une liste de demande de ce demandeur.

2024-06-05 11:41 UTC, skelz0r commented
> Si je récapitule bien, on fait actuellement une recherche uniquement par ID d'authorization_request (demande) ici.

Non.

La spec exacte:

```
Instruction: habilitation search
  when we use an id
    when we can not see this authorization request
      does not redirects to the authorization request
    when we can see this authorization request
      redirects to the authorization request
  when we search with text, state and type
    renders only one authorization request
  when we search with state and type
    renders 2 valids authorization requests
  when we use organization siret
    renders authorization request linked to this siret
  when we search with text and type
    renders 2 valids authorization requests
  when we search with text and state
    renders 2 valids authorization requests
```

Le fichier: spec/features/instruction/search_spec.rb

> Or si on ne trouve pas d'exact matching d'ID, on se retrouve avec une liste de demande dans le tableau pouvant récupérer des infos de date se trouvant par dans le cadre légal...

Oui. Quelle est l'alternative ?

> Le filtre de recherche ne fonctionne pas actuellement pour faire des recherches par Nom de famille ou email de demandeur, ni pour toute autres info de la demande comme nom du projet contact tech, intitulé de la demande comme demandé / suggéré par Charlotte.

Le demandeur n'est en effet pas encore géré, mais ça va venir (dans une prochaine PR pour éviter de faire N conflits). Par contre tout ce qui est dans la clé `data` est dans la recherche.

Exemple avec l'intitulé: https://api-entreprise.v2.datapass.api.gouv.fr/instruction/demandes?q%5Bwithin_data_or_organization_siret_cont%5D=Espace+agent+sur+annuaire&q%5Bstate_eq%5D=&button=
Avec le contact technique: https://api-entreprise.v2.datapass.api.gouv.fr/instruction/demandes?q%5Bwithin_data_or_organization_siret_cont%5D=loic.delmaire&q%5Bstate_eq%5D=&button=
Avec un lien de texte juridique spécifique: https://api-entreprise.v2.datapass.api.gouv.fr/instruction/demandes?q%5Bwithin_data_or_organization_siret_cont%5D=https%3A%2F%2Feur-lex.europa.eu%2Feli%2Freg%2F2013%2F1303%2Foj%2Ffra&q%5Bstate_eq%5D=&button=

> Je suggère dans ce cas de retirer dans le hint l'information relative à l'intitulé pouvant induire en erreur nos utilisateurs.

Pour le coup le hint dans le placeholder me semble plus efficace qu'un texte sans indication. Par exemple le numéro de siret n'est pas une information de la demande, pourtant ça marche.

> La demande de Charlotte est également de pouvoir voir toutes les demandes rattachées au nom du demandeur. Donc ne pas forcement être redirigée vers une demande spécifique mais vers une liste de demande de ce demandeur.

Ce qui sera le cas.

2024-06-05 11:43 UTC, skelz0r commented
Je re-request une review à la suite de ma réponse du coup. 
Je peux implémenter la recherche sur le demandeur dans cette PR si on est OK sur l'approche (par rapport aux 2 autres PRs).

2024-06-05 13:04 UTC, Isalafont commented
> Or si on ne trouve pas d'exact matching d'ID, on se retrouve avec une liste de demande dans le tableau pouvant récupérer des infos de date se trouvant par dans le cadre légal...
> 
> Oui. Quelle est l'alternative ?

Pour ne pas induire en erreur nos utilisatrices, afficher un tableau vide si aucune demande ne match avec un id ? Nos users vont se retrouver à ouvrir une par une chaque demande pour comprendre pourquoi elles sont présentées dans le tableau. (et voir que ça correspond à une date par ex 😅) 

J'avais bien compris que tout ce qui se trouvait dans la clé Data était rendu (quand ça m'a ressorti toutes les habilitations avec la date du 10 aout dans le texte de loi) 

> Pour le coup le hint dans le placeholder me semble plus efficace qu'un texte sans indication. Par exemple le numéro de siret n'est pas une information de la demande, pourtant ça marche.

Si le numéro de Siret fonctionne, c'est justement car c'est un numéro trop spécifique mais, si cela fonctionne pour le moment, c'est d'avantage un effet de bord que réellement voulu. => A fix plus tard ? 

> Je peux implémenter la recherche sur le demandeur dans cette PR si on est OK sur l'approche (par rapport aux 2 autres PRs).

Je n'ai pas encore lu les 2 autres PR mais ce serait bien d'implémenter la recherche sur le demandeur dans cette PR car c'est un des critères les plus utilisés pour la recherche (et nécessaire à Charlotte ! 😄)

2024-06-05 13:25 UTC, skelz0r commented
> Pour ne pas induire en erreur nos utilisatrices, afficher un tableau vide si aucune demande ne match avec un id ?

Donc tu suggères, dans le cas d'une recherche avec un nombre entier, de renvoyer un résultat vide plutôt que d'effectuer la recherche dans toutes les demandes ? Moi ça me va, parce que de toute façon sur de la spécification de recherche il n'y a pas de bonne réponse.

> Si le numéro de Siret fonctionne, c'est justement car c'est un numéro trop spécifique mais, si cela fonctionne pour le moment, c'est d'avantage un effet de bord que réellement voulu. => A fix plus tard ?

C'est iso à la prod, et je crois que c'est le plus gros cas d'usage de la recherche. D'ailleurs c'est une feature car c'est explicitement implémenté. Au passage la v1 fait aussi la recherche sur la raison sociale et le zip code.

> Je n'ai pas encore lu les 2 autres PR mais ce serait bien d'implémenter la recherche sur le demandeur dans cette PR car c'est un des critères les plus utilisés pour la recherche (et nécessaire à Charlotte ! 😄)

Il n'y a pas besoin de lire les 2 autres PRs, uniquement le titre + https://mattermost.incubateur.net/betagouv/pl/54rf5y18bj8izqk4gdchx3iohy

---

J'en conclus donc que je dois faire 2 changements:

1. J'implémente la recherche sur le demandeur (email + nom) ;
2. Si on cherche exclusivement un ID et qu'il ne correspond pas à une demande, alors on renvoi un tableau vide au lieu de chercher dans toutes les demandes.

2024-06-05 13:41 UTC, Isalafont commented
> Donc tu suggères, dans le cas d'une recherche avec un nombre entier, de renvoyer un résultat vide plutôt que d'effectuer la recherche dans toutes les demandes ? Moi ça me va, parce que de toute façon sur de la spécification de recherche il n'y a pas de bonne réponse.

Ce qui me parait justement étrange c'est que si je recherche un id (ex id: 29), ça me ressort actuellement en local toutes les demandes avec le chiffres 29 apparaissant dans la demande, y compris si le numéro 29 apparait dans le lien relatif au cadre juridique. Ce qui semble très étrange et surtout risque de susciter des incompréhensions (pourquoi est ce que l'on propose cette demande alors que ça ne correspond pas à l'id ?)
  

> C'est iso à la prod, et je crois que c'est le plus gros cas d'usage de la recherche. D'ailleurs c'est une feature car c'est explicitement implémenté. Au passage la v1 fait aussi la recherche sur la raison sociale et le zip code.

Sur V1 on filtrait selon les attributs suivant : 
`%w[id siret nom_raison_sociale intitule target_api status zip_code team_members.email only_with_unprocessed_messages].include? key`

ce qui est un peu différent de notre cas en V2.

2024-06-10 13:09 UTC, Isalafont requested changes

2024-06-10 13:09 UTC, Isalafont commented on app/models/user.rb
> +      family_name
Est ce que les instructeurs/trices n'utilisent pas le given_name également ? Surtout si on a le cas d'utilisateurs ayant le même nom de famille ?

2024-06-10 13:17 UTC, skelz0r commented on app/models/user.rb
> +      family_name
Comme je l'ai dit plus haut, on peut s'amuser à l'inclure comme l'exclure, ça ne répondra jamais à l'ensemble des cas.
Exemple concret: tu cherches un demandeur qui a un nom de famille "Martin", ça va sortir tous les gens qui ont comme prénom "Martin", ça sera le bordel.
Est-ce que ce cas est plus légitime que celui que tu décris ? Non. Est-ce que le cas que tu décris est plus légitime ? Non plus.
C'est du best effort, de manière général la recherche c'est la PIRE des solutions sur un produit. Il n'y a pas de bonne solution, et on devrait faire l'effort de supprimer la recherche globale plutôt que de tenter de l'améliorer.

2024-06-10 13:19 UTC, skelz0r commented on app/models/user.rb
> +      family_name
Du coup je le mets ou non ?

2024-06-10 13:21 UTC, Isalafont commented on app/models/user.rb
> +      family_name
Donc on ne peut pas dans ton cas filtrer sur given_name + family_name qui fera ressortir toutes les habilitations matchant ce champs de recherche ? 
ce sera forcémant l'un ou l'autre ?

2024-06-10 13:24 UTC, skelz0r commented on app/models/user.rb
> +      family_name
Je ne suis pas sûr de comprendre ton commentaire. Peux-tu donner des exemples ?

2024-06-10 14:24 UTC, Isalafont commented on app/models/user.rb
> +      family_name
C'est simple si je veux chercher l'utilisateur qui s'appelle "DELAHOULIERE Ingrid" ? (family_name + given_name), la recherche ne fonctionnera pas en l'état il me semble ?

2024-06-10 14:47 UTC, skelz0r commented on app/models/user.rb
> +      family_name
Non en effet, car on cherche l'ensemble des termes par champ, et non de manière splitté.

On peut s'amuser à spécifier ce genre de recherche, mais on va rentrer dans des spécifications assez complexes. Des exemples top of mind:

* Jean Dupond (et non Dupond Jean) ;
* Jean De Dupond ;
* Jean de la Dupond ;
* Jean Marie Dupond.

imo mieux vaut shipper sans, implémenter du tracking, et monitorer les mauvais résultats (ou demander en interview quali)

2024-06-10 14:59 UTC, Isalafont commented on app/models/user.rb
> +      family_name
Bon ok; on merge comme ça.

2024-06-10 15:06 UTC, merged