Feature/dat 411 etq d si la modalite dappel formulaire de collecte du
etalab/data_pass pull request #251
Opened 2024-06-24 10:07 UTC by Isalafont

Work on view for Deliberation view : 

So far: 

![screencapture-localhost-3000-formulaires-api-particulier-arpege-concerto-demande-126-etapes-cadre-juridique-2024-06-26-17_01_20](https://github.com/etalab/data_pass/assets/43042737/59d34fc4-52a4-4d32-af80-ba1aa105692f)

- [ ] Encore besoin de revoir les wordings 
- [x] Gérer le bug d'affichage lorsque l'on est sur les autres formulaire d'api 
`undefined method html_safe' for nil`   `<%= f.wording_for('deliberation_link', 'legal').html_safe %>` 
- [x] Dans le formulaire, le champ "précisez la nature et les références …" sera affiché pré-rempli et désactivé => reporté dans le [ticket 437](https://linear.app/pole-api/issue/DAT-437/etq-d-si-je-souhaite-modifier-les-informations-du-cadre-juridique)
- [x]  Fixer les tests 
- [x] Clean les commits 
- [ ] Review

2024-06-27 08:11 UTC, evaspae commented
**Pour les typos :** 
- Le sous titre "les justificatifs de votre cadre juridique" doit être en bold 18px (corps de texte/texte article)
"Veuillez joindre la délibération du conseil municipal" -> bold 16 px (corps de texte / texte standard)

- "Veuillez nous indiquer l'url ..." -> bold 16 px (corps de texte / texte standard)


**Pour les espacements :** 
- Espace entre "pour les données CNAF" + sous titre et le champ de texte -> mettre max 24px

- Entre "Veuillez joindre la délibération du conseil municipal" et "pour en savoir plus ..." -> ajouter minimum 8px

- Juste après ce bloc et avant l'ajout de fichier -> diminuer à 24px maximum 

- Distance entre le dernier élément et l'encadrement du bloc -> maximum 32 px

2024-06-27 15:16 UTC, Isalafont commented
Y'a un truc qui me rend chèvre avec le DSFR. 
j'ai fait une modification sur la page et du coup, le bloc de text area ne prend plus toute la page. 
![screencapture-chrome-extension-fdpohaocaechififmbbbbbknoalclacl-editor-html-2024-06-27-17_15_06](https://github.com/etalab/data_pass/assets/43042737/032664e3-6c0c-4f55-8af3-aa905773bd88)

@skelz0r si tu as une idée du pourquoi ?

2024-06-27 15:42 UTC, skelz0r commented
@Isalafont c'est imo une div mal fermé, faut inspecter le html généré pour savoir.

Pour rspec faut ignorer des patterns dans i18n-tools https://github.com/etalab/data_pass/blob/develop/config/i18n-tasks.yml#L116 (dans ces eaux là, ça dépend de l'erreur que tu as).

2024-07-01 10:32 UTC, Isalafont commented
**Pour les forms Api Particulier**

![screencapture-localhost-3000-formulaires-api-particulier-arpege-concerto-demande-136-2024-07-01-12_24_48](https://github.com/etalab/data_pass/assets/43042737/4f8864ba-5fce-43e5-987f-b64f8b14203b)

---- 

**Pour les autres formulaires**

![screencapture-localhost-3000-formulaires-api-entreprise-marches-publics-demande-142-etapes-cadre-juridique-2024-07-01-12_24_21](https://github.com/etalab/data_pass/assets/43042737/bd5cb747-e2f0-4501-9717-090c1db691c6)

2024-07-01 13:16 UTC, skelz0r requested changes
Je pense que tu peux tout rebase en 1 commit ou 2 commits, vu que c’est globalement la peinture de la vue legal + la configuration pour API Particulier.

2 remarques et 1 question :

* Globalement tu peux remplacer partout `deliberation` par `cadre_juridique` (ou `legal` vu que l’étape est legal)
* Le `wording_for(attribute, kind)` est vraiment peu intuitif (ça devrait être dans l’autre sens en vrai), faudrait potentiellement refactoriser mais là comme ça j’ai pas d’idée. Peux-être `wording_for(key)` (on concatene `kind` et `attribute`)
* Pourquoi y-a t’il des labels avec des `*` à la fin ? C’est pour mettre en avant le caractère obligatoire ? Si oui, pour moi il faut déporter ça dans le framework rails et non les wordings, cela devrait se baser sur la couche modèle et non la vue (on peut faire un ticket à part).

2024-07-01 13:16 UTC, skelz0r commented on app/views/authorization_request_forms/shared/_legal.html.erb
> +  <% end %>
La vue étant générique, tu devrais te baser sur le framework de formulaires. La notion de `cnaf` est spécifique à API Particulier et n'est donc pas générique.

Vu où c'est, je mettrais `subtitle` et `description`.

```suggestion
  <% if f.wording_for('subtitle', 'legal') %>
    <p class="fr-h5 legal-subtitle">
      <%= f.wording_for('subtitle', 'legal') %>
    </p>
  <% end %>
  <% if f.wording_for('description', 'legal') %>
    <p>
      <%= f.wording_for('description', 'legal') %>
    </p>
  <% end %>
```

Et du coup dans la configuration de wordings tu peux mettre des clés plus générique https://github.com/etalab/data_pass/pull/251/files#diff-d793f1d16915c72a56d91160be67550a5b514788f4640b3fe4d93594cd5efd1bR215

J'ai appliquer quelque chose de similaire ici: https://github.com/etalab/data_pass/commit/339ac7e6bca0758c5cf6e60fb32fa42e1dd9ebce#diff-5ef92f887d14b6fb4fd118342b4d0fecb6994533b601fc0da0c02306b203bf51R7

2024-07-01 13:16 UTC, skelz0r commented on app/views/authorization_request_forms/shared/_legal.html.erb
>    </div>
Même remarque qu'au dessus. Il faut que ça soit plus générique que `deliberation.title`. En voyant les screenshots pour moi ce sont comme clés `cadre_juridique_document.title` et `cadre_juridique_document.description` (ou `hint`, le design ne respectant pas le DSFR je ne sais pas à quoi cela correspond.)

2024-07-01 13:16 UTC, skelz0r commented on app/views/authorization_request_forms/shared/_legal.html.erb
> +  <p class="deliberation-text__bold"><%= f.wording_for('text_url_traitement_donnee', 'legal') %></p>
```suggestion
  <p class="deliberation-text__bold"><%= f.wording_for('cadre_juridique_url.title', 'legal') %></p>
```

2024-07-01 14:32 UTC, Isalafont commented
> * Pourquoi y-a t’il des labels avec des `*` à la fin ? C’est pour mettre en avant le caractère obligatoire ? Si oui, pour moi il faut déporter ça dans le framework rails et non les wordings, cela devrait se baser sur la couche modèle et non la vue (on peut faire un ticket à part).

J'ai suivi la maquettes, je pense que c'est surtout pour attirer visuellement l'attention sur ce texte que l'* a été proposé. 
Après on ne peut pas valider si on n'a pas rajouté le document et l'url mais c'est une question que l'on peut poser à @evaspae !

2024-07-02 07:37 UTC, evaspae commented
Les "*" c'était effectivement pour montrer visuellement les infos obligatoires, si elles ne sont pas complétées, le bouton "suivant" doit être grisé dans le formulaire à étape / on ne peut pas soumettre.

2024-07-02 07:46 UTC, skelz0r commented
> Les "*" c'était effectivement pour montrer visuellement les infos obligatoires, si elles ne sont pas complétées, le bouton "suivant" doit être grisé dans le formulaire à étape / on ne peut pas soumettre.

Ce sont 2 features différentes imo. J'ai reporté https://linear.app/pole-api/issue/DAT-442 et https://linear.app/pole-api/issue/DAT-441

2024-07-02 13:19 UTC, skelz0r commented
@Isalafont pour le rebase tu fais 2 commits:

1. Avec juste les locales
2. Avec le reste (qui correspond au redesign entier de la page)

Donc tu peux tout rebase en 1 seul commit, puis annuler le commit, et refaire 2 commits

2024-07-02 14:50 UTC, skelz0r commented
dès que t'as supprimé https://github.com/etalab/data_pass/pull/251/commits/468694af4b7742b9a2957cc46fea85062e098975#r1662685017 + que c'est green tu peux merge

2024-07-02 14:50 UTC, Isalafont commented on app/views/authorization_request_forms/shared/_deliberation.html.erb
> +<%= f.info_for(:legal) %>
je viens de le faire (c'était pour voir si tu suivais 🤣)

2024-07-02 14:55 UTC, merged