Implement HubEECERTDCBridge
etalab/data_pass pull request #253
Opened 2024-06-26 09:10 UTC by skelz0r

2024-07-08 15:07 UTC, Isalafont commented on spec/services/hubee_api_client_spec.rb
> +    # => {"access_token"=>"token"}
@skelz0r J'aurais bien besoin d'un petit coup de main ici, je ne comprends pas pourquoi ici `create_organization` me renvoie l'access_token. 

Et je suis preneuse de tes retours si je pars dans la bonne direction ou pas ! 
🙏

2024-07-08 16:39 UTC, skelz0r commented on spec/services/hubee_api_client_spec.rb
> +    # => {"access_token"=>"token"}
Parce que tu stubbes la connexion faraday L4, et tu lui fais renvoyer en `post` la réponse qui a comme payload l'access token. 

Ici comme c'est un post, ça renvoi le access token donc.

C'est en bonne voie, y'a 2 gros points qui sont à revoir:

1. Il ne faut pas que tu stubbes la connexion Faraday, mais plutôt que tu te bases à 100% sur `webmock` -> https://github.com/bblimke/webmock
2. `find_or_create_organization` n'a pas lieu d'être dans le client API, mais plutôt dans le bridge -> le client API doit vraiment rester sur un rôle très bas niveau qui doit coller le plus possible à 1 methode = 1 appel API.

Pour 2. en fait, dans le bridge tu fais ça:

```ruby
def perform
  hubee_organization_payload = find_or_create_organization(organization)

  # create subscription
end

def find_or_create_organization(organization)
  # Niveau interface on peut affiner, par exemple construire directement `SI-#{siret}-#{process_code}`, c'est à voir/débattre
  hubee_api_client.find_organization(organization.siret, organization.code_commune)
rescue Error # à définir ici, on peut catch `Faraday::NotFoundError`, ou s'amuser à faire des exceptions customs, à défini dans l'interface du client
  # Niveau interface c'est aussi à affiner, typiquement y'a pas le DataPass ID dans `insee_payload`
  hubee_api_client.create_organization(organization.insee_payload)
end
```

Pour 1., par exemple pour `find_organization` ça donnerait un truc du genre (j'ai pas testé mais c'est pour la logique)

```ruby
subject(:find_organization) { described_class.find_organization(organization.siret, organization.code_commune) }

before do
  stub_request(:post, hubee_auth_url).to_return(
    body: { access_token: 'access_token' }.to_json
  )
end

context 'when organization exists on hubee' do
  let(:hubee_organization_payload) { { id: '1' } }
  let!(:stubbed_find_organization) do
    stub_request(:get, hubee_get_organization_url).to return(
      status: 200,
      body: hubee_organization_payload.to_json
    )
  end

  it 'calls the requested url' do
    subject

    expect(stubbed_find_organization).to have_been_requested
  end

  it 'returns the payload' do
    expect(subject).to eq(hubee_organization_payload)
  end
end
```

2024-07-09 07:46 UTC, Isalafont commented on spec/services/hubee_api_client_spec.rb
> +    # => {"access_token"=>"token"}
dans le create_organization, je lui passe un body pour que
```ruby
def organization_body(organization, authorization_request)
    {
      type: 'SI',
      companyRegister: organization.siret,
      branchCode: organization.code_commune,
      name: organization.denomination,
      code: organization.sigle_unite_legale,
      country: 'France',
      postalCode: organization.code_postal,
      territory: organization.libele_commune,
      email: authorization_request.data['administrateur_metier_email'],
      phoneNumber: authorization_request.data['administrateur_metier_phone_number'].delete(' ').delete('.').delete('-'),
      status: 'Actif'
    }
  end
```

et je me posais la question de l'email et le phone_number, est ce que c'est celui de la demande de l'authorization_request ou cela vient d'ailleurs ? 
Auquel cas, d'où car je ne vois nul part dans la payload Insee ces info ?

2024-07-10 08:54 UTC, skelz0r reviewed
Cf mes coms, c'est principalement du style/logique de tests.

2024-07-10 08:54 UTC, skelz0r commented on spec/services/hubee_api_client_spec.rb
> +
```suggestion
      before do
        stub_request(:post, hubee_api_client.send(:hubee_auth_url))
          .to_return(status: 200, headers: { 'Content-Type' => 'application/json' }, body: { "access_token" => "token" }.to_json)
      end

```

C'est déjà fait ligne 4

2024-07-10 08:54 UTC, skelz0r commented on spec/services/hubee_api_client_spec.rb
> +  describe '#access_token' do
Tu n'as pas besoin de tester cette méthode, pour une unique raison: il s'agit d'une méthode privée (car la méthode ne sera jamais utilisé en dehors de cette classe). On ne teste pas les méthodes privés.

2024-07-10 08:54 UTC, skelz0r commented on spec/services/hubee_api_client_spec.rb
> +    context 'when organization already exist' do
Faut mettre le before dans le context

```suggestion
    context 'when organization already exist' do
      before do
        stub_request(:get, "#{hubee_api_client.send(:api_host)}/referential/v1/organizations/SI-#{siret}-#{code_commune}")
          .with(
            headers: { 'Authorization' => "Bearer #{access_token}" })
          .to_return(status: 200, body: hubee_organization.to_json, headers: { 'Content-Type' => 'application/json' })
      end

```

2024-07-10 08:54 UTC, skelz0r commented on spec/services/hubee_api_client_spec.rb
> +      .to_return(status: 200, headers: { 'Content-Type' => 'application/json' }, body: { "access_token" => "token" }.to_json)
```suggestion
      .to_return(status: 200, headers: { 'Content-Type' => 'application/json' }, body: { "access_token" => access_token }.to_json)
```

2024-07-10 08:54 UTC, skelz0r commented on spec/services/hubee_api_client_spec.rb
> +      it 'returns the organization' do
```suggestion
      it 'returns the hubee organization payload' do
```

2024-07-10 08:55 UTC, skelz0r commented on spec/services/hubee_api_client_spec.rb
> +  describe '#access_token' do
Je dirais même juste supprime tout le bloc.

2024-07-10 13:40 UTC, skelz0r commented on spec/services/hubee_api_client_spec.rb
> +      end
C'est le même contexte, 404 veut dire "not found"

```suggestion
    context 'when organization does not exist' do
      let(:siret) { '21050136700010' }
      let(:code_commune) { '05245' }

      before do
        stub_request(:get, "#{hubee_api_client.send(:api_host)}/referential/v1/organizations/SI-#{siret}-#{code_commune}")
          .with(
            headers: { 'Authorization' => "Bearer #{access_token}" })
          .to_return(status: 404, body: '', headers: { 'Content-Type' => 'application/json' })
      end

      it 'raises a Faraday::ResourceNotFound error' do
        expect { get_organization }.to raise_error(Faraday::ResourceNotFound)
      end
    end
```

2024-07-18 15:28 UTC, Isalafont commented
⚠️ Il ne restera plus qu'a rajouter les credentials de production et les credentials pour l'environnement staging et sandbox

2024-07-18 15:36 UTC, JeSuisUnCaillou commented
> ⚠️ Il ne restera plus qu'a rajouter les credentials de production et les credentials pour l'environnement staging et sandbox

Tu ne le a pas ?

2024-07-18 15:41 UTC, Isalafont commented
> > ⚠️ Il ne restera plus qu'a rajouter les credentials de production et les credentials pour l'environnement staging et sandbox
> 
> Tu ne le a pas, et ne peux pas les ajouter ?

Je me sentirais plus à l'aise de vérifier que j'ai bien les bon credentials pour la prod avant. ^^

2024-07-18 15:44 UTC, skelz0r commented
Je les aies btw je peux les ajouter.

2024-07-18 15:53 UTC, JeSuisUnCaillou requested changes
Je te poste déjà cette review, par ce qu'il y a tout le lint à faire.
Je me penche sur le reste ensuite.

2024-07-18 15:53 UTC, JeSuisUnCaillou commented on .rubocop.yml
> +    - "spec/services/hubee_api_client_spec.rb"
On va tout de suite arrêter de faire ça, et lint au fur et à mesure qu'on code, d'accord ? ^^
Le linter est pas ton ennemi, il est là pour t'aider à mieux coder. L'ignorer, c'est juste se le prendre encore plus violemment à la fin.

Là tu peux retirer ces deux lignes et lancer le linter pour voir ce que t'as à corriger avec `make lint`.
Normalement ça se lance avec `bundle exec rubocop`, mais là faut le faire dans docker, donc on utilise le makefile pour éviter d'avoir à écrire une super longue commande docker à chaque fois. Cette commande est décrite dans le Makefile ici : https://github.com/etalab/data_pass/blob/main/Makefile/#L20-L21

Pour t'éviter d'y passer des heures, rubocop peut auto-corriger une grande partie des choses, avec l'option `-A` pour "Autocorrect".

Tu as donc juste à ajouter le `-A` dans le Makefile, ligne 21, et lancer `make lint`, et ça va autocorriger 279/287 problèmes, et t'en auras plus que 8 à régler à la main :)

![image](https://github.com/user-attachments/assets/6094b522-7a36-4c6a-9180-4d93b2ee8c17)

(Et oublie pas de retirer le `-A` après)

2024-07-18 15:54 UTC, JeSuisUnCaillou commented on .rubocop.yml
> +    - "spec/services/hubee_api_client_spec.rb"
D'ailleurs, c'est quelque chose que tu aurais pu voir tout de suite si tu étais passée sur ton diff dans github comme je te l'ai conseillé ;)

2024-07-18 16:58 UTC, Isalafont commented on .rubocop.yml
> +    - "spec/services/hubee_api_client_spec.rb"
Tu es sur que ce n'est pas un probleme de config avec docker? J'ai run rubocop avant de push et je n'avais aucune offense, d'ailleurs la CI n'a détecté aucune offence rubocop non plus. 🤔

2024-07-18 19:23 UTC, Isalafont commented on .rubocop.yml
> +    - "spec/services/hubee_api_client_spec.rb"
Après je suis preneuse d'une meilleure solution pour résuidre 
`spec/bridges/hubee_cert_dc_bridge_spec.rb:1:1: C: RSpec/SpecFilePathFormat: Spec path should end with hub_ee_cert_dc_bridge*_spec.rb.` ainsi que 
`spec/services/hubee_api_client_spec.rb:1:1: C: RSpec/SpecFilePathFormat: Spec path should end with hub_eeapi_client*_spec.rb.
RSpec.describe HubEEAPIClient do`
(les 2 raisons pour laquelle j'ai rajouté ces 2 fichiers dans la config rubocop)

2024-07-23 07:17 UTC, JeSuisUnCaillou requested changes
C'est pas mal déjà, bravo :clap: 

En plus de mes comms, voici des conseils supplémentaires :

- Pour tous les payloads que tu mock dans tes tests, tu pourrais faire des factories pour alléger le fichier de spec. Je te montre un exemple de payload qu'on a mis dans une factory sur FQF : https://github.com/etalab/formulaire-qf/blob/main/spec/factories/quotient_familial_payload.rb

- Et les mocks d'api eux-même aussi on pourrait les déplacer dans un fichier à part, comme ça : https://github.com/etalab/formulaire-qf/blob/main/spec/support/provider_stubs/api_particulier.rb

Ca rendrait le tout plus clair et plus réutilisable

2024-07-23 07:17 UTC, JeSuisUnCaillou commented on spec/organizers/approve_authorization_request_spec.rb
> +    let(:user) { create(:user, :instructor, authorization_request_types: %w[api_particulier]) }
Pourquoi on change ça ?
Si le test ne fonctionne plus avec `hubee_cert_dc`, il y a peut-être une bonne raison à investiguer, non ?

2024-07-23 07:17 UTC, JeSuisUnCaillou commented on spec/services/hubee_api_client_spec.rb
> +      it 'calls the stubbed request' do
`it 'gets the existing organization'`

2024-07-23 07:17 UTC, JeSuisUnCaillou commented on spec/services/hubee_api_client_spec.rb
> +    context 'when organization already exist' do
`'when organization already exists in hubee'`

2024-07-23 07:17 UTC, JeSuisUnCaillou commented on spec/services/hubee_api_client_spec.rb
> +    context 'when organization does not exist' do
`'when organization doesn't exist in hubee'`

2024-07-23 07:17 UTC, JeSuisUnCaillou commented on spec/services/hubee_api_client_spec.rb
> +    context 'when organization does not exist' do
`'when organization does not exist in hubee'`

2024-07-23 07:17 UTC, JeSuisUnCaillou commented on spec/services/hubee_api_client_spec.rb
> +      it 'calls the stubbed request' do
`it 'creates the organization'`

2024-07-23 07:17 UTC, JeSuisUnCaillou commented on spec/services/hubee_api_client_spec.rb
> +      context 'when it is a conflict' do
`'when the organization already exists'`

2024-07-23 07:19 UTC, JeSuisUnCaillou commented on .rubocop.yml
> +    - "spec/services/hubee_api_client_spec.rb"
> Après je suis preneuse d'une meilleure solution pour résoudre
> `spec/bridges/hubee_cert_dc_bridge_spec.rb:1:1: C: RSpec/SpecFilePathFormat: Spec path should end with hub_ee_cert_dc_bridge*_spec.rb.` ainsi que
> `spec/services/hubee_api_client_spec.rb:1:1: C: RSpec/SpecFilePathFormat: Spec path should end with hub_eeapi_client*_spec.rb. RSpec.describe HubEEAPIClient do`
> (les 2 raisons pour laquelle j'ai rajouté ces 2 fichiers dans la config rubocop)

Là j'avoue je sais pas pourquoi il propose ces noms de fichiers là. On regarde ensemble cet aprem si tu veux.

2024-07-23 07:39 UTC, skelz0r commented on .rubocop.yml
> +    - "spec/services/hubee_api_client_spec.rb"
Vis-à-vis du dernier commentaire, si tu renames `HubEE` en `Hubee` je pense que ça plantera en prod à cause de l'inflection. Pour moi c'est un bug de rubocop qui n'a pas bien analysé le fichier parce qu'il ne râle pas sur le fichier normal (et si on rename je pense que ça va râler).

Ici je pense qu'il faut utiliser https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#customtransform-rubocoprubocop-rspecrspec-default pour spécifier comment transformer

2024-07-23 07:44 UTC, skelz0r commented on app/bridges/hubee_cert_dc_bridge.rb
> +    code_commune = authorization_request.organization.code_commune
Ce n'est pas validé ailleurs, mais c'est peu probable. Dans tous les cas ça plantera dans le bridge, ce qui est très bien. Si ça arrive, on avisera imo.

2024-07-23 07:51 UTC, skelz0r commented on spec/organizers/approve_authorization_request_spec.rb
> +    let(:user) { create(:user, :instructor, authorization_request_types: %w[api_particulier]) }
Il est vrai que le message de commit n'est pas assez clair f37669f6132c3c0ffe0f60ece822191335bb7925 (il manque l'explication).

Je pense qu'ici que le bridge est appelé et que du coup ça plante car rien n'est mocké.

Tant que ça ne sera pas en asynchrone ça sera un poil relou ici, parce que le fix le plus global que je vois est de coller un `type: :bridge` sur tous les tests de bridge, et mock en `before` de chaque test les bridge SAUF sur les `type: :bridge`.

2024-07-23 07:55 UTC, skelz0r commented
> C'est pas mal déjà, bravo 👏
> 
> En plus de mes comms, voici des conseils supplémentaires :
> 
> * Pour tous les payloads que tu mock dans tes tests, tu pourrais faire des factories pour alléger le fichier de spec. Je te montre un exemple de payload qu'on a mis dans une factory sur FQF : https://github.com/etalab/formulaire-qf/blob/main/spec/factories/quotient_familial_payload.rb
> * Et les mocks d'api eux-même aussi on pourrait les déplacer dans un fichier à part, comme ça : https://github.com/etalab/formulaire-qf/blob/main/spec/support/provider_stubs/api_particulier.rb
> 
> Ca rendrait le tout plus clair et plus réutilisable

Pour des exemples dans le code de DataPass

* Des exemples de payloads dans des factories: https://github.com/etalab/data_pass/blob/develop/spec/factories/mon_compte_pro_payloads.rb 
* Des mocks dans des fichiers à part : https://github.com/etalab/data_pass/blob/develop/spec/support/insee_sirene_api_mocks.rb (je pense d'ailleurs que le code de FQF s'inspire de celui de DP v2)

2024-07-23 08:44 UTC, JeSuisUnCaillou commented on .rubocop.yml
> +    - "spec/services/hubee_api_client_spec.rb"
On n'arrive pas à faire marcher ce custom transform, rien à faire il le prend pas en compte :thinking: 

```
RSpec/SpecFilePathFormat:
  CustomTransform: 
    HubEE: hubee
    RuboCop: rubocop
    RSpec: rspec
```

On a aussi essayé https://github.com/aeroastro/rubocop-inflector sans succès.

Une idée de comment ça se configure ?

2024-07-23 08:54 UTC, Isalafont commented on .rubocop.yml
> +    - "spec/services/hubee_api_client_spec.rb"
J'ai testé le CustomTransform (et même en rajoutant la gem rubocop-inflector) mais rien n'y fait, enfin si ça fonctionne mais ça lève d'autres errors  type: `An error occurred while RSpec/SpecFilePathFormat cop was inspecting /Users/isalafont/code/BetaGouv/Etalab/data_pass/spec/models/message_spec.rb.`

2024-07-23 08:56 UTC, skelz0r commented on .rubocop.yml
> +    - "spec/services/hubee_api_client_spec.rb"
Tain le relou quoi..

tbh limite je désactiverai globalement ce cop qui ne sert pas à grand chose avec des IDEs (qui vont mettre les fichiers ont bons endroits)

2024-07-23 08:58 UTC, skelz0r commented on .rubocop.yml
> +    - "spec/services/hubee_api_client_spec.rb"
(si on y réfléchit, on parle d'un fichier de test qui potentiellement est mal nommé, c'est clairement peu important pour la qualité du code globale)

2024-07-23 15:09 UTC, JeSuisUnCaillou commented on spec/support/hubee_cert_dc_bridge_mocks.rb
> +  end
C'est la même chose que `HubEEAPIClientMocks#organization_payload` non ?

2024-07-23 15:12 UTC, JeSuisUnCaillou reviewed
Allez je m'occupe de faire les factories, comme ça personne ne râlera :)

2024-07-23 15:12 UTC, JeSuisUnCaillou commented on spec/support/hubee_cert_dc_bridge_mocks.rb
> +  end
C'est la même chose que `HubEEAPIClientMocks#organization_payload` et `HubEEAPIClientMocks#subscription_body` là. On se répète.

(A mon avis, ça devrait être dans une factory hehe)

2024-07-23 15:12 UTC, JeSuisUnCaillou commented on spec/support/hubee_api_client_mocks.rb
> +    }
Toutes ces response errors pourraient être plus DRY dans une factory ;)

2024-07-23 15:17 UTC, JeSuisUnCaillou commented on app/bridges/hubee_cert_dc_bridge.rb
> +    create_and_store_subscription(authorization_request, hubee_organization, process_code)
pas besoin de mettre le process_code en argument ici, la méthode `create_and_store_subscription` y a accès

2024-07-23 15:24 UTC, Isalafont commented
> Allez je m'occupe de faire les factories, comme ça personne ne râlera :)

J'avoue que je suis curieuse de voir comment tu fais les factories pour les `response` !

2024-07-23 17:48 UTC, JeSuisUnCaillou commented
> > Allez je m'occupe de faire les factories, comme ça personne ne râlera :)
> 
> J'avoue que je suis curieuse de voir comment tu fais les factories pour les `response` !

-> https://github.com/etalab/data_pass/pull/299

2024-07-24 11:07 UTC, skelz0r commented on .rubocop.yml
> +RSpec/SpecFilePathFormat:
Remarque: préciser dans les messages de commit les raisons c'est pas mal ça donne de l'historique.

2024-07-24 11:47 UTC, skelz0r reviewed
Il y a un peu de refactor dans le code effectif à faire mais rien de bien méchant.

Par contre le test du bridge est vraiment peu compréhensible, le setup devrait être plus clair, et je pense que c'est ici que potentiellement changer les factories pour faire un truc plus simple est bénéfique. Là on fait des assumptions sur des ids, emails des factories, ce n'est pas explicite dans le test, il faut que ça le soit.

Un autre point: il vaut mieux éviter de manipuler l'attribut `data` de authorization_request et directement manipuler les accessors crées, pour éviter d'avoir du nil et de manipuler des attributs qui n'existe pas.

Le seul truc bloquant pour moi in fine est la remarque ci-dessus avec l'attribut `data`, le reste peut se refacto en scout commit.

(PS: vu que c'est ma PR je ne peut pas approve/request changes)

2024-07-24 11:47 UTC, skelz0r commented on app/bridges/hubee_cert_dc_bridge.rb
> +    code_commune = authorization_request.organization.code_commune
```suggestion
    organization = authorization_request.organization
    siret = authorization_request.organization.siret
    code_commune = organization.code_commune
```

2024-07-24 11:47 UTC, skelz0r commented on app/bridges/hubee_cert_dc_bridge.rb
> +    code_commune = authorization_request.organization.code_commune
D'ailleurs on peut aussi faire ceci:

```ruby
def organization
  authorization_request.organization
end
```

et manipuler directement `organization`

2024-07-24 11:47 UTC, skelz0r commented on app/bridges/hubee_cert_dc_bridge.rb
> +      phoneNumber: authorization_request.data['administrateur_metier_phone_number'].gsub(/[ .-]/, ''),
```suggestion
      email: authorization_request.administrateur_metier_email,
      phoneNumber: authorization_request.administrateur_metier_phone_number.gsub(/[ .-]/, ''),
```

2024-07-24 11:47 UTC, skelz0r commented on app/bridges/hubee_cert_dc_bridge.rb
> +      datapassId: authorization_request[:id],
```suggestion
      datapassId: authorization_request.id,
```

2024-07-24 11:47 UTC, skelz0r commented on app/bridges/hubee_cert_dc_bridge.rb
> +  def subscription_body(authorization_request, hubee_organization, process_code)
Ici on pourrait directement passer `organization` et non `hubee_organization`.

2024-07-24 11:47 UTC, skelz0r commented on app/bridges/hubee_cert_dc_bridge.rb
> +    authorization_request.data['scopes'].presence || 'CERTDC'
ce code est faux à plusieurs égards:

1. `scopes` peut être un tableau ;
2. on veut forcément envoyer `CERTDC`
3. il n'y a pas de clé `scopes`

```suggestion
    'CERTDC'
```

Du coup ça peut même se simplifier directement dans le code plus haut.

2024-07-24 11:47 UTC, skelz0r commented on app/services/hubee_api_client.rb
> +      req.headers['tag'] = 'Portail HubEE'
imo ça ne sert pas ça tu peux le flip

2024-07-24 11:47 UTC, skelz0r commented on app/services/hubee_api_client.rb
> +      req.headers['Authorization'] = "Bearer #{access_token}"
Il n'y a pas moyen de déporter cette ligne dans la faraday connexion ? Parce que ce n'est pas vraiment dry

2024-07-24 11:47 UTC, skelz0r commented on app/services/hubee_api_client.rb
> +    response.body['access_token']
```suggestion
    return @access_token if @access_token.present?
    
    response = faraday_connection.post do |req|
      req.url hubee_auth_url
      req.headers['Authorization'] = "Basic #{encoded_client_id_and_secret}"
      req.headers['Content-Type'] = 'application/x-www-form-urlencoded'
      req.headers['tag'] = 'Portail HubEE'
      req.body = URI.encode_www_form({ grant_type: 'client_credentials', scope: 'ADMIN' })
    end

    @access_token = response.body['access_token']
```

Ça évite de doubler les appels et de récupérer uniquement un jeton.
L'alternative est de faire comme pour le client INSEE.

2024-07-24 11:47 UTC, skelz0r commented on spec/bridges/hubee_cert_dc_bridge_spec.rb
> +  let(:subscription_response) { build(:hubee_subscription_response_payload, :cert_dc) }
Ce setup me parait très compliqué: aucune valeur n'est vraiment utilisée ici, ou alors c'est caché et donc compliqué à comprendre. Je vais proposer quelque chose :

```suggestion
  let(:authorization_request) { create(:authorization_request, :hubee_cert_dc, organization:) }

  let(:organization) { create(:organization, :with_insee_data) } # je ne suis pas sûr que ce trait existe mais ça peut se faire du coup

  let(:organization_payload) { build(:hubee_organization_payload, organization: ) }
  let(:subscription_response) { build(:hubee_subscription_response_payload, :cert_dc, authorization_request:) }
```

Et ici on modifie les factories hubee. Exemple avec la première:

```ruby
factory :hubee_organization_payload do
  transient do
    organization { nil }
  end

  after(:build) do |hubee_organization_payload, evaluator|
    if evaluator.organization.present?
      hubee_organization_payload[:companyRegister] = evaluator.organization.siret
      hubee_organization_payload[:branchCode] = evaluator.organization.postal_code
    end
  end
end
```

2024-07-24 11:47 UTC, skelz0r commented on spec/bridges/hubee_cert_dc_bridge_spec.rb
> +  describe '#perform' do
Je trouve ça très étrange de tester les méthodes privées. Je propose de réorganiser de cette manière les blocks pour qu'on comprenne mieux ce que ce `perform` fait:

```ruby
describe '#perform' do
  it 'retrieves the hubee organization with authorization request organization attributes'
  it 'creates a subscription with valid process code for authorization request organization'
  it 'stores the external subscription id within authorization request'

  context 'when organization exists on hubee' do
    it 'does not create organization on hubee'
  end

  context 'when organization does not exist on hubee' do
    it 'create organization on hubee with valid attributes'
  end
end
```

Je trouve ça plus clair que l'agencement ici. Fondamentalement c'est que du réarrangement

2024-07-24 11:47 UTC, skelz0r commented on spec/bridges/hubee_cert_dc_bridge_spec.rb
> +    it 'Creates and store subscription id' do
La 2e partie n'est pas testée

2024-07-24 11:47 UTC, skelz0r commented on spec/services/hubee_api_client_spec.rb
> +      end
Je vérifierai que le stub exact a été appelé.

```suggestion
      let!(:stubbed_hubee_get_organization_request) do
        stub_hubee_get_organization(siret, code_commune, organization_payload)
      end

      it 'calls the stubbed request' do
        get_organization

        expect(stubbed_hubee_get_organization_request).to have_been_requested
      end
```

2024-07-24 11:47 UTC, skelz0r commented on spec/services/hubee_api_client_spec.rb
> +      it 'calls the stubbed request' do
ce n'est pas ce qu'elle teste ici btw

2024-07-24 11:47 UTC, skelz0r commented on spec/services/hubee_api_client_spec.rb
> +      end
C'est valide pour tous en bas btw

2024-07-24 11:47 UTC, skelz0r commented on spec/services/hubee_api_client_spec.rb
> +      it 'creates the organization - Render 200' do
ce render 200 n'a pas lieu d'être car tu ne le testes pas.
d'ailleurs je suis quasiment sûr que c'est un 201 ici

cette remarque est valable pour tous les autres it plus bas

2024-07-24 13:29 UTC, Isalafont commented on app/bridges/hubee_cert_dc_bridge.rb
> +    authorization_request.data['scopes'].presence || 'CERTDC'
Je préférerai tout de même garder la méthode `process_code` en vu du bridge DILA qui lui aura bien un Array de scopes possible.

2024-07-24 13:50 UTC, Isalafont commented on spec/bridges/hubee_cert_dc_bridge_spec.rb
> +  let(:subscription_response) { build(:hubee_subscription_response_payload, :cert_dc) }
Je ne suis pas certaine de saisir 

> `let(:organization) { create(:organization, :with_insee_data) }` # je ne suis pas sûr que ce trait existe mais ça peut se faire du coup

Quand je lance organization dans mon debugger avec la ligne 
`let(:organization) { create(:organization, id: 3, siret: '21920023500014') }`, j'ai bien une payload_insee incluse.

2024-07-24 15:10 UTC, Isalafont commented on spec/bridges/hubee_cert_dc_bridge_spec.rb
> +  let(:organization) { create(:organization, siret: '21920023500014') }
@skelz0r Est ce que quelque chose comme ceci serait mieux niveau lisibilité ?

2024-07-24 15:11 UTC, Isalafont commented on spec/bridges/hubee_cert_dc_bridge_spec.rb
> +  let(:organization) { create(:organization, siret: '21920023500014') }
Je n'ai pas terminé car je dois encore apporter des modifications au fichier de support pour les mocks ainsi qu'au fichier spec de hubee_api_client.

2024-07-26 12:42 UTC, JeSuisUnCaillou commented on app/services/hubee_api_client.rb
> +      req.headers['tag'] = 'Portail HubEE'
Ah je me demandais justement, vu qu'on l'a que dans certains payloads je pensais que c'était une particularité bizarre de hubee :shrug:

2024-07-26 13:47 UTC, JeSuisUnCaillou commented on app/services/hubee_api_client.rb
> +      req.headers['Authorization'] = "Bearer #{access_token}"
done

2024-07-30 11:38 UTC, skelz0r commented on spec/services/hubee_api_client_spec.rb
> +      it 'calls the stubbed request' do
Oui exactement, c'est testé en dessous la get organization

2024-07-30 14:29 UTC, JeSuisUnCaillou commented on spec/services/hubee_api_client_spec.rb
> +      end
Ah j'ai pigé en relisant :+1:

2024-07-30 14:34 UTC, JeSuisUnCaillou commented on spec/bridges/hubee_cert_dc_bridge_spec.rb
> +    it 'Creates and store subscription id' do
c'est testé là : https://github.com/etalab/data_pass/blob/features/bridge-certdc/spec/bridges/hubee_cert_dc_bridge_spec.rb/#L80-L84

2024-07-30 14:42 UTC, JeSuisUnCaillou commented on spec/bridges/hubee_cert_dc_bridge_spec.rb
> +  describe '#perform' do
Bon je garde tel quel, la flemme

2024-07-31 14:46 UTC, merged