API Particulier - création formulaire cas d'usages sans éditeur
etalab/data_pass pull request #298
Opened 2024-07-23 16:10 UTC by DorineLam

2024-07-26 14:25 UTC, DorineLam commented
@skelz0r ça me paraît prêt à la revue, j'aurai bien aimé voir ce que ça peut donner en préprod et surtout pouvoir ainsi l'envoyer à Miryad.

2024-07-26 14:28 UTC, skelz0r commented
@DorineLam tu n'as pas réussi à le faire tourner en local ? si oui, tu peux déployer en sandbox la branche

2024-07-26 15:58 UTC, DorineLam commented
> @DorineLam tu n'as pas réussi à le faire tourner en local ? si oui, tu peux déployer en sandbox la branche

Ok, alors j'ai des conflits et le rebase s'annonce être compliqué, il me demande de passer en revue chaque commit. Est-ce que tu as un moyen plus simple pour rebase ?

2024-07-26 16:00 UTC, skelz0r commented
Je peux rebase

2024-07-26 16:10 UTC, skelz0r commented
Bon, en vrai c'est relou je pense que je vais juste squash tous tes commits et faire un seul merge conflict ça t'irait ?

2024-07-29 09:10 UTC, skelz0r commented
C'est OK @DorineLam

2024-07-30 08:24 UTC, DorineLam commented
@skelz0r j'ai essayé de déployer ma branche en sandbox mais ça ne semble pas fonctionner, peut-être à cause des tests ?
Aussi, je ne sais pas sur quelle URL regarder la sandbox.... Peux-tu me dire comment la retrouver ?

2024-07-30 14:01 UTC, JeSuisUnCaillou commented
@skelz0r J'ai essayé de regarder pour fix les tests (il manque la factory apparemment), mais j'ai pas réussi.

2024-07-31 12:06 UTC, skelz0r commented
@JeSuisUnCaillou cf dernier commit

2024-07-31 12:10 UTC, skelz0r commented
Et je viens d'ajouter une itération de la doc (où il manquait justement cet ajout de factory).
En vrai c'est un peu painful ce truc faudrait potentiellement simplifier.

2024-07-31 15:04 UTC, JeSuisUnCaillou commented
> @JeSuisUnCaillou cf dernier commit

Ah ben j'avais essayé ça, mais ça marchait pas :thinking:

2024-07-31 15:50 UTC, skelz0r commented
Faudrait ajouter des tests cucumber aussi histoire d'être sûr que ça fonctionne

2024-08-01 07:44 UTC, JeSuisUnCaillou commented
> Faudrait ajouter des tests cucumber aussi histoire d'être sûr que ça fonctionne

J'ai proposé à JB de se pencher dessus

2024-08-01 15:34 UTC, jbfeldis commented on config/authorization_request_forms/api_particulier.yml
> +    - name: scopes
En rédigeant des tests je vois que l'étape de scopes est en 2e position sur les formulaires ajoutés alors que c'est plutôt la dernière étape dans les autres formulaires, est-ce que c'est normal ?

2024-08-01 15:53 UTC, skelz0r commented on config/authorization_request_forms/api_particulier.yml
> +    - name: scopes
C'est en effet une bonne remarque. Ça me semblerait logique que à minima la partie legal soit avant les scopes.

2024-08-02 12:25 UTC, DorineLam commented on config/authorization_request_forms/api_particulier.yml
> +    - name: scopes
Oui c'est fait exprès. C'est pas possible de donner un cadre légal tant qu'on n'a même pas coché les données souhaitées, vu que le cadre juridique dépend de la donnée

2024-08-02 13:05 UTC, DorineLam commented
@skelz0r c'est validé, avec @Miryad3108, tu peux merger quand tu peux.

2024-08-02 15:04 UTC, skelz0r commented on config/authorization_request_forms/api_particulier.yml
> +    - name: scopes
> C'est pas possible de donner un cadre légal tant qu'on n'a même pas coché les données souhaitées

Je ne comprends pas, c'est la base légale qui détermine les données, pas l'inverse. Je ne comprends pas la logique du "je choisis mes données et je vais aller chercher un cadre légal qui va bien"

2024-08-02 15:06 UTC, skelz0r commented on config/authorization_request_forms/api_particulier.yml
> +    - name: scopes
Et au passage ce n'est pas cohérent avec la demande libre

2024-08-02 15:09 UTC, DorineLam commented on config/authorization_request_forms/api_particulier.yml
> +    - name: scopes
Oui j'entends, mais ça ne me semble pas fluide dans le parcours : On leur demande un cadre légal pour des données qu'ils n'ont pas encore vues. Comment peuvent ils savoir celles qu'ils vont demander ? Alors oui, les plus assidus auront bien regardé le site avant, mais est-ce que c'est la majorité des gens.

2024-08-02 22:17 UTC, Miryad3108 commented on config/authorization_request_forms/api_particulier.yml
> +    - name: scopes
Côté instruction le plus pertinent c'est que les données soient avant la délibération comme ça je sais exactement ce que je dois chercher 

Mais là l'objectif c'est de faciliter la saisie des formulaires aux FS. Dans cette optique, je rejoins plutôt @skelz0r et @jbfeldis dans le sens où la partie légale permet de te rappeler quelles sont les données que tu peux demander. ça rappelle aussi qu'un cadre légal est obligatoire avant d'accéder aux données ...  

Ils n'ont effectivement pas encore vu les données mais ils savent déjà pourquoi ils demandent accès à l'API.

2024-08-05 12:26 UTC, jbfeldis commented on config/authorization_request_forms/api_particulier.yml
> +    - name: legal
même remarque ici : 
je précise que je n'ai pas touché l'ordre ici parce que je ne savais pas quoi faire avec le static_block

2024-08-05 12:36 UTC, skelz0r commented on config/authorization_request_forms/api_particulier.yml
> +    - name: scopes
Ça aurait mérité 2 commits différents

2024-08-05 12:38 UTC, skelz0r commented on features/habilitations/api_particulier/soumission.feature
> +  Scénario: Je soumets une demande d'habilitation pour mes développeurs internes
c/c la logique d'API Entreprise ici imo. Je pense que tu peux refactoriser pas mal de choses avec des plan de scénarios.

2024-08-05 12:38 UTC, skelz0r requested changes
Pour refactoriser les plans de scénario.

2024-08-05 16:55 UTC, jbfeldis commented on config/authorization_request_forms/api_particulier.yml
> +    - name: scopes
done

2024-08-05 16:55 UTC, jbfeldis commented on config/authorization_request_forms/api_particulier.yml
> +    - name: legal
je l'ai finalement changé 🙃

2024-08-05 16:57 UTC, jbfeldis commented on features/habilitations/api_particulier/soumission.feature
> +      | Tarification cantine lycées                              | Précisez la nature et les références du texte vous autorisant à traiter les données | URL du texte relatif au traitement |
Est-ce qu'on n'utiliserait pas le même wording pour ne plus avoir ces 2 cas qui sont différents ?

2024-08-05 16:58 UTC, jbfeldis commented on features/habilitations/api_particulier/soumission.feature
> +  Scénario: Je soumets une demande d'habilitation pour mes développeurs internes
done... sauf pour un cas qui n'a pas d'étape de cadre juridique

2024-08-05 16:58 UTC, jbfeldis commented on config/authorization_request_forms/api_particulier.yml
> +    - name: legal
je l'ai finalement changé aussi 🙃

2024-08-06 16:13 UTC, jbfeldis commented on features/habilitations/api_particulier/soumission.feature
> +      | Tarification cantine lycées                              | Précisez la nature et les références du texte vous autorisant à traiter les données | URL du texte relatif au traitement |
Vu avec Dorine : c'est à challenger avec l'équipe donc pas pour le moment même si ça pourrait être bien de faire ces améliorations globales

2024-08-15 09:02 UTC, skelz0r requested changes
Je pense qu'on peut encore simplifier, cf mes coms.

2024-08-15 09:02 UTC, skelz0r commented on features/habilitations/api_particulier/soumission.feature
> +  Plan du scénario: Je soumets une demande d'habilitation pour mes développeurs internes
```suggestion
  Plan du scénario: Je soumets une demande d'habilitation pour un cas d'usage sans éditeur où je dois préciser le cadre légal et le lien vers la délibération
```

Et je déporterai `Tarification cantine lycées` dans un autre test, pour éviter de variabiliser `Cadre légal` et `Lien délibération`

2024-08-15 09:02 UTC, skelz0r commented on features/habilitations/api_particulier/soumission.feature
> +  Scénario: Je soumets une demande d'habilitation pour mes développeurs internes
```suggestion
  Scénario: Je soumets une demande d'habilitation pour le cas d'usage "Aides sociales des CCAS"
```

Y'en a qu'un, autant être précis.

2024-08-15 09:02 UTC, skelz0r commented on features/habilitations/api_particulier/soumission.feature
> +  Scénario: Je soumets une demande d'habilitation pour mes développeurs internes
```suggestion
  Scénario: Je soumets une demande d'habilitation pour le cas d'usage Gestion RH du secteur public
```

idem, autant être précis,

2024-08-15 11:57 UTC, skelz0r approved these changes

2024-08-15 11:57 UTC, merged