factorise block titles for single pages
etalab/data_pass pull request #305
Opened 2024-07-25 13:00 UTC by JeSuisUnCaillou

Closes https://linear.app/pole-api/issue/DAT-500/il-manque-des-titressous-titres-sur-les-single-pages

2024-07-25 14:57 UTC, skelz0r requested changes
Le fait d'inclure wicked dans le controller `AuthorizationRequests::BlocksController` et le `@no_stepper` sont pour moi à jarter, doit clairement y avoir plus simple pour exploiter le nom français.

De plus je vois que tu fais des tests sur des steps, pour moi on veut que ça plante. Le cas contraire c'est de la dette car ça introduit du bug silencieux (genre le `wicked_block_id` où tu prends soit le nom français soit le nom anglais avec la condition c'est pas ouf).

2024-07-25 14:57 UTC, skelz0r commented on app/views/authorization_request_forms/_form.html.erb
> +  <% if @authorization_request.form.multiple_steps? && !@authorization_request.finished? && !@no_stepper %>
Tu ne peux pas te baser sur wicked pour ça ? (genre faire `defined?(wizard_path)`)

2024-07-25 14:57 UTC, skelz0r commented on app/views/authorization_request_forms/shared/_block_titles.html.erb
> +
```suggestion
```

Je veux clairement que ce bloc plante si on ne passe pas le `block_name`

2024-07-25 14:57 UTC, skelz0r commented on app/controllers/authorization_requests/blocks_controller.rb
> +  include Wicked::Wizard::Translated
Y'a un souci là : on n'est clairement pas dans un wizard. Du coup tu ajoutes une machine de gestion d'étapes pour avoir 1 traduction que tu pourrais obtenir avec une méthode outil ici non ?

Surtout que in-fine tu passes le `block_name` donc vraiment là je ne comprends pas à quoi ça sert

2024-07-25 14:57 UTC, skelz0r commented on app/views/authorization_requests/shared/blocks/_summary_block.html.erb
> +      <% wicked_block_id = t('wicked').keys.include?(block_id) ? t("wicked.#{block_id}") : block_id %>
```suggestion
      <% wicked_block_id = t("wicked.#{block_id}") %>
```

on veut que ça plante si ça n'existe pas

2024-07-25 16:19 UTC, JeSuisUnCaillou commented on app/controllers/authorization_requests/blocks_controller.rb
> +  include Wicked::Wizard::Translated
j'avoue.

2024-07-25 16:20 UTC, JeSuisUnCaillou commented on app/views/authorization_request_forms/_form.html.erb
> +  <% if @authorization_request.form.multiple_steps? && !@authorization_request.finished? && !@no_stepper %>
bah j'ai pas wicked quand je suis dans un edit

2024-07-25 16:33 UTC, skelz0r commented
> Va vraiment falloir virer "API INFINOE" là si on veut que le code soit moins permissif T_T

Tu peux c'est du PoC de l'époque. Comme je te disais ce n'est pas utilisé donc c'est du code mort.
Après il faut garder en tête que cette étape sera très certainement existante par la suite, donc faudra le faire

2024-07-25 16:42 UTC, JeSuisUnCaillou commented
> Tu peux c'est du PoC de l'époque. Comme je te disais ce n'est pas utilisé donc c'est du code mort.
> Après il faut garder en tête que cette étape sera très certainement existante par la suite, donc faudra le faire

Il suffira de correctement le configurer à ce moment là, avec les traductions qui vont bien. Là c'est par qu'il manquait des traductions que je faisait des sauts périlleux.

2024-07-25 17:03 UTC, JeSuisUnCaillou commented
Erf je peux pas clean entièrement toute référénce à Infinoe, y'a des tests de bridges qui se basent dessus

2024-07-25 17:06 UTC, skelz0r commented
> Erf je peux pas clean entièrement toute référénce à Infinoe, y'a des tests de bridges qui se basent dessus

Flip les bridges, c'est du PoC

2024-07-25 17:18 UTC, JeSuisUnCaillou commented
En flippant juste la feature infinoe_production qui foirait, c'est green.
Je tente de retirer tout ce qui touche à Infinoe, mais je promet pas d'y arriver ^^.

2024-07-25 17:36 UTC, JeSuisUnCaillou commented
OMG it's green.

Tu peux checker le dernier commit voir si j'ai pas flip des tests utiles quand même.

2024-07-26 09:21 UTC, skelz0r commented on app/views/authorization_request_forms/_form.html.erb
> +  <% if @authorization_request.form.multiple_steps? && !@authorization_request.finished? && !@no_stepper %>
On n'a pas envie de mettre le stepper si on n'est pas dans un wizard. Au lieu d'utiliser une variable setup à la main, on peut vérifier que `wizard_path` est bien défini (uniquement quand on est dans un controller du wizard).

2024-07-26 09:23 UTC, skelz0r requested changes
Fix ce commentaire https://github.com/etalab/data_pass/pull/305/files#r1692765337 et c'est OK pour moi (le `@no_stepper` est inutile).

Est-ce que tout le flip de Infinoe est bien dans un unique commit ? Pour le référencer dans une issue pour plus tard.

2024-07-26 09:36 UTC, JeSuisUnCaillou commented
> Est-ce que tout le flip de Infinoe est bien dans un unique commit ? Pour le référencer dans une issue pour plus tard.

Y'en avait 2, mais maintenant oui.

2024-07-26 15:40 UTC, merged