Ux/dat 447/display info bann when prefilled data in step form
etalab/data_pass pull request #314
Opened 2024-07-30 15:29 UTC by Isalafont

WIP

![screencapture-localhost-3000-formulaires-api-particulier-arpege-concerto-demande-commencer-2024-07-30-17_29_00](https://github.com/user-attachments/assets/8917d388-89f2-4a42-9412-3a18b70022cd)

2024-08-19 17:07 UTC, skelz0r requested changes
Il manque en effet, à mon sens, 2 tests cucumber:

1. Sur un formulaire pré-rempli, voir l'alerte
2. Sur un formulaire non pré-rempli, ne pas voir d'alerte

Je pense que ça peut s'insérer dans un test existant, sinon il y a déjà toute la grammaire pour faire des scénarios.

2024-08-19 17:07 UTC, skelz0r commented on app/decorators/authorization_request_decorator.rb
> +
```suggestion
  def prefilled_data?(keys)
    (object.form.data.keys & keys.map(&:to_sym)).any?
  end

```

2024-08-19 17:07 UTC, skelz0r commented on app/views/authorization_request_forms/shared/_contacts.html.erb
> +<% if @authorization_request.prefilled_data?(%i[contact_technique_email contact_metier_email ]) %>
ça me parait faux ici, pourquoi ne pas utilisé directement `@authorization_request.contact_types` ? et pourquoi que les emails ?

2024-08-19 17:07 UTC, skelz0r commented on app/views/authorization_request_forms/shared/_legal.html.erb
> +<% if @authorization_request.prefilled_data?(%i[cadre_juridique_nature cadre_juridique_url  cadre_juridique_text]) %>
d'où sort `cadre_juridique_text` ?

2024-08-19 17:07 UTC, skelz0r commented on app/views/authorization_request_forms/shared/_personal_data.html.erb
> +<% if @authorization_request.prefilled_data?(%i[destinataire_donnees_caractere_personnel duree_conservation_donnees_caractere_personnel duree_conservation_donnees_caractere_personnel_justification])
je pense que la justification on peut l'omettre.

2024-08-19 17:07 UTC, skelz0r commented on config/locales/authorization_request_forms.fr.yml
> +        description: "Vous avez choisi le cas d'usage %{name}, nous avons pré-rempli les informations correspondantes."
`name` ici est le nom du formulaire et non le cas d'usage, c'est un peu brainfuck

2024-08-20 07:25 UTC, Isalafont commented on app/views/authorization_request_forms/shared/_contacts.html.erb
> +<% if @authorization_request.prefilled_data?(%i[contact_technique_email contact_metier_email ]) %>
Dans le cas de `<% if @authorization_request.contact_types %>` Cela m'affiche la banner même s'il n'y a pas de contact pré-rempli. => voir `formulaires/api-particulier-arpege-concerto`

Dans le cas ou je mets `<% if @authorization_request.contact_types.present? %>` cela fonctionnerait, mais est ce que l'on a envie d'avoir une méthode d'affichage différente des autres blocks ? A savoir ne pas utiliser `prefilled_data?`

Dans le cas `<% if @authorization_request.prefilled_data?(%i[contact_types]) %>`, Cela n'affiche pas la banner si un contact est pré-rempli => voir editeur abelium `formulaires/api-particulier-abelium/demande/31/etapes/contacts`

J'ai sélectionné les emails car ce sont les champs toujours rempli dans le cas des formulaires pré-remplis.

2024-08-20 07:28 UTC, Isalafont commented on app/views/authorization_request_forms/shared/_legal.html.erb
> +<% if @authorization_request.prefilled_data?(%i[cadre_juridique_nature cadre_juridique_url  cadre_juridique_text]) %>
Une erreur, je retire

2024-08-20 07:37 UTC, skelz0r commented on app/views/authorization_request_forms/shared/_contacts.html.erb
> +<% if @authorization_request.prefilled_data?(%i[contact_technique_email contact_metier_email ]) %>
Il faut vérifier dynamiquement en fonction des types de contacts si il existe une donnée pré-remplis pour ces contacts. Les 3 options que tu proposes ne font pas ces vérifications.

Faut faire un truc de ce genre (si on ne vérifie que les emails, ce qui après réflexion est suffisant je pense):

```ruby
contact_email_fields = @authorization_request.contact_types.map { |contact_type| "#{contact_type}_email".to_sym }
@authorization_request.prefilled_data?(contact_email_fields)
```

2024-08-20 07:40 UTC, skelz0r commented on config/locales/authorization_request_forms.fr.yml
> +        description: "Vous avez choisi le cas d'usage %{name}, nous avons pré-rempli les informations correspondantes."
`name` correspondant au nom du formulaire, je mettrai `Vous avez choisi le formulaire %{name}`, on pourrait potentiellement afficher `name_with_editor` aussi.

> et par exemple dans le cas d'usage `portail_famille_tarification`, cela ne correspond à rien pour l'utilisateur.

comment ça ?

Si il y a des noms de formulaires qui ne sont pas clair, il faut retravailler le contenu. Utiliser le nom du formulaire en précisant "Cas d'usage" ce n'est viable. 
On peut aussi itérer et mettre des vrais noms de cas d'usages, mais ici se pose la question de : est-ce que tous les formulaires seront liés à des cas d'usages ?

2024-08-20 07:44 UTC, Isalafont commented on config/locales/authorization_request_forms.fr.yml
> +        description: "Vous avez choisi le cas d'usage %{name}, nous avons pré-rempli les informations correspondantes."
Le nom de cas d'usage n'est pas viable et ne concerne que API Particulier. 
Les autres API ayant des données pré-remplis n'ont pas forcément de cas d'usage. API Entreprise par exemple. Quid des API tels que Service National ou Le Taxi par exemple (pour ne citer qu'eux?)

2024-08-20 07:48 UTC, skelz0r commented on config/locales/authorization_request_forms.fr.yml
> +        description: "Vous avez choisi le cas d'usage %{name}, nous avons pré-rempli les informations correspondantes."
> Le nom de cas d'usage n'est pas viable et ne concerne que API Particulier.

Je ne suis pas sûr de bien comprendre cette phrase. Il n'y a actuellement pas de nom de cas d'usage (c'est un simple ID technique).

> Les autres API ayant des données pré-remplis n'ont pas forcément de cas d'usage. API Entreprise par exemple.

Ce sont des oublis aussi

> Quid des API tels que Service National ou Le Taxi par exemple (pour ne citer qu'eux?)

D'où ma question finale. C'est une question purement métier ici, je pense que la réponse est "non", et dans ce cas là ça n'a pas de sens d'écrire "Vous avez choisi le cas d'usage", et je maintiens (à court terme) d'utiliser "Vous avez choisi le formulaire"

2024-08-20 08:51 UTC, skelz0r approved these changes

2024-08-20 09:00 UTC, JeSuisUnCaillou reviewed
Je vais pas repasser sur tout vu que loic a déjà review, juste quelques remarques sur le css.

- Utiliser les classes de flex du dsfr (`fr-grid-row` et compagnie)
- Scoper les classes css pour ne pas impacter de futures possibles `fr-notice`

2024-08-20 09:02 UTC, JeSuisUnCaillou commented on app/assets/stylesheets/components/prefilled_banner.css
> +    align-items: center;
fr-grid-row
fr-grid-row--center
fr-grid-row--middle

2024-08-20 09:25 UTC, JeSuisUnCaillou commented on app/assets/stylesheets/components/prefilled_banner.css
> +    align-items: center;
D'ailleurs selon moi, on devrait aussi utiliser au max les classes de marges du dsfr au lieu de les faire custom dans le css. Nice to have.

2024-08-20 09:47 UTC, Isalafont commented on app/assets/stylesheets/components/prefilled_banner.css
> +    align-items: center;
De mon souvenir, j'ai tenté en premier avec les classes du DSFR, sans succès. 
J'ai passé plus de temps a tenté de reproduire le design avec les classes du DSFR qu'a la personnalisé à la main...

2024-08-20 09:50 UTC, JeSuisUnCaillou commented on app/assets/stylesheets/components/prefilled_banner.css
> +    align-items: center;
Si je me souviens bien :
`fr-grid-row` = `display: flex`
`fr-grid-row--center` = `justify-content: center`
`fr-grid-row--middle` = `align-items: center`

2024-08-20 10:25 UTC, Isalafont commented
PR rebase avec la dernière version de develop

2024-08-20 10:47 UTC, skelz0r commented on app/assets/stylesheets/components/prefilled_banner.css
> +}
J'aurais namespace avec `prefilled_banner` justement.

```suggestion
.prefilled-banner .fr-notice__title {
    display: block;
    color: var(--text-default-grey);
    font-size: 1.375rem;
    font-weight: 700;
    line-height: 1.74rem;
}

.prefilled-banner .fr-notice__desc {
    color: var(--text-default-grey);
}
```

Et dans le html:

```html
<div class="fr-notice fr-notice--info prefilled-banner fr-my-3w fr-p-0">
```

là le `_custom` est (paradoxalement) trop générique.

2024-08-20 11:54 UTC, JeSuisUnCaillou commented on app/assets/stylesheets/components/prefilled_banner.css
> +}
D'accord avec loic, quand je parlais de scoper les noms, je pensais à ça : ajouter une classe.

2024-08-20 11:56 UTC, JeSuisUnCaillou requested changes
cf le commentaire de loic plus haut

2024-08-20 13:11 UTC, JeSuisUnCaillou requested changes
Deux virgules en moins et c'est bon. Je valide pour que tu puisses merge une fois que ce sera fait, mais faut bien changer ça :point_down:

2024-08-20 13:11 UTC, JeSuisUnCaillou commented on app/assets/stylesheets/components/prefilled_banner.css
> +}
Si tu met une virgule, ça veut dire que ton css s'applique aux deux classes. C'est juste un espace qu'il faudrait, entre `.prefilled-banner .fr-notice__title` pour que ça veuille dire "les notice-title à l'intérieur de prefilled-banner

2024-08-20 13:12 UTC, JeSuisUnCaillou approved these changes

2024-08-20 13:28 UTC, merged