move unicity conditions from new? to create?
etalab/data_pass pull request #350
Opened 2024-08-12 11:49 UTC by JeSuisUnCaillou

Closes https://linear.app/pole-api/issue/DAT-466/fix-le-bouton-remplir-une-demande-napparait-plus-pour-hubee-sur-la

2024-08-12 14:19 UTC, JeSuisUnCaillou commented
J'ai utilisé le composant de callout, et j'ai customisé le texte en fonction de si l'habilitation est déjà validée ou pas.

![image](https://github.com/user-attachments/assets/4fa1ce38-d1b9-4d3c-92ee-c2f3c6165989)

![image](https://github.com/user-attachments/assets/52ab00fe-b8a4-4d95-9e99-46f4c2c70569)

2024-08-12 14:31 UTC, JeSuisUnCaillou commented
@skelz0r j'devrais ptet rajouter une contrainte d'unicité sur `organization + hubee_cert_dc` dans le modèle ? Dans la db ?

2024-08-12 14:42 UTC, skelz0r requested changes
Pour moi il faut alléger le décorateur qui a fait de la logique de vue, ce n'est pas son rôle.

Je pense que ce que je propose est plus logique.

2024-08-12 14:42 UTC, skelz0r commented on app/decorators/authorization_request_form_decorator.rb
> +  end
Pour moi ce n'est pas le rôle d'un décorateur de s'occuper de quasiment toute la construction de la vue. Pourquoi ne pas déporter ce code qui est, in-fine, quasiment que de la vue dans ... la vue ?

2024-08-12 14:42 UTC, skelz0r commented on app/decorators/authorization_request_form_decorator.rb
> +  def unicity_callout_key(_organization, request)
Pourquoi passer `organization` si on ne s'en sert pas ?

2024-08-12 14:42 UTC, skelz0r commented on app/views/authorization_request_forms/new.html.erb
> +    </div>
Related au commentaire du decorateur en haut, pour moi faut utiliser une view ici:

```suggestion
    <% if @authorization_request_form.authorizations_for(current_organization).any? %>
      <%= render 'callout', locals: { kind: 'red', text: t('.authorization.already_exists', cta_link: authorization_path(...)) } %>
    <% else %>
      <%= render 'callout', locals: { kind: 'red', text: t('.authorization_request.already_exists', cta_link: authorization_request_path(...)) } %>
    <% end %>
```

Le `authorizations_for` dedans y'a basiquement ça:

```ruby
organization.authorization_requests.where(authorization_request_type: self.authorization_request_class, status: 'validated')
```

Et ça oui ça va dans le decorateur (qui décore/augmente un modèle pour de la vue, ce qui est exactement son rôle).

2024-08-12 14:43 UTC, skelz0r commented
> @skelz0r j'devrais ptet aussi rajouter une contrainte d'unicité sur `organization + hubee_cert_dc` dans le modèle ? Dans la db ?

Oui bonne idée

2024-08-12 14:53 UTC, JeSuisUnCaillou commented on app/decorators/authorization_request_form_decorator.rb
> +  def unicity_callout_key(_organization, request)
reliquat de code modifié, je remove

2024-08-12 14:54 UTC, JeSuisUnCaillou commented on app/decorators/authorization_request_form_decorator.rb
> +  end
Par ce que ça fait beaucoup de logique dans la vue, pour une vue. J'me voyais pas écrire tout ça dans des `<%= truc %>`

2024-08-12 14:55 UTC, JeSuisUnCaillou commented
> > @skelz0r j'devrais ptet aussi rajouter une contrainte d'unicité sur `organization + hubee_cert_dc` dans le modèle ? Dans la db ?
> 
> Oui bonne idée

Y'a deux questions, et tu répond "oui". Oui aux deux ?

2024-08-12 14:56 UTC, skelz0r commented on app/views/authorization_request_forms/new.html.erb
> +    </div>
Je comprends ton commentaire plus haut, mais je pense que ce que je propose est plus lisible que ce que tu proposes, et on déporte le gros de la logique dans une méthode qui est dans le décorateur.

2024-08-12 14:57 UTC, skelz0r commented
> > > @skelz0r j'devrais ptet aussi rajouter une contrainte d'unicité sur `organization + hubee_cert_dc` dans le modèle ? Dans la db ?
> > 
> > 
> > Oui bonne idée
> 
> Y'a deux questions, et tu répond "oui". Oui aux deux ?

Oui aux deux, mais plus à la 2e (parce que la 1e existe déjà.)

2024-08-13 07:57 UTC, JeSuisUnCaillou commented on app/views/authorization_request_forms/new.html.erb
> +    </div>
Ah mais je pensais que tu disais que `authorizations_for` existait déjà, et je le trouvais pas x)

2024-08-13 07:58 UTC, skelz0r commented on app/views/authorization_request_forms/new.html.erb
> +    </div>
Non, c'est une propale

2024-08-13 08:12 UTC, JeSuisUnCaillou commented on app/views/authorization_request_forms/new.html.erb
> +    </div>
le truc c'est que j'ai besoin d'avoir la request pour pouvoir crafter le path du lien, donc je vais pas foutre le `any?` dans cette méthode, je vais garder mon find_by. Mais ouais je la déplace dans le form.

2024-08-13 08:14 UTC, skelz0r commented on app/views/authorization_request_forms/new.html.erb
> +    </div>
Je n'ai pas mis le `any?` dans la méthode tu remarqueras ;)

2024-08-13 08:24 UTC, JeSuisUnCaillou commented
En vrai c'est vachement plus simple comme ça avec la partial de unicity callout :+1:

2024-08-13 09:01 UTC, skelz0r reviewed
Je te laisse le choix de gérer ou non mes 2 commentaires, en l'état ça me va (même si je pense que je vais bugguer à chaque fois sur le `active_authorization_request_for` car ça n'a pas de sens métier, sauf pour HubEE et que ça n'apparait pas vraiment dans le code (mais au moins dans l'historique))

2024-08-13 09:54 UTC, JeSuisUnCaillou commented on app/models/authorization_request_form.rb
> +  def active_authorization_request_for(organization)
ça me va

2024-08-13 09:58 UTC, skelz0r commented
T'as un conflit avec le db schema btw

2024-08-13 10:00 UTC, skelz0r approved these changes

2024-08-13 11:43 UTC, merged