Ux/dat 409/new design authorization request card
etalab/data_pass pull request #373
Opened 2024-08-21 10:30 UTC by Isalafont

![Capture d’écran 2024-08-26 à 16 44 14](https://github.com/user-attachments/assets/63ae167d-74a1-4221-b632-d79e08d6502c)

-----

![Capture d’écran 2024-08-26 à 16 44 48](https://github.com/user-attachments/assets/ecedf9b3-93e2-45e6-9860-f85f77e0e3ea)

-----
Full Page

![screencapture-localhost-3000-tableau-de-bord-organisation-2024-08-26-16_42_21 (1)](https://github.com/user-attachments/assets/c5d5c10e-bb86-4098-802e-48ee324aba9d)

--- 

Quand l'utilisateur est dans la section `Toutes celles de l'organisation`, le nom du demandeur de la demande (autre que celle du current user) s'affiche. 
![Capture d’écran 2024-08-26 à 17 27 48](https://github.com/user-attachments/assets/88eac0c3-2b73-4081-bcca-9db3d80d5ed9)

2024-08-22 16:04 UTC, JeSuisUnCaillou requested changes
Beau boulot déjà !

2024-08-22 16:04 UTC, JeSuisUnCaillou commented on app/views/dashboard/card/_authorization_request_card.html.erb
> +          N°<%= authorization_request.id %>
Au lieu de mettre le numéro de la demande, il faudrait plutôt mettre l'identifiant d'habilitation sous forme de date là, pour rester cohérent avec le show

![image](https://github.com/user-attachments/assets/a9eaf771-c459-4f15-ba60-d5a45aa6c7c0)

2024-08-22 16:04 UTC, JeSuisUnCaillou commented on app/views/dashboard/card/_authorization_request_card.html.erb
> +          N°<%= authorization_request.id %>
Ou les deux, si on veut.

2024-08-22 16:04 UTC, JeSuisUnCaillou commented on app/views/dashboard/card/_authorization_request_card_small.html.erb
> +          N°<%= authorization_request.id %>
Je mettrai "Demande N°65" ici, pour rester cohérent avec le show

2024-08-22 16:04 UTC, JeSuisUnCaillou commented on app/views/dashboard/card/_authorization_request_card_small.html.erb
> +          N°<%= authorization_request.id %>
On pourrait d'ailleurs faire une partial juste pour ce badge, vu qu'on le réutilise plusieurs fois

2024-08-22 16:04 UTC, JeSuisUnCaillou commented on config/locales/fr.yml
> +        current_user_mentions: Vous avez été référencé comme %{contact_types}
`contact_type` au singulier non ? Il peut y avoir plusieurs types ?

2024-08-26 09:17 UTC, Isalafont commented
@evaspae Pourras tu me valider l'ordre de présentation "habilitation" (Demandes à modifier, Demandes en cours d'instruction, demandes en brouillon, Mes habiliations)
J'ai trouvé cet ordre présent sur la page "Accueil" du Figma, mais trouvé un ordre de présentation différent dans une autre page du Figma 🫣

2024-08-26 12:52 UTC, JeSuisUnCaillou commented on app/views/dashboard/card/_authorization_request_card_small.html.erb
> +          N°<%= authorization_request.id %>
(Si ça rentre)

2024-08-26 18:25 UTC, jbfeldis reviewed
GG, c'est stylé !

J'ai laissé quelques commentaires plutôt axés sur le ruby dans erb, ça rejoint surtout les commentaires de Valentin sur l'utilisation plus poussée des decorators

2024-08-26 18:25 UTC, jbfeldis commented on app/views/dashboard/card/_authorization_request_card.html.erb
> +          <%= truncate(authorization_request.name, length: 50) %>
quitte à avoir un decorator je mettrais ça dedans pour avoir `.truncated_name` dans la vue

2024-08-26 18:25 UTC, jbfeldis commented on app/views/dashboard/card/_authorization_request_card.html.erb
> +          <% end %>
pareil ici, je mettrais ça dans le decorator, le `<p>` est le même partout donc la condition ne concerne "que" le contenu et les conditions sont toujours plus lisibles dans une petite méthode ruby :wink:

2024-08-26 18:25 UTC, jbfeldis commented on app/views/dashboard/card/_authorization_request_card.html.erb
> +        <% end %>
on peut aussi pousser ça dans le decorator pour se débarrasser des conditions dans les vues (ça vaut pour la plupart des conditions qui suivent dans ce partial)

je n'ai pas regardé les decorators dans le projet donc ce n'est ptet pas aligné avec le style du projet mais on pourrait éventuellement en discuter

(bon moi j'avoue que j'aime pas les conditions et encore moins dans les vues :older_man: :smile: )

2024-08-26 18:25 UTC, jbfeldis commented on app/views/dashboard/show.html.erb
> +    <%= render partial: 'authorization_requests_changes_requested', locals: { authorization_requests: @authorization_requests.changes_requested.without_reopening, kind: 'changes_requested' } %>
on ne pourrait pas utiliser la forme de render qui fonctionne avec une collection ? ça éviterait de répéter les conditions vu qu'on est dans le cas ou rendre une collection vide ça fait exactement ce qu'on veut

2024-08-27 07:46 UTC, JeSuisUnCaillou reviewed
@Isalafont Pour moi on est bons, je laisserait @jbfeldis valider après avoir échangé avec toi sur sa review.

2024-08-27 13:08 UTC, JeSuisUnCaillou commented
Moi j'ai déjà dit que ça m'allait.
Je vois qu'il reste des commentaires de @jbfeldis non resolus, vous en avez parlé à l'oral ?

2024-08-27 14:35 UTC, Isalafont commented
J'ai fait des commentaires mais ils sont restés en pending... ARGHHH

2024-08-27 14:36 UTC, Isalafont commented
@jbfeldis 
> on ne pourrait pas utiliser la forme de render qui fonctionne avec une collection ? ça éviterait de répéter les conditions vu qu'on est dans le cas ou rendre une collection vide ça fait exactement ce qu'on veut

J'ai tenté d'utiliser une collection mais j'ai l'impression que ça complexifie le code également au niveau du fichier app/views/dashboard/_authorization_requests.html.erb pour traiter la collection.
Les habilitations ne se classent plus dans leurs sections respectives.
Je pense que ça meriterait peut être de s'y plonger d'avantage dans un ticket de refacto ?

2024-08-27 14:41 UTC, Isalafont commented
@jbfeldis 

> on peut aussi pousser ça dans le decorator pour se débarrasser des conditions dans les vues (ça vaut pour la plupart des conditions qui suivent dans ce partial)

je n'ai pas regardé les decorators dans le projet donc ce n'est ptet pas aligné avec le style du projet mais on pourrait éventuellement en discuter

(bon moi j'avoue que j'aime pas les conditions et encore moins dans les vues 👴 😄 )

Jusqu'a présent dans le décorator, il y a surtout des methods helpers, je ne suis pas certaine que de déplacer une condition a une seule branche soit réellement un plus niveau lisibilité ?

Mais je suis d'accord qu'il y a peut être des questions à se poser quand à notre utilisation des decorators et ce que l'on doit y mettre ou pas ?

J'ai déplacé dans le decorator la condition précédente qui pour le coup améliore la lisibilité.

2024-08-28 08:31 UTC, jbfeldis commented on app/views/dashboard/card/_authorization_request_card.html.erb
> +        <% end %>
> Jusqu'a présent dans le décorator, il y a surtout des methods helpers, je ne suis pas certaine que de déplacer une condition a une seule branche soit réellement un plus niveau lisibilité ?
Mais je suis d'accord qu'il y a peut être des questions à se poser quand à notre utilisation des decorators et ce que l'on doit y mettre ou pas ?
J'ai déplacé dans le decorator la condition précédente qui pour le coup améliore la lisibilité.

Ouais, parlons en, c'est intéressant comme sujet !

2024-08-28 08:31 UTC, jbfeldis approved these changes

2024-08-28 08:57 UTC, merged

2024-08-28 08:57 UTC, JeSuisUnCaillou commented
let's go ! :D

2024-08-28 08:59 UTC, skelz0r commented
> Jusqu'a présent dans le décorator, il y a surtout des methods helpers, je ne suis pas certaine que de déplacer une condition a une seule branche soit réellement un plus niveau lisibilité ?
> 
> Mais je suis d'accord qu'il y a peut être des questions à se poser quand à notre utilisation des decorators et ce que l'on doit y mettre ou pas ?

Tout ce qui est utilisé uniquement dans la vue et intrinséquement lié au modèle ça part dans le decorateur pour moi. Ensuite je fais confiance à nos règles de lint pour nous alerter dès que ça devient trop gros.

2024-08-29 07:44 UTC, evaspae reviewed
C'est bon pour moi ! 👍