Améliore le design et l'UX de l'entrée du tunnel de création de demande
etalab/data_pass pull request #374
Opened 2024-08-21 16:01 UTC by jbfeldis

![FireShot Capture 015 - DataPass - 192 168 1 12](https://github.com/user-attachments/assets/e1740056-504e-40b4-9110-0175fd7bf049)

Cette PR reprend les éléments de design, ajoute un index pour les éditeurs en gardant les cas d'usage sur la même page.

C'est à revoir avec Eva la semaine prochaine pour des potentielles retouches.

2024-08-22 07:28 UTC, Isalafont reviewed
Je suis surprise de voir autant de texte dans la vue sans avoir été placé dans les locales. ^^
Est ce qu'on le laisse dans la vue ? 

Sinon top ! Je ne savais pas que l'on pouvait passer les couleurs du DSFR pour le texte directement dans les class, je vais réutiliser ce tips tient ! ^^

2024-08-22 07:28 UTC, Isalafont commented on app/controllers/authorization_requests_controller.rb
> +  before_action :find_authorization_definition, only: %i[new]
👍

2024-08-22 07:28 UTC, Isalafont commented on app/javascript/controllers/choose_authorization_request_form_controller.js
> +  static targets = [
Je suis étonnée que Rubocop n'ai pas changé les double quote en single quote

2024-08-22 07:28 UTC, Isalafont commented on app/javascript/controllers/choose_authorization_request_form_controller.js
> +  chooseEditor(event) {
Pareil pour l'espace de `chooseEditor (event)` et les `;` ?

2024-08-22 07:28 UTC, Isalafont commented on app/javascript/controllers/choose_authorization_request_form_controller.js
> +  static targets = [
Ah bin si finalement 😆

2024-08-27 08:57 UTC, evaspae commented
Pour info, j'avais pris le composant "contrôle segmenté" du DSFR 
https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/controle-segmente

On peut laisser en l'état si c'est plus simple pour vous. 
Si on garde comme ça, est-ce qu'on pourrait aligner les radio Button et la lettre sélectionnée ? 
Est-ce qu'on pourrait aussi réduire la taille du bloc pour qu'il s'aligne avec les boutons du choix de l'éditeur ? 

<img width="1338" alt="choix editeur" src="https://github.com/user-attachments/assets/db63425f-9720-4085-ac87-6390134a3c76">

2024-08-28 09:40 UTC, JeSuisUnCaillou commented
Sans avoir regardé le code, y'a un truc que j'aime pas du tout avec ce nouveau design : Il n'est absolument pas responsive.

Si j'ouvre la page dans une fenêtre un peu petite, je vais cliquer sur des trucs et ne pas voir les conséquences que ça a par ce que les éléments qui s'ajoutent sont en dessous de ma ligne de flotaison.

J'ai fait un petit GIF pour montrer ça : 

![Peek 2024-08-28 11-38](https://github.com/user-attachments/assets/4a725515-cb27-4f4e-932a-59fd63c380ee)

Je dis pas que c'était mieux avant, mais en tout cas là on peut faire un peu mieux à mon avis.
- Soit on scroll automatiquement jusqu'à l'élément ajouté
- Soit on fait ça avec un stepper, qui change d'étape à chaque sélection

2024-08-28 13:43 UTC, JeSuisUnCaillou commented
https://linear.app/pole-api/issue/DAT-532/integrer-le-nouveau-design-sur-la-premiere-etape#comment-a1032735
Go sur un petit scroll auto pour une quick win :+1:

2024-08-29 08:20 UTC, JeSuisUnCaillou reviewed
Juste une remarque sur la liste en dur des éditeurs "déjà intégrés".

2024-08-29 08:20 UTC, JeSuisUnCaillou commented on app/controllers/authorization_requests_controller.rb
> +      integrated_editor.new(id: 'editor_already_integrated', name:)
Etrange de voir cette liste en dur ici. On peut pas se baser sur de la data pour ça ?

2024-08-29 08:20 UTC, JeSuisUnCaillou commented on app/controllers/authorization_requests_controller.rb
> +      integrated_editor.new(id: 'editor_already_integrated', name:)
Je vois que c'est pas toi qui a inventé cette liste et qu'elle existait déjà en dur avant. Mais je pense qu'on peut sûrement faire mieux que ça pour la maintenabilité, dans un yaml de config ou dans une table

2024-09-02 12:14 UTC, jbfeldis commented on app/controllers/authorization_requests_controller.rb
> +      integrated_editor.new(id: 'editor_already_integrated', name:)
Exac' mais en creusant un peu dans la façon d'organiser les données ça me semblait pas _boyscoutable_ rapidement.

Je peux tout mettre dans un yaml mais il me semble que le mieux serait de le mettre dans le yaml "editors" avec une nouvelle clé "already_integrated" mais du coup faut vérifier les effets de bord.

Petite PR de follow up ? WDYT?

2024-09-02 12:43 UTC, JeSuisUnCaillou commented on app/controllers/authorization_requests_controller.rb
> +      integrated_editor.new(id: 'editor_already_integrated', name:)
Ah si, il est chargé dans le modèle `Editor`

2024-09-02 12:45 UTC, JeSuisUnCaillou commented on app/controllers/authorization_requests_controller.rb
> +      integrated_editor.new(id: 'editor_already_integrated', name:)
Ben ça me paraît très bien de faire ce que tu proposes ! Tu te sers du modèle pour obtenir la liste des éditors déjà intégrés, ça me paraît le bon endroit. Et je pense pas qu'ajouter un attribut aux editors va avoir d'effets de bords (et puis au pire y'a les tests pour ça)

2024-09-02 12:48 UTC, JeSuisUnCaillou commented
J'ai encore quelques soucis perso : 
- il faudrait scroll aussi lors du premier choix de la page
- ça scroll pas correctement sur les éditeurs "sans formulaire"

![Peek 2024-09-02 14-47](https://github.com/user-attachments/assets/03b3682a-7d92-4775-9bd3-f6c287cd6a1a)

2024-09-02 15:48 UTC, jbfeldis commented on app/controllers/authorization_requests_controller.rb
> +      integrated_editor.new(id: 'editor_already_integrated', name:)
En effet, ça s'est bien passé 👌

2024-09-02 15:54 UTC, jbfeldis commented
Je ferai un "squash and merge" donc ne mergez pas tous ces commits svp 🙏

2024-09-02 15:58 UTC, skelz0r commented
> Je ferai un "squash and merge" donc ne mergez pas tous ces commits svp 🙏

Y'a l'air d'avoir pas mal de commits de lint, ça mériterait du commit à part si possible.

2024-09-02 16:23 UTC, skelz0r requested changes
J'ai lâché quelques coms principalement sur la couche ruby. Pour moi faut déporter tout le code spécifique à API Entreprise ailleurs, je pense qu'une façade est un bon candidat et permettra d'encapsuler toute la logique spécifique uniquement à API Entreprise dans une classe, et ainsi ne pas polluer le controller/le modèle `Editor`.

Comme dit je sais plus où, le lint mériterai des commits à part.

2024-09-02 16:23 UTC, skelz0r commented on app/controllers/authorization_requests_controller.rb
> +  def already_integrated_editors
Ce code est beaucoup trop spécifique à API Entreprise.

J'introduirais un objet facade pour encapsuler toute cette logique pour l'index, de ce style:

```ruby
  before_action :extract_specific_facade_for_authorization_definition

  private

  def extract_specific_facade_for_authorization_definition
    @facade = Kernel.const_get("NewAuthorizationRequest::#{@authorization_definition.id.classify}Facade").new
  rescue NameError
  end
```

Dans `app/facades/new_authorization_request/api_entreprise_facade.rb`

```ruby
class NewAuthorizationRequest::APIEntrepriseFacade
  def grouped_editors
    # le code
  end
end
```

Et du coup dans la vue:

```
<% @facade.grouped_editors.each do |..| %>
```

2024-09-02 16:23 UTC, skelz0r commented on app/decorators/editor_decorator.rb
> +    @dom_id ||= "editor-#{id}-#{SecureRandom.alphanumeric}"
Pourquoi généré un id variable ?

Par ailleurs, `dom_id(editor)` ne renvoi pas déjà `editor_#{id}` ?

2024-09-03 07:51 UTC, jbfeldis commented on app/decorators/editor_decorator.rb
> +    @dom_id ||= "editor-#{id}-#{SecureRandom.alphanumeric}"
avec les éditeurs dans le yml j'ai un uid qui a du sens donc pas besoin en effet

sinon j'ai pas d'id donc il faut que je bricole ce qui ne permet pas utiliser dom_id directement

2024-09-03 07:51 UTC, jbfeldis commented on app/controllers/authorization_requests_controller.rb
> +    }.sort
anéfé, je vais le pimper un peu mais ce type de truc qui sort une liste ça sera jamais super lisible (mais c'est le nom de la méthode qui va faire le taff en vrai)

2024-09-03 07:51 UTC, jbfeldis commented on app/controllers/authorization_requests_controller.rb
> +  def already_integrated_editors
> En gros cet éditeur est déjà intégré, mais pour quoi ?

C'est une bonne question... Et c'est un peu inquiétant que tu saches pas 🤣 
Et je suis d'accord sur l'approche de bouger la logique dans un objet à part mais je trouve ça étrange d'avoir des éditeurs qui ont une particularité métier (surement discutable mais quand même !) et de considérer qu'ils ne doivent pas apparaitre dans la BDD des éditeurs.
Si on avait une table PG tu verrais pas ça dans une colonne dédiée ou dans une colonne json genre extra_params ?

Je suis d'accord sur l'approche facade (même si dans la façon de faire je vais plutôt faire une factory pour aller chopper la facade, comme ça on peut avoir facilement un comportement par défaut et rajouter des facades pour d'autres cas).

2024-09-03 07:59 UTC, skelz0r commented on app/controllers/authorization_requests_controller.rb
> +  def already_integrated_editors
> C'est une bonne question... Et c'est un peu inquiétant que tu saches pas 🤣

La question sous-jacente est que ce n'est pas clair surtout.

---

Si c'était en db, y'a 2 approches:
1. Je n'ajouterai pas l'info et gérerai ça dans la facade
2. Je mettrais un array => `already_integrated: ['api_entreprise']`

Vu le truc mega spécifique je ferai clairement 1.

---

> Je suis d'accord sur l'approche facade (même si dans la façon de faire je vais plutôt faire une factory pour aller chopper la facade, comme ça on peut avoir facilement un comportement par défaut et rajouter des facades pour d'autres cas).

Pourquoi complexifier avec une factory ? Ce que je propose est KISS++ (c'est 3 lignes de code :D)

2024-09-03 16:51 UTC, jbfeldis commented on app/facades/new_authorization_request/default_facade.rb
> +class NewAuthorizationRequest
J'ai repush ce POC pour qu'on en discute.

Pour moi ça reste plus clair si les éditeurs ont la données chez eux mais en effet on pourrait avoir les éditeurs sans ce nouveau "champ" et avoir une liste en dur dans la facade spécifique à api-entreprise.

@skelz0r @JeSuisUnCaillou on en discute en réponse ici pour éviter les commentaires globaux à rallonge ?

2024-09-04 15:02 UTC, Isalafont reviewed
Très stylé !  Super travail ! 

Quand tu aura le temps, je veux bien un petit point sur ce qu'est une façade et quand on décide de l'implementer and co pour ma culture perso 🙏

2024-09-04 15:02 UTC, Isalafont commented on config/locales/fr.yml
> +        start_text_with_form_name: 'Vous êtes sur le point de démarrer une nouvelle demande d''habilitation pour le compte de <a href="https://annuaire-entreprises.data.gouv.fr/etablissement/%{organi
Idem 👆🏻

2024-09-04 15:45 UTC, JeSuisUnCaillou commented on config/locales/fr.yml
> +        start_text: 'Vous êtes sur le point de démarrer une nouvelle demande d''habilitation pour le compte de <a href="https://annuaire-entreprises.data.gouv.fr/etablissement/%{organization_siret}"
Il est pas en trop en fait c'est comme ça qu'on échappe des apostrophes dans des strings entre apostrophes.

Mais c'est vrai que ce serait plus clair si on avait une string entre double quotes, ce qui éviterait d'avoir à échapper l'apostrophe.

2024-09-04 15:48 UTC, JeSuisUnCaillou commented on app/facades/new_authorization_request/default_facade.rb
> +class NewAuthorizationRequest
le nom de fichier correspond pas au nom de la classe :thinking:

2024-09-04 15:48 UTC, JeSuisUnCaillou commented on app/facades/new_authorization_request/default_facade.rb
> +class NewAuthorizationRequest
Mais sinon je suis pas contre ce que t'as fait. Mais je trouvais quand même ça vachement plus simple de faire un attribut dans les yaml de conf et de gérer ça nivau modèle @skelz0r

2024-09-04 16:17 UTC, jbfeldis commented on config/locales/fr.yml
> +        start_text: 'Vous êtes sur le point de démarrer une nouvelle demande d''habilitation pour le compte de <a href="https://annuaire-entreprises.data.gouv.fr/etablissement/%{organization_siret}"
ouais 🤔 

je suppose qu'il a priorisé cette règle parce qu'on a plusieurs doubles quotes dans la partie html

je vais regarder si y'a pas une astuce

2024-09-04 16:18 UTC, jbfeldis commented on app/javascript/controllers/scroll_to_controller.js
> +      window.scroll({
tout-à-fait d'accord !

2024-09-04 16:28 UTC, jbfeldis commented on app/facades/new_authorization_request/default_facade.rb
> +class NewAuthorizationRequest
si si ça matche mais j'ai mis sur 2 lignes, mais je vais repasser sur une seule, je sais plus la règle sur rubocop

je vais repush demain matin je pense, avec un mix, je vais garder les éditeurs dans le yml mais sans la donnée en plus et setup un tableau des identifiants dans la facade. 

Je pense que ça fera un bon compromis parce que la base des éditeurs va tous les contenir et la spécificité d'api-entreprise pourra être gérée avec un tableau d'identifiants au lieu des noms (et si c'est moche... on fera le plan B).

Et pour la facade, c'est un peu plus de code avec la factory (mais pas grand chose au final) mais ça a quelques avantages à mon sens:
- expliciter ce qui se passe (c'est la première du projet, d'autres suivront, autant que ça soit clair)
- être plus ouvert au changement (dans un cas nécessitant plus de logique ça serait difficile de faire un `const_get`)
- être plus "robuste" s'il faut capter dans 3 ans pourquoi la page marche plus parce qu'on a changé la route 😄

2024-09-09 10:50 UTC, jbfeldis commented on app/facades/new_authorization_request/default_facade.rb
> +class NewAuthorizationRequest
Bon bah c'était pas si simple en fait, donc j'ai gardé la donnée "propre" (mais un peu plus complexe du coup) dans le yaml des éditeurs parce que sans ça le code est trop moche :
la facade aurait du faire des trucs horribles ou alors la vue aurait du continuer à avoir la logique malgré le decorator

Là c'est plutôt aligné et c'est ouvert à d'autres cas dans le futur.

2024-09-09 12:28 UTC, Isalafont commented on config/locales/fr.yml
> +        start_text: 'Vous êtes sur le point de démarrer une nouvelle demande d''habilitation pour le compte de <a href="https://annuaire-entreprises.data.gouv.fr/etablissement/%{organization_siret}"
> Il est pas en trop en fait c'est comme ça qu'on échappe des apostrophes dans des strings entre apostrophes.
> 
Je ne connaissais pas cette façon de faire. J'ai toujours utilisé les double quote pour échapper les apostrophes! 
Merci pour le tips !

2024-09-09 14:19 UTC, JeSuisUnCaillou approved these changes
Allez on y a passé assez de temps là, let's go :rocket:

2024-09-16 09:22 UTC, skelz0r requested changes
Faut à minima changer le naming de `scope` en `definition_id` et faire du matching exact (les 2 propals que j'ai fait).

Pour ce qui est du `Base` vs `Default` je trouve ça compliqué. C'est peu critique car c'est du code isolé, mais on aurait pu faire un truc plus simple côté controller:

```ruby
  def extract_potential_facade
    @facade = Kernel.const_get("NewAuthorizationRequest::#{@authorization_request.definition.id.classify}Facade")
  rescue NameError
  end
```

Comme ça tu n'as qu'une seule classe à définir, qui encapsule la complexité en 1 seul endroit. Là tu as introduit 4 classes pour faire la même chose.

Après, pour moi il faut impérativement fixer le `scope` qui pour moi est plus que bancal (notamment le `/api.entreprise/.match?(scope)`) qui n'a aucune raison d'être car on peut faire du matching direct sur l'ID, le reste c'est ~ok.

2024-09-16 09:22 UTC, skelz0r commented on app/controllers/authorization_requests_controller.rb
> +    klass = NewAuthorizationRequest.facade(scope: params[:id])
```suggestion
    klass = NewAuthorizationRequest.facade(definition_id: id_sanitized)
```

2024-09-16 09:22 UTC, skelz0r commented on app/facades/new_authorization_request.rb
> +  end
```suggestion
  def self.facade(definition_id:)
    new(definition_id:).facade
  end

  def initialize(definition_id:)
    @definition_id = definition_id
  end

  def facade
    return APIEntrepriseFacade if api_entreprise?

    DefaultFacade
  end

  private

  attr_reader :definition_id

  def api_entreprise?
    definition_id == 'api-entreprise'
  end
```

2024-09-16 09:22 UTC, skelz0r commented on app/facades/new_authorization_request.rb
> +    DefaultFacade
Pourquoi ne pas utiliser `Base` ? C'est plus conventionnel ?

Sinon, juste ne rien renvoyer : y'a pas besoin d'avoir de facade en vrai.

2024-09-16 09:22 UTC, skelz0r commented on app/facades/new_authorization_request/default_facade.rb
> +  class DefaultFacade < Base
Quasiment l'intégralité des méthodes `Base` devrait être dans cette classe (sauf `public_available_forms`), et celle-ci devrait s'intitulé (`WithEditorsToSelect` / `WithEditors`). 
Pour moi ça n'a pas de sens de parler d'éditeurs dans la classe `Base`.

2024-09-16 09:46 UTC, jbfeldis commented
On merge (parce que trop long déjà) et on discute de l'implem ensuite !

2024-09-16 09:51 UTC, jbfeldis commented on app/facades/new_authorization_request.rb
> +    DefaultFacade
Ouaip, `Base` chez rails c'est le socle, tu l'utilises pas directement.

Et c'est vrai que y'a pas besoin, là le choix c'est concision/clarté.

Concision c'est ce que tu proposes : metaprog simple (mais metaprog quand même !) et il faut quand même gérer clairement le cas isolé donc il lui faut une contrepartie (donc au moins 2 facades).

Moi j'aime bien la carté quand c'est possible, là c'est ptet un peu overkill mais en même temps ça fait un bon "cas d'école" parce que la mécanique est facilement compréhensible.

2024-09-16 09:54 UTC, jbfeldis commented on app/facades/new_authorization_request/default_facade.rb
> +  class DefaultFacade < Base
J'avoue qu'au début j'avais pas fait de `Base` parce que c'était vachement logique d'avoir la facade spécifique qui hérite de `DefaultFacade` mais après je me suis dit "bon... quitte à faire autant répliquer la façon plus Rails".

Je ferai un follow up, c'est un bon sujet de discussion en plus cc @Isalafont 

(par contre je comprends pas ta propale de naming "WithEditorsToSelect / WithEditors" 🤔)

2024-09-18 08:38 UTC, skelz0r approved these changes
Le scope a été jarté c'est OK pour moi.

2024-09-18 08:39 UTC, merged

2024-09-18 08:39 UTC, JeSuisUnCaillou commented
Allez hop();