Add a custom class to apply the align-items css rule to body
etalab/data_pass pull request #379
Opened 2024-08-22 15:09 UTC by Isalafont

- the fr-grid-row classes did not apply on every page where the full custom notice disclaimer is used. On some page, it was ok and for some other the disclaimer was broken. `.prefilled_banner .fr-notice__body {}`  did not apply the `align-items:center` rules neither

  - Remove some css by replace it with dsfr class (color text)

Avant: 

![Capture d’écran 2024-08-22 à 17 07 51](https://github.com/user-attachments/assets/64d7b2e4-055c-4602-9493-be07fce35b84)

Après: 

![Capture d’écran 2024-08-22 à 17 08 45](https://github.com/user-attachments/assets/f4171d87-5b7b-4a96-a40d-edcc3404bd6b)

2024-08-22 16:13 UTC, JeSuisUnCaillou requested changes

2024-08-22 16:13 UTC, JeSuisUnCaillou commented on app/assets/stylesheets/components/prefilled_banner.css
> +}
:notes: ça existe dans le dsfr :musical_note: 

En vrai le problème c'est pas ça, c'est l'utilisation de `fr-col-md-10`. Je te fait un commit pour te montrer par ce que c'est chiant à expliquer x)

2024-08-22 16:16 UTC, JeSuisUnCaillou commented on app/views/authorization_request_forms/shared/_prefilled_banner.html.erb
> +      <p class="fr-col">
Voilà, ce qu'il fallait c'est un `fr-col` sur le texte, pour qu'il prenne toute la place qui se trouve à droite de l'icône. (ça fait un `flex-grow: 1`)

Et retirer le `fr-col-10` sur le grid-row, c'est juste par ce qu'il était pas nécessaire. Mais en fait il gênait pas.

2024-08-22 16:19 UTC, JeSuisUnCaillou approved these changes

2024-08-26 08:40 UTC, Isalafont commented on app/views/authorization_request_forms/shared/_prefilled_banner.html.erb
> +      <p class="fr-col">
En retirant encore une fois le display flex et l'align items center, l'icone n'est plus centré par rapport au texte. 

J'ai remis le `fr-col-10` qui est présent pour équilibrer le texte dans le composant comme proposé par @evaspae dans son design. 

Si dans le cas du text écourté, cela ne déséquilibre pas le composant, lorsque l'on ré-intégrera le texte manquant, 
ne pas avoir le `fr-col-10` donnera ceci : 
![Capture d’écran 2024-08-26 à 09 45 29](https://github.com/user-attachments/assets/8db801f2-90fc-4d0c-9082-1499a7404d84)

or le design est celui ci 
![Capture d’écran 2024-08-26 à 10 39 48](https://github.com/user-attachments/assets/7a89a14f-52d9-4a67-8472-5f48da25dd7e)

2024-08-26 08:54 UTC, merged