Extenso Partner
etalab/data_pass pull request #383
Opened 2024-08-23 09:10 UTC by Miryad3108

2024-08-23 09:16 UTC, Miryad3108 commented
Je n'ai pas complété le fichier 'features/habilitations/api_particulier/soumission.feature' car ce cas d'usage n'existe pas encore sur API Particulier (à venir quand on aura de premiers utilisateurs)

2024-08-26 09:14 UTC, jbfeldis requested changes

2024-08-26 09:14 UTC, jbfeldis commented on config/authorization_request_forms/api_particulier.yml
> +    contact_technique_phone_number: "<%= Rails.application.credentials.api_particulier_3douest_contact_technique_phone_number || '0836656565' %>"
les clés devraient être pour "extenso_partner" et non 3douest non ?

2024-08-26 09:14 UTC, jbfeldis commented on config/authorization_request_forms/api_particulier.yml
> +    # contact_technique_editable: false
autant ne pas garder le commentaire

2024-08-29 08:48 UTC, merged