Add a condition to display banner only one time in single page
etalab/data_pass pull request #395
Opened 2024-08-27 15:08 UTC by Isalafont

![screencapture-localhost-3000-formulaires-api-service-national-obligation-service-national-demande-commencer-2024-08-27-17_08_12](https://github.com/user-attachments/assets/82574069-abc4-4b18-a741-914ec2a1d459)

2024-08-27 15:15 UTC, skelz0r requested changes
Au regard du code il faut que tu appliques la même logique que dans app/views/authorization_request_forms/_form.html.erb L41

2024-08-27 15:15 UTC, skelz0r commented on app/decorators/authorization_request_decorator.rb
> +    return false unless object.form.multiple_steps?
Ce code est faux au regard du nom de la méthode: le fait que le formulaire ne soit pas à étape multiple n'implique pas qu'il n'y a pas de données pré-remplies.

2024-08-28 09:28 UTC, Isalafont commented on app/decorators/authorization_request_decorator.rb
> +    return false unless object.form.multiple_steps?
Le problème c'est juste le nom de la méthode ? 
Si ce n'est que cela, je le change vu qu'il y a une autre méthode `prefilled_data?` qui a été implémenté pour les changelogs.

2024-08-28 09:56 UTC, JeSuisUnCaillou commented on app/decorators/authorization_request_decorator.rb
> +    return false unless object.form.multiple_steps?
Je propose ça : 

```ruby
  def display_prefilled_banner?(keys)
    !object.form.multiple_steps? && prefilled_data?(keys)
  end

  def prefilled_data?(keys)
    object.form.data.keys.intersect?(keys.map(&:to_sym))
  end
```

et dans ta vue tu conditione l'affichage avec `display_prefilled_banner?`

2024-08-28 09:59 UTC, JeSuisUnCaillou commented on app/decorators/authorization_request_decorator.rb
> +    return false unless object.form.multiple_steps?
Comme ça on lit mieux :

"display prefilled banner if the form is not with multiple steps and there is prefilled data"

2024-08-28 10:01 UTC, JeSuisUnCaillou commented on app/decorators/authorization_request_decorator.rb
> +    return false unless object.form.multiple_steps?
(alors j'ai chié ma condition, c'est pas tout à fait ça, mais t'as saisi l'idée je pense xD)

2024-08-28 10:09 UTC, skelz0r commented on app/decorators/authorization_request_decorator.rb
> +    return false unless object.form.multiple_steps?
Cette méthode a toujours un mauvais nom car le fait que le formulaire soit à étape multiple n'a aucun lien avec le fait d'afficher ou non cette bannière.

Faut trouver un autre nom, qui traduit qu'il s'agit du prefilled uniquement pour les single pages.

2024-08-28 10:38 UTC, JeSuisUnCaillou commented on app/decorators/authorization_request_decorator.rb
> +    return false unless object.form.multiple_steps?
Ca a un lien par ce qu'on ne veut pas afficher cette bannière ici dans les formulaires à étapes multiples :thinking:

2024-08-28 10:39 UTC, JeSuisUnCaillou commented on app/decorators/authorization_request_decorator.rb
> +    return false unless object.form.multiple_steps?
Ah je vois, attend j'ai une proposition :

-> `display_prefilled_banner_inside_blocks?`

2024-08-28 10:44 UTC, JeSuisUnCaillou commented on app/decorators/authorization_request_decorator.rb
> +    return false unless object.form.multiple_steps?
Je précise :

```ruby
  def display_prefilled_banner_inside_block?
    object.form.multiple_steps?
  end

  def prefilled_data?(keys)
    object.form.data.keys.intersect?(keys.map(&:to_sym))
  end
```

et dans les vues de chaque block : 

```ruby
<% if display_prefilled_banner_inside_block? && prefilled_data?(...) %>
```

et dans le _form :
```ruby
  <% if !display_prefilled_banner_inside_block? && @authorization_request.form.prefilled? %>
```

2024-08-28 13:54 UTC, skelz0r approved these changes

2024-08-29 08:12 UTC, JeSuisUnCaillou commented
Allez hop ça merge. GG Isa :)

2024-08-29 08:13 UTC, merged