DAT-435 / Supprimer les sections informations Pré-remplies de la synthèse
etalab/data_pass pull request #399
Opened 2024-08-29 14:54 UTC by Isalafont

![screencapture-localhost-3000-formulaires-api-particulier-arpege-concerto-demande-50-resume-2024-08-29-16_46_37](https://github.com/user-attachments/assets/f64b935f-a9e6-4b2d-aedc-70d326a854ef)

----

En cours d'instruction 

![screencapture-localhost-3000-formulaires-hubee-dila-demande-47-resume-2024-08-29-16_47_31](https://github.com/user-attachments/assets/5e1b88c0-2292-4386-9dde-71706695d0d2)

2024-08-29 15:05 UTC, Isalafont commented
Closes [DAT-436/distinction-des-blocs-non-modifiables](https://linear.app/pole-api/issue/DAT-436/distinction-des-blocs-non-modifiables)

2024-08-29 15:08 UTC, Isalafont commented
Je souhaiterais m'attaquer à la refactorisation des alerts (il y en a 3 rien que dans ce fichier) mais je préfère le traiter dans une autre PR.

2024-08-29 15:45 UTC, JeSuisUnCaillou commented
> Closes [DAT-436/distinction-des-blocs-non-modifiables](https://linear.app/pole-api/issue/DAT-436/distinction-des-blocs-non-modifiables)

faut mettre ça dans le premier message de la PR, sinon linear le voit pas

2024-08-30 09:04 UTC, skelz0r requested changes
Juste supprimer la méthode qui possède un nom qui ne reflète pas ce qu'elle fait (et simplifier avec ce que je propose).

2024-08-30 09:04 UTC, skelz0r commented on app/views/authorization_request_forms/summary.html.erb
>        <% end %>
```suggestion
      <% @authorization_request.blocks.each do |block| %>
        <%= render partial: "authorization_requests/shared/blocks/#{block[:name]}", locals: { f: f, editable: @authorization_request.editable_blocks.pluck(:name).include?(block[:name]) } %>
      <% end %>
```

Je pense même que `@authorization_request.editable_blocks.include?(block)` fonctionne.

2024-08-30 09:04 UTC, skelz0r commented on app/views/authorization_requests/shared/blocks/_summary_block.html.erb
> +        Ces informations ne sont pas modifiables
Vu que tu as fais l'effort de faire du i18n autant le faire ici aussi.

2024-09-02 07:21 UTC, Isalafont commented
> > Closes [DAT-436/distinction-des-blocs-non-modifiables](https://linear.app/pole-api/issue/DAT-436/distinction-des-blocs-non-modifiables)
> 
> faut mettre ça dans le premier message de la PR, sinon linear le voit pas

C'était donc ça l'astuce avec Linear !

2024-09-02 08:11 UTC, Isalafont commented on app/views/authorization_request_forms/summary.html.erb
>        <% end %>
Ça fonctionnerait mais je ne suis pas certaine que cela faciliterait la compréhension de ce que fait cette méthode dans la view, d'où la création de la méthode dans le decorator.

2024-09-02 08:12 UTC, Isalafont commented on app/decorators/authorization_request_decorator.rb
> +  end
Je ne savais pas quel autre nom donner, des idées peut être ?

2024-09-02 08:25 UTC, Isalafont commented on app/decorators/authorization_request_decorator.rb
> +  end
`display_static_and_editable_blocks` ?

2024-09-02 08:29 UTC, skelz0r commented on app/decorators/authorization_request_decorator.rb
> +  end
Pour moi il faut utiliser `blocks` (il n'y a pas de raison d'utiliser autre chose en fait).

2024-09-03 09:45 UTC, evaspae approved these changes

2024-09-03 10:04 UTC, Isalafont commented on app/decorators/authorization_request_decorator.rb
> +  end
cad ?

2024-09-03 10:10 UTC, skelz0r commented on app/decorators/authorization_request_decorator.rb
> +  end
Il n'y a pas besoin d'introduire une nouvelle méthode.

2024-09-03 10:18 UTC, Isalafont commented on app/decorators/authorization_request_decorator.rb
> +  end
donc tu voudrais faire :

```ruby
def editable_blocks
    blocks.select do |block|
      object.form.static_blocks.pluck(:name).exclude?(block[:name])
    end
  end
  
  def static_blocks
    blocks - editable_blocks
  end

  def blocks
    object.definition.blocks.map do |block|
      {
        name: block[:name],
        editable: object.form.static_blocks.pluck(:name).exclude?(block[:name])
      }
    end
  end
  ```
  
  ça ne poserait pas de problème avec la méthode `editable_blocks` ?

2024-09-03 10:31 UTC, skelz0r commented on app/decorators/authorization_request_decorator.rb
> +  end
Oui ça posera problème parce que tu écrases (potentiellement) plein d'attributs sur les blocks.

```ruby
def blocks
  object.definition.blocks.map do |block|
    block.merge(editable: object.form.static_blocks.pluck(:name).exclude?(block[:name]))
  end
end
```

Après comme je disais dans un autre commentaire ce `editable` je l'aurais déporté en vue vu que c'est assez simple à comprendre/lire, mais je n'ai pas plus d'avis que ça.

2024-09-03 10:33 UTC, skelz0r commented on app/decorators/authorization_request_decorator.rb
> +  end
Mieux:

```ruby
def blocks
  @blocks ||= begin
    object.definition.blocks.map do |block|
      block.merge(editable: editable_blocks.include?(block))
    end
  end
end
```

2024-09-03 12:12 UTC, Isalafont commented on app/decorators/authorization_request_decorator.rb
> +  end
sinon : 

```ruby
def blocks
    @blocks ||= begin
                  static_block_names = object.form.static_blocks.pluck(:name)

                  object.definition.blocks.map do |block|
                    {
                      name: block[:name],
                      editable: static_block_names.exclude?(block[:name])
                    }
                  end
                end
  end

  def editable_blocks
    blocks.select { |block| block[:editable] }
  end

  def static_blocks
    blocks.reject { |block| block[:editable] }
  end
  ```

2024-09-03 12:26 UTC, skelz0r commented on app/decorators/authorization_request_decorator.rb
> +  end
```ruby
  def blocks
    @blocks ||= begin
      static_block_names = object.form.static_blocks.pluck(:name)

      object.definition.blocks.map do |block|
        block.merge(editable: static_block_names.exclude?(block[:name]))
      end
    end
  end

  def editable_blocks
    blocks.select { |block| block[:editable] }
  end

  def static_blocks
    editable_blocks - editable_blocks
  end
```

2024-09-03 12:30 UTC, Isalafont commented on app/decorators/authorization_request_decorator.rb
> +  end
je ne comprends pas la différence entre :
```ruby
def static_blocks
    blocks - editable_blocks
  end
  ```
  et
   ```ruby
  def static_blocks
    blocks.reject { |block| block[:editable] }
  end
  ```

2024-09-03 12:31 UTC, Isalafont commented on app/decorators/authorization_request_decorator.rb
> +  end
ni pourquoi faire : `block.merge(editable: static_block_names.exclude?(block[:name]))` serait mieux que 
`editable: static_block_names.exclude?(block[:name])`

2024-09-03 12:36 UTC, skelz0r commented on app/decorators/authorization_request_decorator.rb
> +  end
> je ne comprends pas la différence entre :
> 
> ```ruby
> def static_blocks
>     blocks - editable_blocks
>   end
> ```
> 
> et
> 
> ```ruby
> def static_blocks
>  blocks.reject { |block| block[:editable] }
> end
> ```

La fonctionnalité finale est la même en l'état, mais c'est mieux de faire qu'une seule fois le traitement (et accessoirement `blocks - editable_blocks` est plus clair)

> ni pourquoi faire : `block.merge(editable: static_block_names.exclude?(block[:name]))` serait mieux que `editable: static_block_names.exclude?(block[:name])`

Ce que je propose est de faire en sorte que si demain on ajoute des clés sur blocks la version que je propose n'écrase pas les clés. Ta version ne garde que `name`, ce qui n'est clairement pas souhaitable. Il s'agit du principe open close principle.

2024-09-03 13:08 UTC, skelz0r commented on app/decorators/authorization_request_decorator.rb
> +  end
> ah bah `blocks - editable_blocks`, je ne trouve pas forcément cela plus clair alors que pour`blocks.reject`, je sais que ça "rejette" les blocs editable. 🤷🏻‍♀️
> 
> ok pour le `merge`

C'est que le nom `editable_blocks` n'est pas assez clair. Ça me semble évident que les blocs soustrait des blocs éditables il ne reste que les blocs qui ne sont pas éditable, et donc static.

Et de toute façon, il ne faut pas doubler le traitement (ça fait 2 fois plus de code à maintenir, 2 fois plus de choses à comprendre), donc soit tu gardes le `select` soit le `reject`

2024-09-03 15:46 UTC, skelz0r approved these changes

2024-09-04 12:54 UTC, merged