Improve/dat 545/change linked token manager id attr
etalab/data_pass pull request #409
Opened 2024-09-04 14:11 UTC by Isalafont

2024-09-04 14:27 UTC, JeSuisUnCaillou approved these changes
Moi je suis super d'accord.

Toujours pas un grand fan du nom (même si c'est ma suggestion) mais c'est toujours 10x mieux que le nom original selon moi.

2024-09-04 14:36 UTC, skelz0r requested changes
Le naming ne me parait pas adapté, providers au pluriel est faux à mon sens.

Je propose d'autres naming en dessous (je me permet aussi de renommer en `data_provider` qui me semble plus accurate que `provider`, mais ça se discute)

1. `external_data_provider_id` => pas convaincu car on peut stocker autre chose qu'un ID
2. `external_data_provider_ids` => pas ultra convaincu car cela implique que l'on stocke un array
3. `external_data_provider_ids_data` => c'est plus vague, mais au moins ça traduit qu'on peut stocker autre chose que de l'ID (comme pour `HubEEDila`)

La propal 3 me semble être la plus adaptée, mais je suis pas 100% convaincu, faudrait en discuter je pense.

Autre point, plus pour ta culture perso, renommer une colonne en production n'est [pas safe](https://github.com/ankane/strong_migrations?tab=readme-ov-file#renaming-a-column), le mieux reste de faire ce qui est préciser dans le lien ici: https://github.com/ankane/strong_migrations?tab=readme-ov-file#renaming-a-column
Pour DataPass ce n'est pas critique donc on peut garder ce renommage (au pire du pire on aura quelques erreurs 500 pendant la migration), mais vraiment rien de grave.

2024-09-04 14:37 UTC, skelz0r commented
@JeSuisUnCaillou @jbfeldis des avis sur le naming ? Tant qu'on est dessus autant renommer ça bien.

2024-09-04 14:37 UTC, JeSuisUnCaillou commented
Le s c'est pour c'est "external provider's id". Mais j'entends, c'est pas fou.

2024-09-04 14:38 UTC, skelz0r commented
> Le s c'est pour c'est "external provider's id". Mais j'entends, c'est pas fou.

Conventionnellement on l'omet, si il n'y avait qu'un id ça aurait été `external_provider_id` (et plusieurs `external_provider_ids`) (sinon on comprend que c'est plusieurs providers)

2024-09-04 14:39 UTC, JeSuisUnCaillou commented
je tente un `external_provider_reference` et j'avance de 3 cases. Kamoulox. :shrug:

2024-09-04 14:40 UTC, skelz0r commented
> je tente un `external_provider_reference` et j'avance de 3 cases. Kamoulox ? 🤷

ça fait nom de foreign key ;p

2024-09-04 15:36 UTC, JeSuisUnCaillou commented
`external_provider_id_but_sometimes_it_is_a_hash_of_ids`

2024-09-04 15:49 UTC, skelz0r commented
Si tout le monde est OK pour `external_provider_id` let's go ça me va (et en effet c'est clairement mieux que l'ancien nom dtf). (je peux faire le sed ça me dérange pas)

2024-09-04 16:02 UTC, skelz0r commented
> > Si tout le monde est OK pour `external_provider_id` let's go ça me va (et en effet c'est clairement mieux que l'ancien nom dtf). (je peux faire le sed ça me dérange pas)
> 
> (et rollback puis rejouer la migration)

Ce qui n'est pas nécessaire si tu ne l'as pas encore jouée

2024-09-05 07:36 UTC, Isalafont commented
> Autre point, plus pour ta culture perso, renommer une colonne en production n'est [pas safe](https://github.com/ankane/strong_migrations?tab=readme-ov-file#renaming-a-column), le mieux reste de faire ce qui est préciser dans le lien ici: https://github.com/ankane/strong_migrations?tab=readme-ov-file#renaming-a-column Pour DataPass ce n'est pas critique donc on peut garder ce renommage (au pire du pire on aura quelques erreurs 500 pendant la migration), mais vraiment rien de grave.

Merci pour le lien, effectivement je ne le savais pas et surtout ce n'est pas inscrit dans la doc Rails ça 😅

2024-09-05 07:40 UTC, Isalafont commented
Du coup, je suis un peu perdue la sur ce que l'on doit faire et qui fait quoi ? 

De ce que j'ai compris, faut que je retravaille la migration donc 
- rollback la migration 
- retravailler la migration, faire quelque chose comme ça: 
```ruby 
class AddCorrectColumnNames < ActiveRecord::Migration
  def up
    add_column :table, :correct_name_column_one, :string
    add_column :table, :correct_name_column_two, :string

    puts 'Updating correctly named columns'
    execute "UPDATE table_name SET correct_name_column_one = old_name_column_one, correct_name_column_two = old_name_column_two"
    end
  end

  def down
    remove_column :table, :correct_name_column_one
    remove_column :table, :correct_name_column_two
  end
end
```
Et faire un sed dans le projet pour renommer les attributs, noms de variables / methodes and co partout (limite le plus simple à faire)

2024-09-05 08:47 UTC, skelz0r commented
Si tu n'as pas déployé cette PR sur une machine distante, tu peux juste te contenter de remplacer tous les termes (et de squash en 1 commit pour que ça soit atomiquement valide)

2024-09-05 08:48 UTC, skelz0r commented
> > Autre point, plus pour ta culture perso, renommer une colonne en production n'est [pas safe](https://github.com/ankane/strong_migrations?tab=readme-ov-file#renaming-a-column), le mieux reste de faire ce qui est préciser dans le lien ici: https://github.com/ankane/strong_migrations?tab=readme-ov-file#renaming-a-column Pour DataPass ce n'est pas critique donc on peut garder ce renommage (au pire du pire on aura quelques erreurs 500 pendant la migration), mais vraiment rien de grave.
> 
> Merci pour le lien, effectivement je ne le savais pas et surtout ce n'est pas inscrit dans la doc Rails ça 😅

Parce qu'en réalité ça n'a pas grand chose à voir avec rails, plus avec SQL.

2024-09-05 09:01 UTC, Isalafont commented
@skelz0r J'ai fait les modifications suivantes: 

- Creation d'une nouvelle colonne dans la db
- migration pour update la colonne external_provider_id avec ce que contient linked_token_manager_id
- Remplacer external_providers_id en external_provider_id
- Ajouter un `before_save` dans le model `AuthorizationRequest` pour écrire dans les 2 colonnes

Il manquera une migration pour remove la colonne obsolete mais j'aurais quelques questions: 
est ce que je suis sur la bonne voie ? 
Si oui, est ce que je dois / peux mieux faire ? 
Et toujours si oui, quand faire la migration de suppression de la colonne Linked_token_manager_id ?

2024-09-05 10:03 UTC, skelz0r commented
Je reprends pour info.

2024-09-05 10:26 UTC, skelz0r approved these changes

2024-09-05 10:26 UTC, merged