Ajoute un bouton pour annuler une réouverture côté utilisateur
etalab/data_pass pull request #421
Opened 2024-09-12 07:40 UTC by jbfeldis

Cette PR permet aux demandeurs d'annuler une demande de réouverture.
![Capture d'écran 2024-09-25 112412](https://github.com/user-attachments/assets/fbd702eb-9d9a-41fa-b9c0-7c8305edeacc)

![Capture d'écran 2024-09-25 112431](https://github.com/user-attachments/assets/5b3fb975-669a-4a95-9aca-f8bd81f04fb1)

2024-09-18 08:01 UTC, Isalafont commented
@jbfeldis Je n'ai pas encore regardé le code mais j'ai décelé un comportement étrange en testant le bouton `annuler la demande de réouverture`
Il apparait alors que je suis sur une demande simple (pas dans le cas d'une demande de réouverture) 

De plus si je clique quand même sur annuler, voici le comportement : 

https://github.com/user-attachments/assets/0eca063f-c656-43fe-a75a-0dcf341a3fc9

2024-09-23 12:32 UTC, JeSuisUnCaillou commented
On est bons sur cette PR maintenant @Isalafont ?

Comme t'as déjà review, je repasse pas en plus mais faudrait quand même dire à ce pauvre JB si c'est ok maintenant pour le libérer de ce sujet ^^

2024-09-23 19:04 UTC, Isalafont commented
Je viens de tester mais il me semble qu'il y ait toujours un effet non désiré. 

Lorsque l'on veut soumettre une demande d'habilitation, le bouton "soumettre la demande d'habilitation" est passé à gauche alors qu'il devrait être en bas à droite. 

Le bouton d'annulation fonctionne, par contre j'ai une petite question. 
Lorsque l'on a soumis une demande de mise à jour et que celle ci est en status "en cours d'instruction", est ce que le demandeur peut encore accéder au bouton "annuler la demande" et peut l'annuler. 
Est ce le comportement voulu ? (Désolée, je n'ai pas lu les specs complètes de la feature)

<img width="1512" alt="Capture d’écran 2024-09-23 à 21 02 38" src="https://github.com/user-attachments/assets/f97ce0f7-f00c-42b9-8a6c-50c185e99d5a">

2024-09-24 07:21 UTC, jbfeldis commented
Rahh les boutons !
Je regarde ça.

Et pour le comportement, le linear dit "Tant qu'une demande de réouverture n'a pas été soumise, le demandeur peut l'annuler". Dans ce cas il faudrait rendre la policy plus stricte.

Mais est-ce que ça vaut le coup d'empêcher les gens qui ont fait une boulette de la corriger (je précise que je pose la question de manière totalement neutre car je n'ai pas en tête toutes les implications) ?

2024-09-24 07:54 UTC, skelz0r commented
Vous êtes surtout entrain de discuter de la possibilité d'annuler une soumission et non une réouverture, du coup je pense que ça dépasse le scope de cette PR, et que coller à la spec que tu as citée me semble plus safe ici.

2024-09-24 13:08 UTC, jbfeldis commented
cf linear mais j'ai repush avec le fix visuel et une modification de la policy côté demandeur pour ne pas afficher le bouton lorsque la demande de réouverture a été soumise (sans changer le comportement pour l'instructeur pour le moment)

2024-09-24 13:18 UTC, skelz0r requested changes
Des petits changements mais globalement c'est OK pour moi.

Je pense que niveau wording faudrait invoquer @evaspae ou @SchweisguthN

2024-09-24 13:18 UTC, skelz0r commented on app/policies/authorization_request_policy.rb
> +      record.can_cancel_reopening? && !record.submitted?
Je déporterai le `!record.submitted?` dans la state machine (car c'est intrinsèque au modèle à mon sens)

2024-09-24 13:18 UTC, skelz0r commented on config/locales/fr.yml
> +            Vous êtes sur le point d'annuler la réouverture de l'habilitation '%{authorization_request_name}' au profit de l'organisation '%{organization_raison_sociale}' (numéro de siret: %{organiza
J'ajouterai un truc du genre "Toutes les informations en cours d'édition seront annulées. Votre habilitation sera toujours valide." (le wording n'est pas bon mais tu vois l'idée).

2024-09-24 13:18 UTC, skelz0r commented on features/reouverture_habilitation.feature
> +  Scénario: Annulation d'une demande de réouverture
J'ajouterai un test pour vérifier que le bouton n'est pas là quand c'est soumis.

2024-09-24 14:19 UTC, skelz0r commented on app/policies/authorization_request_policy.rb
> +      record.can_cancel_reopening? && !record.submitted?
Ah oui mybad bien vu.

2024-09-25 07:27 UTC, evaspae commented
@jbfeldis pour les wording : 

Pour les boutons : 
- Annuler ma demande de modification
- Envoyer ma demande de modification 

<img width="1440" alt="nav bar" src="https://github.com/user-attachments/assets/5924adfa-2e27-4c44-b2b1-090c3826fa60">

Pour la pop-up : 
- Annulation de vos modifications 
"Vous êtes sur le point d'annuler vos modifications, l'ensemble des changements que vous avez pu effectuer seront perdus. Votre habilitation quant à elle sera toujours valide."

2024-09-25 09:27 UTC, jbfeldis commented
ça devrait être tout bon

j'ai split l'affichage de la sticky_bar des boutons avec un elsif dans la vue summary pour pouvoir changer le wording du bouton de soumission, j'aime pas les elsif et surtout dans les vues mais c'est suffisant pour le moment

2024-09-25 10:51 UTC, skelz0r approved these changes

2024-09-25 11:52 UTC, merged