Draft: Hubee/dat 574/correctif wording
etalab/data_pass pull request #433
Opened 2024-09-19 15:13 UTC by Isalafont

WIP : Reste à faire pour lundi : 

- [x]  Retirer le provider_name et appeler le provider.name dans la page d'unauthenticated_start pour spécifier le nom du fournisseur
- [x] Changer les nom des fournissuer pour hubee (DILA et DGS) + ajout des logos et urls correspondants
- [x] Modifier les logos s'affichant pour hubee

- [ ] Ajouter un entête "Via HubEE" dans les formulaires adéquats. 

![screencapture-localhost-3000-formulaires-hubee-dila-demande-nouveau-2024-09-26-18_07_50](https://github.com/user-attachments/assets/7bcef343-2054-4288-877d-370f87db7eb0)

![screencapture-localhost-3000-formulaires-hubee-cert-dc-demande-nouveau-2024-09-26-18_08_25](https://github.com/user-attachments/assets/169404ee-461c-49e1-be42-365d6b657021)

![screencapture-localhost-3000-formulaires-api-entreprise-demande-nouveau-2024-09-26-18_08_55](https://github.com/user-attachments/assets/3de7fdf4-2371-4d62-8ce5-4de829d1d113)

![screencapture-localhost-3000-demandes-hubee-cert-dc-nouveau-2024-09-26-18_15_26](https://github.com/user-attachments/assets/7981f643-2c71-4816-a290-06aacb366a95)

2024-09-19 15:57 UTC, skelz0r commented
Je suis désolé @Isalafont mais je me permets de faire un commentaire dès maintenant : il faut juste faire en sorte de modifier les wordings et non les vues, sinon on ne va jamais s'en sortir si on doit customiser pour tout le monde chaque vue avec des conditions partout, ça deviendra inmaintenable. 

En regardant le figma, mise à part changer les "demandes d'habilitations" en "demandes d'abonnements" (qui pour moi est plus que douteux au passage, DataPass délivre des habilitations pas des "abonnements"), quasiment tout peut se faire en modifiant les wordings dans les fichiers YAML.

Ce que je te propose: tu modifies le maximum que tu peux dans les YAML, et ce que tu ne peux pas modifier sans avoir à faire des disjonctions on en discute de vive voix.

2024-09-19 15:58 UTC, skelz0r commented
> Ce que je te propose: tu modifies le maximum que tu peux dans les YAML, et ce que tu ne peux pas modifier sans avoir à faire des disjonctions on en discute de vive voix.

En ayant listé au préalable quelque part ofc.

2024-09-20 10:58 UTC, skelz0r commented
Je me permets de mettre cette PR https://github.com/etalab/data_pass/pull/437 qui va te permettre aussi de mieux customiser les vues en te basant sur les attributs des définitions et non sur le type spécifique de la définition.

2024-09-23 14:08 UTC, Isalafont commented
Merci à toi @Samuelfaure pour le coup de main !! 🙏

2024-09-23 15:04 UTC, Isalafont commented on app/views/authorization_request_forms/new.html.erb
> +    count: @authorization_request_form.authorization_definition.id == 'hubee_dila' ? 2 : 1) %>
Je suis d'accord ! On était en train de réfléchir à comment améliorer cela avec @Samuelfaure 👍🏻

2024-09-23 15:05 UTC, Isalafont commented on config/authorization_definitions.yml
> +    service_type: 'CertDC'
👍🏻

2024-09-23 15:16 UTC, skelz0r commented on app/views/authorization_request_forms/new.html.erb
> +    count: @authorization_request_form.authorization_definition.id == 'hubee_dila' ? 2 : 1) %>
Perso je vois 2 approches plus simple:

1. On trouve un wording qui fonctionne dans tous les cas: `abonné aux services fourni par NOM` (ou whatever) ;
2. On donne la possibilité à travers les wordings de customiser certaines parties de cette page d'intro (comme les wordings des labels/hint/titre d'étapes etc etc)

Je pense qu'on peut juste faire 1. et faire un wording générique qui marche.

2024-09-23 15:17 UTC, skelz0r commented on app/models/authorization_definition.rb
> +    :service_name,
Quel est la différence avec le nom ?

2024-09-23 15:27 UTC, skelz0r commented on app/views/authorization_request_forms/new.html.erb
> +    count: @authorization_request_form.authorization_definition.id == 'hubee_dila' ? 2 : 1) %>
Je précise aussi en amont: j'entends que ce n'est pas exactement la spécification/les retours d'HubEE, mais on ne peut pas s'amuser à customiser partout tous les wordings de chaque FD (parce qu'en vrai API Particulier et API Entreprise les wordings ne sont pas dingues et pourrait être plus adapté je trouve), et je trouve qu'importer la logique de disjonction entre service et api est déjà pas mal/a pas mal de sens pour un produit comme DataPass, et permet de donner assez de flexibilité pour customiser des wordings.

Fondamentalement in-fine les portails CertDC et DILA sont des services, on peut je pense trouver un bon wording pour englober les deux.

2024-09-24 08:06 UTC, Isalafont commented on app/views/authorization_request_forms/new.html.erb
> +    count: @authorization_request_form.authorization_definition.id == 'hubee_dila' ? 2 : 1) %>
@SchweisguthN et @evaspae, Je pense que votre avis sur les wordings sont nécessaires ici. 👆🏻

2024-09-24 08:09 UTC, Isalafont commented on app/models/authorization_definition.rb
> +    :service_name,
Hubee est un portail pour un service CertDC et des service lié à DILA, qui sont 2 équipes différentes. 

Pour le texte d'introduction, j'ai un nom d'équipe qui change dans l'intro, c'est le nom juste de Cert DC ou DILA. 
C'était la solution qui prenait le moins de ligne de code trouvé et surtout la moins redondante que d'implémenter un service_name précisant ces noms. 

maintenant si on doit tout retirer, je retirerais, je commence à perdre trop de temps sur une PR de wording.

2024-09-24 08:25 UTC, skelz0r commented on app/models/authorization_definition.rb
> +    :service_name,
En relisant ce que tu as mis dans les valeurs, il s'agit en fait du fournisseur ?
Par exemple pour API Entreprise ça serait la DINUM, pour API Impot Part la DGFIP etc etc ?

Si oui je pense que ça mérite d'être précisé partout, et exploité partout pour que ça soit générique (en mode "Vous êtes sur le point de démarrer une habilitation pour le service NAME, fourni par PROVIDER_NAME" (pour l'API -> "Vous êtes sur le point de démarrer une habilitation pour l'API NAME, fourni par PROVIDER_NAME"))

Ça me parait clairement intéressant à ajouter pour en effet customiser les intros/page en non authentifié, mais du coup faut l'ajouter partout pour tout le monde, je ne vois pas de raison de faire de disjonction entre HubEE et le reste. Je pense que la disjonction devrait être uniquement entre "service" et "api" (comme précisé dans un autre commentaire).

Du coup ça mériterait un commit du même style que 7703fcff (où on documente, teste, ajoute toutes les valeurs)

2024-09-24 08:27 UTC, evaspae commented
Pour les formulaires en single page, je propose de masquer la partie "les étapes de votre formulaire" car elle ne sert à rien. 

On peut conserver la partie "les objectifs de ce formulaire" et y intégrer les wording demandés par HubEE. 
Ça nous permet de régler le problème global d'info pas utile sur la page d'intro des formulaires single page. 

Ma proposition : 
<img width="1440" alt="1 c intro" src="https://github.com/user-attachments/assets/005f7415-85da-4d70-8d3c-3fff12078982">

2024-09-24 08:45 UTC, skelz0r commented
Mon commentaire globale:

Je vous invite à introduire un `provider_name` sur la définition (qui est en fait le `service_name` en fait, juste je pense que le naming n'est pas bon, ça se discute), et à ne manipuler qu'exclusivement `kind` et `provider_name` pour customiser les wordings de la page d'intro, et de supprimer purement et simplement les références à HubEE dans les vues/helpers/locales.

Pour plus de contexte : https://github.com/etalab/data_pass/pull/433#discussion_r1772892358 et https://github.com/etalab/data_pass/pull/433#discussion_r1771656908

2024-09-25 08:50 UTC, Samuelfaure commented on app/models/authorization_definition.rb
> +    :service_name,
@skelz0r OK pour rajouter ce champs, par contre je remarque qu'on a pas de spec d'acceptance pour ces fichiers de config, est-ce que j'ouvre un ticket?

2024-09-25 09:50 UTC, Samuelfaure commented
@SchweisguthN @evaspae Wordings generiques pour les providers de service (Hubee) - le but étant de ne pas s'embêter avec le pluriel / les noms de chaque formulaire 

![Screenshot 2024-09-25 at 11-48-34 DataPass](https://github.com/user-attachments/assets/3ef9056d-23f3-40d8-956c-77fabc2c3f5b)

![Screenshot 2024-09-25 at 11-48-06 DataPass](https://github.com/user-attachments/assets/6e71b540-47c5-473e-8e48-3d387246f67f)

![Screenshot 2024-09-25 at 11-48-34 DataPass](https://github.com/user-attachments/assets/0eacc73f-9486-4408-a720-95021877e0f2)

2024-09-25 10:50 UTC, skelz0r commented on app/models/authorization_definition.rb
> +    :service_name,
Comme tu veux, je n'en ai pas fait parce que j'ai jamais eu de souci :D

2024-09-25 12:40 UTC, skelz0r requested changes
Je request change pour des petits détails et le refactor du `provider_name` (en fait le modèle existe déjà comme souligné dans un commentaire, donc pas besoin d'ajouter la clé qui est déjà en fait renseignée), globalement c'est OK.

2024-09-25 12:40 UTC, skelz0r commented on config/authorization_definitions.yml
> +    provider_name: 'Dinum'
```suggestion
    provider_name: 'DINUM'
```

2024-09-25 12:40 UTC, skelz0r commented on config/authorization_definitions.yml
> +    provider_name: 'Dinum'
```suggestion
    provider_name: 'DINUM'
```

2024-09-25 12:40 UTC, skelz0r commented on config/editors.yml
> +    already_integrated:
Possible de revert les changements de ce fichier ? ça n'a pas lieu d'être dans cette PR ( c'est dans le commit f535962be3ecc61a2fb657a4bb19a8732b516f9c )

2024-09-25 12:40 UTC, skelz0r commented on app/views/authorization_request_forms/new.html.erb
> +        <%= t(".#{@authorization_definition.kind}.intro.title") %>
Je pense qu'il s'agit de code mort car il n'y a plus de wording spécifique au kind

```suggestion
        <%= t('.intro.title') %>
```

2024-09-25 12:40 UTC, skelz0r commented on app/views/authorization_request_forms/new.html.erb
> +        <%= t(".#{@authorization_definition.kind}.single_form.title") %>
idem que plus haut

```suggestion
        <%= t('.single_form.title') %>
```

2024-09-25 12:40 UTC, skelz0r commented on app/views/authorization_requests/new/default.html.erb
> +    <%= t('authorization_request_forms.new.api.organization.start_text', organization_raison_sociale: current_organization.raison_sociale, organization_siret: current_organization.siret).html_safe %>
Je pense que ce changement n'a plus lieu d'être (il faudra modifier la clé de la locale en conséquence)

```suggestion
    <%= t('authorization_request_forms.new.organization.start_text', organization_raison_sociale: current_organization.raison_sociale, organization_siret: current_organization.siret).html_safe %>
```

2024-09-25 12:40 UTC, skelz0r commented on app/models/authorization_definition.rb
> +    :provider_name,
En fait je me rends compte que `provider_name` est déjà implémenté 😅

Donc dans le code en fait il suffit de remplacer `authorization_definition.provider_name` en `authorization_definition.provider.name` partout où c'est utilisé.

2024-09-25 12:48 UTC, Isalafont commented on app/views/authorization_request_forms/new.html.erb
> +        <%= t(".#{@authorization_definition.kind}.intro.title") %>
Ce n'est pas du code mort, on utilise toujours le kind pour changer les intro.title. 
Si c'est une api on affiche "Les objectifs du formulaire" et dans le cas des services : "les objectifs de votre demande d'abonnement"

2024-09-25 12:49 UTC, Isalafont commented on app/views/authorization_request_forms/new.html.erb
> +        <%= t(".#{@authorization_definition.kind}.single_form.title") %>
idem que plus haut

2024-09-25 12:50 UTC, skelz0r commented on app/views/authorization_request_forms/new.html.erb
> +        <%= t(".#{@authorization_definition.kind}.intro.title") %>
oula oui, désolé j'ai pas les yeux en face des trous aujourd'hui j'ai interprété `type` (et donc `hubee_cert_dc` et non `service`)

2024-09-25 12:53 UTC, skelz0r commented on config/authorization_definitions.yml
> +    provider_name: 'Dinum'
(du coup ce commentaire est obsolète vis-à-vis de ma remarque sur le modèle `provider`)

2024-09-25 12:53 UTC, skelz0r commented on config/authorization_definitions.yml
> +    provider_name: 'Dinum'
(du coup ce commentaire est obsolète vis-à-vis de ma remarque sur le modèle `provider`)

2024-09-25 13:20 UTC, Isalafont commented on app/views/authorization_requests/new/default.html.erb
> +    <%= t('authorization_request_forms.new.api.organization.start_text', organization_raison_sociale: current_organization.raison_sociale, organization_siret: current_organization.siret).html_safe %>
On en a besoin, sinon ça plante pour `demandes/api-service-national/nouveau` par exemple
J'ai essayé de remplacer le `api` par `#{@authorization_definition.kind}` mais ça ne fonctionne pas

2024-09-25 13:23 UTC, Isalafont commented on app/models/authorization_definition.rb
> +    :provider_name,
On y a pensé sauf que pour cert_dc et Dila le provider name utilisé est "HubEE" or la on veut afficher "CertDC" ou juste "DILA". 
C'était pour cette raison qu'en premier lieu, je n'avais rajouté un champs service_name que sur hubee_cert_dc et hubee_dila car j'avais besoin de faire cette distinction uniquement pour ce cas la.

2024-09-25 13:31 UTC, skelz0r commented on app/models/authorization_definition.rb
> +    :provider_name,
J'avais mis HubEE parce que je pensais que c'était HubEE sur le moment, faut juste changer du coup (parce que le fournisseur de données n'est en effet pas HubEE, c'est juste un moyen (pour faire le parallèle, Rails est le moyen utilisé pour API Entreprise))

2024-09-25 13:32 UTC, skelz0r commented on app/models/authorization_definition.rb
> +    :provider_name,
Et dtf en l'état on a `provider.name` qui est `HubEE` et `provider_name` qui est `CERTDC` ce n'est dtf pas logique

2024-09-25 13:33 UTC, Isalafont commented on config/editors.yml
> +    already_integrated:
Euh c'était un fix de linter quand j'ai run une commande de lint ^^

2024-09-25 13:36 UTC, skelz0r commented on config/editors.yml
> +    already_integrated:
Intéressant, je pense que ça doit faire des yoyo entre les diverses configs d'IDE (ce qui est un poil pénible 🙄)

J'ai aucun souci à ce que ça soit commité, par contre si possible dans un commit à part en mode "Lint" pour que ça ne pollue pas le commit effectif (car cette modification n'a rien pas lieu d'être dans le commit associé actuel).

Si c'est trop relou ce n'est pas très grave, à garder en tête pour les prochaines histoire d'avoir un historique clean

2024-09-25 13:38 UTC, skelz0r commented on app/views/authorization_requests/new/default.html.erb
> +    <%= t('authorization_request_forms.new.api.organization.start_text', organization_raison_sociale: current_organization.raison_sociale, organization_siret: current_organization.siret).html_safe %>
Ok make sense, dans ce cas là mettre le bon kind (car là ça plante sur API Service national, mais si demain c'est sur un service ça n'affichera pas le bon wording).

```suggestion
    <%= t("authorization_request_forms.new.#{@authorization_definition.kind}.organization.start_text', organization_raison_sociale: current_organization.raison_sociale, organization_siret: current_organization.siret).html_safe %>
```

2024-09-25 13:49 UTC, skelz0r commented on app/models/authorization_definition.rb
> +    :provider_name,
> Ça ne changera pas le fait que je devrais à un moment rajouter un champs dans authorization_definition car j'aurais besoin d'afficher HubEE a un moment dans l'entête des formulaires.

T'as des exemples ? Ce n'est pas possible de mettre ça dans le nom de la définition ou du formulaire ?

2024-09-25 14:03 UTC, Isalafont commented on app/models/authorization_definition.rb
> +    :provider_name,
Il y a un figma et cette demande fait partie du Ticket. 

Après plus j'y reflechis et plus ça me dérange de mettre en provider DILA et CertDC, déjà car pour CertDC, le provider serait plutôt le Ministère de la santé et de la prévention / DGS et surtout parceque nous délivrons des habilitions pour l'obtention d'un abonnement HubEE qui permet d'accéder à ces 2 services. 

Et avant d'aller plus loin, j'aimerais que les visuels / wording soient validés par @SchweisguthN et @evaspae parce qu'on a pris beaucoup de liberté sur le texte par rapport au texte original.

2024-09-25 14:04 UTC, Isalafont commented on config/editors.yml
> +    already_integrated:
C'est ce que j'avais fait, un commit séparé `Lint`

2024-09-25 15:56 UTC, skelz0r commented on config/locales/fr.yml
> +            Si vous manquez de temps ou avez des questions, vous pourrez sauvegarder votre demande et la reprendre ultérieurement.
Ce wording est spécifique à HubEE, cela devrait être dans l'intro.

2024-09-26 07:22 UTC, SchweisguthN commented on app/models/authorization_definition.rb
> +    :provider_name,
C'est ok pour moi : on a certes pris de la liberté, mais au nom de la factorisation, ce qui est un argument qui s'entend. Je suis juste pas fan de "aux services du fournisseur DILA" sur la page non-authent, mais j'ai pas de meilleure idée et c'est un détail, donc go.

2024-09-26 07:32 UTC, skelz0r commented on app/models/authorization_definition.rb
> +    :provider_name,
Un peu plus de contexte ici: https://mattermost.incubateur.net/betagouv/pl/3s9ccm81f7b5tn3gzga9mhyqky

Le tl;dr est surtout que la page change d'objectif entre les maquettes pour HubEE et ce qu'elle est à l'origine (i.e. une intro au formulaire d'habilitation).

2024-09-30 14:50 UTC, skelz0r approved these changes

2024-10-01 09:11 UTC, merged