Hubee/dat 613/via hubee form header
etalab/data_pass pull request #457
Opened 2024-10-01 10:06 UTC by Isalafont

2024-10-01 10:18 UTC, skelz0r commented
Suivi de https://linear.app/pole-api/issue/DAT-613/ajouter-via-hubee-dans-le-header-des-formulaires-hubee-certdc-et-dila#comment-485918c7

Je me dis qu'en effet c'est peut-être un peu casse gueule de merger ce que tu proposes avec les éditeurs pour le wording "via X" / "via l'éditeur X" en l'état, sauf si sur API Part/Ent on est OK (ça serait mieux ça simplifierai grandement en vrai).

Une autre approche serait de recycler `editors` en `services` (je suis pas convaincu du nom, `service providers` c'est peut-être mieux), et à mettre un truc du style `type` avec `editor`, `saas` etc etc.. et faire une disjonction sur le wording avec ça not sure si ça a du sens pour autre que API Ent/Part et HubEE cela dit.

2024-10-01 12:00 UTC, Isalafont commented
J'ai testé avec API part / Api entreprise et ça ne pose pas de problème car le lien i18n n'est pas le même. 

Alors je ne suis pas certaines d'avoir tout compris quand à la totalité de ton commentaire. Je ne suis pas certaine quand à la deuxième partie de ton commentaire car l'éditeur est vraiment spécifique en majorité à Api Part et Entreprise.
Le cas des éditeurs ne se posent quasiment pas voir pas vraiment pour les autres API, a part peut être pour l'api le taxi ? 

Pour le moment, nous n'avons qu'un seule service (HubEE) et si à l'avenir on aura d'autres services qui peuvent se greffer, est ce que cela ne meritera pas encore une autre approche selon les demandes liées à ce service qui seront peut être différent des besoin actuel de hubee ?

2024-10-01 12:08 UTC, Samuelfaure commented
Perso ça me va mais je plussoie l'incertitude sur le terme `service`

HubEE c'est davantage `service_provider` imo? What about un truc du genre `bouquet_provider`  (c'est du franglais mais bon)

2024-10-01 14:36 UTC, Isalafont commented
> Typiquement je ne comprends pas pourquoi on aurait un affichage différent (je parle de style) entre "Via l'éditeur X" et "Via (le service) Y", car pour moi c'est ~pareil.

ça ne risquera pas de provoquer une confusion à l'utilisateur si l'on retire le terme `éditeur` dans `| Via l'éditeur name` ? 
@evaspae

2024-10-01 14:43 UTC, skelz0r commented
> > Typiquement je ne comprends pas pourquoi on aurait un affichage différent (je parle de style) entre "Via l'éditeur X" et "Via (le service) Y", car pour moi c'est ~pareil.
> 
> ça ne risquera pas de provoquer une confusion à l'utilisateur si l'on retire le terme `éditeur` dans `| Via l'éditeur name` ? @evaspae

Je parle du style et non du texte. Dans ton screen Via HubEE et en gras et Via l'éditeur Whatever est en thin, pourquoi ..?

2024-10-01 14:44 UTC, skelz0r commented
(pour le texte je suis moins convaincu et ça sera clairement une régression si on le fait, d'où ma proposition)

2024-10-01 14:45 UTC, skelz0r commented
Mon point ici est que c'est le même type d'infos et que ça devrait être hiérarchisé de la même manière (d'où aussi ma proposition de merger les 2 notions)

2024-10-01 15:14 UTC, Isalafont commented
J'ai clean la PR par contre je ne suis pas sure de mot pour service_name dans le fichier config/fr.yml. 

J'aime bien le terme service_provider, du coup je pense que je le changerais demain matin. 

Je n'ai pas encore fait les modif du modele editor pour y rajouter un type / service / saas / editor... 
je reprendrais à tête reposé demain.

2024-10-01 15:24 UTC, skelz0r commented
> J'aime bien le terme service_provider, du coup je pense que je le changerais demain matin.

Oui c'est pas mal.

Merci, bonne soirée !

2024-10-01 16:57 UTC, evaspae commented
> > > Typiquement je ne comprends pas pourquoi on aurait un affichage différent (je parle de style) entre "Via l'éditeur X" et "Via (le service) Y", car pour moi c'est ~pareil.
> > 
> > 
> > ça ne risquera pas de provoquer une confusion à l'utilisateur si l'on retire le terme `éditeur` dans `| Via l'éditeur name` ? @evaspae
> 
> Je parle du style et non du texte. Dans ton screen Via HubEE et en gras et Via l'éditeur Whatever est en thin, pourquoi ..?

C'est une erreur de ma part, je considérais HubEE comme une forme d'API au départ quand j'ai fais les maquettes mais ce n'est pas le cas. Gardons le même formalisme pour tout ce qui est utilisé en "via X".

Désolée, je vais modifier les maquettes

2024-10-02 07:58 UTC, Isalafont commented
> Je parle du style et non du texte. Dans ton screen Via HubEE et en gras et Via l'éditeur Whatever est en thin, pourquoi ..?

My bad, j'avais pas les yeux en face des trous et j'ai mal lu !

2024-10-02 08:17 UTC, skelz0r commented
> > Je parle du style et non du texte. Dans ton screen Via HubEE et en gras et Via l'éditeur Whatever est en thin, pourquoi ..?
> 
> My bad, j'avais pas les yeux en face des trous et j'ai mal lu !

Pas de souci ;)

2024-10-02 08:33 UTC, Isalafont commented
J'ai rajouté un type au model Editor pour specifier le `saas` pour HubEE et `editor` dans les autres cas. 

Par contre, je me pose des questions quand au renommage du model `Editor`.  
Déjà comment le renommer ? Je pensais à quelque chose comme `TechProvider` ou `ProductProvider` (j'aime moins la 2eme proposition perso) ? 

ensuite si on le fait, ça demande de faire quand même pas mal de changement dans le code 

1. Renommer partout editor en techprovider par ex (et ça impacte pas mal de fichier) 

2. Introduire le type, c'est bien mais si on ne l'utilise jamais, est ce que ça a un réel intérêt ? 
Donc indirectement, comment on utilise ce type et ou ? 

3. Ça commence à faire beaucoup de changement juste pour push en prod le `via HubEE` en tête de formulaire ?
Est ce que ça ne nécessiterait pas de prendre du temps pour conceptualiser cela et résoudre ces question dans un autre ticket ?

2024-10-02 08:40 UTC, skelz0r commented
J'aurais mis `ServiceProvider` comme tu le suggères (ça marche pour les éditeurs et HubEE).

> Renommer partout editor en techprovider par ex (et ça impacte pas mal de fichier)

C'est quelque chose qui arrive souvent dans une basecode, vu que t'utilises Rubymine tu peux faire du [mass renaming assez simplement](https://www.jetbrains.com/help/ruby/rename-refactorings.html) je dirais.

> Introduire le type, c'est bien mais si on ne l'utilise jamais, est ce que ça a un réel intérêt ?

C'est utilisé pour la disjonction de naming, c'est pour ça que plus haut je questionnais l'intérêt du "Via l'éditeur X" et que si on le négociait ça aurait été plus simple. Il aurait fallu juste faire un simple renaming dans le code.

> Ça commence à faire beaucoup de changement juste pour push en prod le via HubEE en tête de formulaire ?
> Est ce que ça ne nécessiterait pas de prendre du temps pour conceptualiser cela et résoudre ces question dans un autre ticket ?

tbh y'a rien de compliqué, tu veux conceptualiser quoi exactement ? Ce que tu as fait est très bien imo, suffit juste de renommer Editor en ServiceProvider.

2024-10-02 11:44 UTC, Isalafont commented
> C'est quelque chose qui arrive souvent dans une basecode, vu que t'utilises Rubymine tu peux faire du [mass renaming assez simplement (https://www.jetbrains.com/help/ruby/rename-refactorings.html) je dirais. 
tbh y'a rien de compliqué, tu veux conceptualiser quoi exactement ? Ce que tu as fait est très bien imo, suffit juste de renommer Editor en ServiceProvider.

Ah mais j'ai pas dit que c'était compliqué, je sous entend juste que c'est fastidieux parcequ'il y a plus de 190 occurrences du mot "editor" dans le code et toutes ne nécessitent pas d'être changées 😅

2024-10-03 14:32 UTC, skelz0r requested changes
2 gros points:

* L'introduction de la méthode de classe `editors` sur `ServiceProvider` pour filter vraiment que sur les éditeurs 
* Nettoyer les vues, ce n'est pas clair qu'elle vue doit afficher quoi à la fin (et où ..?)

2024-10-03 14:32 UTC, skelz0r commented on app/facades/new_authorization_request/api_entreprise_facade.rb
> +      @already_integrated_editors ||= ServiceProvider.all.select do |editor|
Ici j'introduirais une méthode `editors` sur `ServiceProvider` qui fait ceci:

```ruby
def self.editors
  self.all.where(type: 'editor')
end
```

Et du coup ici:

```suggestion
      @already_integrated_editors ||= ServiceProvider.editors.select do |editor|
```

histoire d'être plus accurate

2024-10-03 14:32 UTC, skelz0r commented on app/models/authorization_definition.rb
> +      form.service_provider.present? && form.service_provider.type == 'editor'
Bien vu !

2024-10-03 14:32 UTC, skelz0r commented on app/models/authorization_request_form.rb
> +    format(@introduction, editor_name: service_provider.try(:name), form_name: name)
Je ferai l'effort de changer aussi `editor_name` ici

2024-10-03 14:32 UTC, skelz0r commented on app/views/authorization_request_forms/_authorization_request_form_card.html.erb
> +            <%= authorization_request_form.service_provider.name %>
Ici je ferai:

```
<p class="fr-badge fr-badge--sm">
  <%= t(".through_#{authorization_request_form.service_provider}", service_provider_name: authorization_request_form.service_provider.name) %>
</p>
```

Et dans les locales:

```
through_editor: "Via l'éditeur %{service_provider_name}"
through_saas: "Via %{service_provider_name}"
```

c'est justement pour ça qu'on a introduit le type

2024-10-03 14:32 UTC, skelz0r commented on app/views/authorization_requests/shared/_service_provider.html.erb
> +<h2 class="authorization-request-form-header__editor-name">
du coup ce code n'a plus lieu d'être ?

2024-10-03 14:32 UTC, skelz0r commented on app/views/authorization_requests/shared/_title.html.erb
> +  <% if @authorization_request.form.service_provider.present? %>
Je suis pas sûr d'avoir tout suivi à travers cette PR mais du coup on a fusionné d'un point de vue style le `| HubEE` et le `| Via l'éditeur XXX` ?

2024-10-03 14:32 UTC, skelz0r commented on config/locales/fr.yml
> +        service_provider: "Via %{name}"
Ok en voyant ton code ici je comprends que c'est dans la vue `subtitle` qu'il faut changer, il faut donc faire la disjonction dans `shared/subtitle`, nettoyer `shared/title` et supprimer `service_provider.html.erb`

Si c'est pas dans subtitle mais title, c'est la même logique, juste faut que ça soit dans une seule vue la modif

2024-10-03 14:32 UTC, skelz0r commented on spec/decorators/service_provider_decorator_spec.rb
>      context 'when editor is already integrated' do
```suggestion
    context 'when service provider is already integrated' do
```

2024-10-03 14:32 UTC, skelz0r commented on spec/decorators/service_provider_decorator_spec.rb
>      context 'when editor is not already integrated' do
```suggestion
    context 'when service provider is not already integrated' do
```

2024-10-03 14:32 UTC, skelz0r commented on spec/facades/new_authorization_request/api_entreprise_facade_spec.rb
> +  let(:editor) { ServiceProvider.all.first }
```suggestion
  let(:editor) { ServiceProvider.editors.first }
```

related à mon commentaire plus haut

2024-10-03 14:32 UTC, skelz0r commented on spec/facades/new_authorization_request/default_facade_spec.rb
> +  let(:editor) { ServiceProvider.all.first }
```suggestion
  let(:editor) { ServiceProvider.editors.first }
```

related à mon commentaire plus haut

2024-10-03 14:32 UTC, skelz0r commented on spec/models/authorization_definition_spec.rb
> +        editor.is_a?(ServiceProvider)
```suggestion
        editor.is_a?(ServiceProvider) && editor.type == 'editor'
```

2024-10-03 14:36 UTC, Isalafont commented on app/models/authorization_request_form.rb
> +    format(@introduction, editor_name: service_provider.try(:name), form_name: name)
Alors j'avais fait cela, mais cela me créé une erreur. J'ai décidé de reverse le temps de clean toutes les autres erreurs et de comprendre pk ce editor_name me posait problème et surtout où ça me posait des problèmes 🤔

2024-10-03 14:37 UTC, Isalafont commented on app/views/authorization_request_forms/_authorization_request_form_card.html.erb
> +            <%= authorization_request_form.service_provider.name %>
C'est la partie que je n'ai pas encore commencé à faire 🫣

2024-10-03 14:38 UTC, Isalafont commented on app/views/authorization_requests/shared/_service_provider.html.erb
> +<h2 class="authorization-request-form-header__editor-name">
j'ai push un commit pour faire le changement de nom de la classe CSS

2024-10-03 14:38 UTC, skelz0r commented on app/models/authorization_request_form.rb
> +    format(@introduction, editor_name: service_provider.try(:name), form_name: name)
c'est dans les introductions des formulaires, donc à modifier dans config/authorization_request_forms/api_particulier.yml et config/authorization_request_forms/api_entreprise.yml

2024-10-03 14:39 UTC, Isalafont commented on spec/decorators/service_provider_decorator_spec.rb
>      context 'when editor is already integrated' do
Oh le vilain, il s'est caché celui la ! (en vrai j'ai pas fait de recherche global avec le mot `editor` car il y en avait bcp que l'on souhaitait garder et ça devenait confus sur le moment.

2024-10-03 14:39 UTC, skelz0r commented on app/views/authorization_requests/shared/_service_provider.html.erb
> +<h2 class="authorization-request-form-header__editor-name">
Je parle du fichier `service_provider.html.erb`

2024-10-03 14:40 UTC, Isalafont commented on spec/models/authorization_definition_spec.rb
> +        editor.is_a?(ServiceProvider)
oh bien vu !

2024-10-03 14:51 UTC, Isalafont commented on spec/decorators/service_provider_decorator_spec.rb
>      context 'when editor is already integrated' do
Plus sérieusement, ce sont les service provider de type editor qui sont déjà intégré ici, du coup, je pense que ça meriterait peut etre de prendre le temps pour refaire une passe sur ces tests la et voir si on doit / peut les améliorer

2024-10-03 14:51 UTC, Isalafont commented on app/models/authorization_request_form.rb
> +    format(@introduction, editor_name: service_provider.try(:name), form_name: name)
top merci !

2024-10-03 14:53 UTC, Isalafont commented on spec/decorators/service_provider_decorator_spec.rb
>      context 'when editor is already integrated' do
Ou pas ...
__

2024-10-03 14:54 UTC, skelz0r commented on spec/decorators/service_provider_decorator_spec.rb
>      context 'when editor is already integrated' do
Vu que cette notion d'éditeur est peu utilisé et à la lumière de ce que tu as modifié je pense que c'est OK avec les 4 modifications que j'ai suggéré.

Si on découvre plus tard une incohérence on scout commitera

2024-10-03 14:55 UTC, Isalafont commented on app/views/authorization_requests/shared/_service_provider.html.erb
> +<h2 class="authorization-request-form-header__editor-name">
Tu veux que le renomme en service.html.erb ou que je le supprime ?

2024-10-03 14:58 UTC, Isalafont commented on app/views/authorization_requests/shared/_title.html.erb
> +  <% if @authorization_request.form.service_provider.present? %>
Oui le style est fusionnée ! par contre je ne peux pas forcément réutiliser la même partial car dans un cas, j'ai un h2 avec un subtitle  + le via editeur name et dans l'autre juste le via editeur name ... 

Enfin, je dois surtout reprendre tout ça à tête reposé mardi pour y voir plus clair

2024-10-03 14:59 UTC, skelz0r commented on app/views/authorization_requests/shared/_service_provider.html.erb
> +<h2 class="authorization-request-form-header__editor-name">
Tu as précisé plus haut que tu n'avais pas encore implémenté la feature, donc je suppose que c'est potentiellement un relicat des anciennes itérations.

Je vais attendre que tu implémentes la feature finale (qui si on a tout bien fait devrait se cantonner à un test de présence du service_provider, et un wording conditionnel en fonction du type).

2024-10-09 10:27 UTC, jbfeldis requested changes
bien joué c'est cool et ça révèle plein de choses cette PR 👌

2024-10-09 10:27 UTC, jbfeldis commented on app/models/authorization_definition.rb
> +      form.service_provider.present? && form.service_provider.type == 'editor'
cf mon commentaire sur des méthodes de check des types, ça donnerait 
```suggestion
      form.service_provider.present? && form.service_provider.editor?
```

2024-10-09 10:27 UTC, jbfeldis commented on app/models/authorization_definition.rb
> +      form.service_provider.present? && form.service_provider.type == 'editor'
j'ajoute aussi que checker partout la présence c'est pas très élégant

terminons cette PR mais on devrait en discuter parce qu'on a déjà les outils pour faire ça "mieux" (des decorators et le null object pattern FTW!)

2024-10-09 10:27 UTC, jbfeldis commented on app/models/authorization_request_form.rb
> +    format(@introduction, service_provider_name: service_provider.try(:name), form_name: name)
y'a plusieurs camp sur le sujet... moi j'avoue que j'aime pas `try` (je précise que je ne dit pas qu'il ne faut pas l'utiliser, mais c'est un code smell assez fort je trouve) 
à mon sens ça boucle sur mes autres commentaires, avec un null object on n'aurait pas à faire cette vérification

2024-10-09 10:27 UTC, jbfeldis commented on app/views/authorization_requests/shared/_subtitle.html.erb
> +      locals: { name: @authorization_request.form.service_provider.name } %>
le check et le render pourraient être dans une méthode de decorator par exemple (ce qui permettrait aussi de faire plaisir à notre pote Demeter 😃 )

2024-10-09 10:27 UTC, jbfeldis commented on config/locales/fr.yml
> +
ça vaut le coup d'avoir une version spécifique pour les cards ?

2024-10-09 10:27 UTC, jbfeldis commented on spec/facades/new_authorization_request/default_facade_spec.rb
> +  let(:editor) { ServiceProvider.all.first }
je rouvre car il me semble que c'est passé à la trappe

2024-10-09 13:11 UTC, Isalafont commented on app/models/service_provider.rb
> +    :type,
On peut utiliser les enum sur les modèles en StaticApplicationRecord ?

Sinon je pensais à quelque chose comme ceci : 

```ruby
attr_accessor :id,
    :name,
    :siret,
    :type,
    :already_integrated

  TYPES = { saas: 'saas', editor: 'editor' }.freeze
...

  def self.editors
    all.select { |service_provider| service_provider.type == TYPES[:editor] }
  end
```

mais la encore, il faudrait encore rajouter des méthodes helper comme 
```ruby
def editors?
  service_provider.type == TYPES[:editor]
end

def saas?
  service_provider.type == TYPES[:saas]
end
```

2024-10-10 07:37 UTC, jbfeldis approved these changes
:shipit:

2024-10-10 08:05 UTC, merged