Dashboard: displays an updated date on reopening validated
etalab/data_pass pull request #458
Opened 2024-10-01 10:56 UTC by skelz0r

Closes https://linear.app/pole-api/issue/DAT-542

2024-10-01 11:07 UTC, skelz0r commented
<img width="1225" alt="Screenshot 2024-10-01 at 12 55 55" src="https://github.com/user-attachments/assets/eb85e706-3714-499c-8e79-1230a84abb0b">

2024-10-01 12:27 UTC, Isalafont requested changes
J'ai 2 messages d'alertes rails qui apparaissent dans les logs 

1 - "Need Counter Cache with Active Record size" :
Est ce qu'il ne faudra pas plutôt utiliser un counter cache plutôt que de le recalculer à chaque requête ? 

2 - "USE eager loading detected" :
potentiel problème de N+1 queries dans l'avenir ? 

![Capture d’écran 2024-10-01 à 14 26 58](https://github.com/user-attachments/assets/faaeb8ea-0a30-4c68-8d5a-0f12ff22538d)

2024-10-01 12:32 UTC, skelz0r commented
@Isalafont j'ai pas request de review car c'était pas prêt. Je viens de pousser le fix.

2024-10-01 13:07 UTC, Isalafont commented on app/controllers/dashboard_controller.rb
> +      .joins('left join authorizations on authorizations.request_id = authorization_requests.id')
Est ce que d'utiliser `includes(:authorization)` ne serait pas plus simple pour éviter le N+1 et précharger les Authorization ?

2024-10-01 13:12 UTC, skelz0r commented on app/controllers/dashboard_controller.rb
> +      .joins('left join authorizations on authorizations.request_id = authorization_requests.id')
Je ne pense pas car je fais un `authorizations.count`.

Y'a la ref dans le commit de pourquoi je fais ça.

2024-10-03 08:27 UTC, Isalafont approved these changes

2024-10-03 08:36 UTC, merged