Instruction: make the search dynamic
etalab/data_pass pull request #459
Opened 2024-10-01 14:15 UTC by skelz0r

* Enable auto submit on each field
* Add a turbo-frame to make it more dynamic (no full refresh)

Closes https://linear.app/pole-api/issue/DAT-529

2024-10-01 15:10 UTC, skelz0r commented
Je précise : la vidéo saute parce que ça submit / refresh la page, et le plugin loom saute du coup. C'est transparent pour l'usager à priori.

2024-10-01 15:58 UTC, jbfeldis requested changes
C'est vraiment mega mieux à l'utilisation 👌

2024-10-01 15:58 UTC, jbfeldis commented on app/javascript/controllers/application.js
> +import AutoSubmit from '@stimulus-components/auto-submit'
on pourrait utiliser le composant de stimulus-library comme ça on évite d'ajouter une dépendance en plus 

https://sub-xaero.github.io/stimulus-library/docs/controllers/form/AutoSubmitFormController

2024-10-01 16:46 UTC, skelz0r commented on app/javascript/controllers/application.js
> +import AutoSubmit from '@stimulus-components/auto-submit'
why not, je vais voir si ça marche

2024-10-01 16:51 UTC, evaspae commented
Je rejoins JB, c'est vachement mieux à l'usage ! 
Une question : est-ce qu'on garde le bouton de recherche du coup ?

2024-10-01 17:10 UTC, skelz0r commented on app/javascript/controllers/application.js
> +import AutoSubmit from '@stimulus-components/auto-submit'
it works j'ai changé

2024-10-01 17:14 UTC, skelz0r commented
> Une question : est-ce qu'on garde le bouton de recherche du coup ?

On pourrait le masquer en js en effet (comme ça on le garde et on est compatible avec les navigateurs).

2024-10-02 08:48 UTC, Isalafont commented
C'est vraiment mieux à l'usage ! 👍

2024-10-02 08:56 UTC, Isalafont approved these changes
LGTM

2024-10-02 08:57 UTC, JeSuisUnCaillou commented
> LGTM

"Let's Go To the Mall" ? :thinking:

2024-10-02 08:57 UTC, skelz0r commented
@jbfeldis need ton approval

2024-10-02 09:45 UTC, Isalafont commented
> > LGTM
> 
> "Let's Go To the Mall" ? 🤔

https://youtu.be/rtMR524m0BM?si=ZajEteATHlcDFmnr

2024-10-02 11:44 UTC, jbfeldis approved these changes
Amazin'

2024-10-02 11:54 UTC, merged