Feature/dat 571 se brancher avec lapi jcop
etalab/data_pass pull request #469
Opened 2024-10-04 10:23 UTC by Samuelfaure

- Interactor en cours 
- Reste à gérer le cas "unknown"

2024-10-04 10:29 UTC, skelz0r commented on app/models/malware_scan.rb
> +  belongs_to :authorization_document
Les authorization documents ne sont pas les documents liés aux authorizations requests, je pense qu'il faut associer le scan à un Blob ou Attachment (à voir)

2024-10-04 10:30 UTC, skelz0r commented on app/jobs/malware_scan_job.rb
> +  RETRIES = 3
J'aurais fait à l'infini mais c'est du détail

2024-10-04 10:31 UTC, skelz0r commented
En diagonale ça me semble clair.

Gros point ici https://github.com/etalab/data_pass/pull/469#discussion_r1787514712 => on veut analyser tous les documents, donc autant s'attacher directement aux ActiveStorage models (surtout que `AuthorizationDocument` n'est pas celui des requêtes)

2024-10-14 09:25 UTC, Isalafont commented on app/organizers/update_authorization_request.rb
> +    RunMalwareScanOnAttachments
Je pense que ce n'est pas nécéssaire de lancer `RunMalwareScanOnAttachments` pour le update car l'user doit de toute façon "submit" ses modifications pour que l'instructeur puisse accéder aux modifications effectuées.

2024-10-14 09:25 UTC, Isalafont commented on spec/factories/active_storage_blob.rb
> +    # key { SecureRandom.uuid }
My bad, tu l'as fait dans le commit suivant ^^

2024-10-14 09:26 UTC, Isalafont commented
Super PR !

2024-10-14 09:54 UTC, JeSuisUnCaillou requested changes
Plutôt stylé.

Il manque juste une gestion claire des scans pas finis je trouve.

2024-10-14 09:54 UTC, JeSuisUnCaillou commented on app/models/malware_scan.rb
> +  enum :safety_state, { safe: 'safe', unsafe: 'unsafe', unknown: 'unknown', pending: 'pending' }
Je préférerait avoir un array de symboles ici, je vois pas l'intérêt de manipuler plutôt des strings :thinking: 

Les enum de status comme ça, c'est clairement un cas d'usage parfait pour des symboles selon moi.

2024-10-14 09:54 UTC, JeSuisUnCaillou commented on app/jobs/malware_scan_job.rb
> +class MalwareScanJob < ApplicationJob
On n'inclut pas `KeepTrackOfJobAttempts` dans celui là ?
Ca me paraîtrait bien pourtant

2024-10-14 09:54 UTC, JeSuisUnCaillou commented on app/models/concerns/active_storage_attachment_extension.rb
> +end
J'ai pas trouvé d'utilisation de ce module, c'est normal ? (possible avec toutes les conventions)

2024-10-14 09:54 UTC, JeSuisUnCaillou commented on app/services/je_clique_ou_pas_api_client.rb
> +  end
Il me semble qu'on devrait pouvoir faire `Rails.application.credentials.je_clique_ou_pas.host` et `Rails.application.credentials.je_clique_ou_pas.token` ici.

2024-10-14 09:54 UTC, JeSuisUnCaillou commented on app/jobs/malware_scan_retrieve_state_job.rb
> +  end
Je comprend ici qu'on ne veut pas dire `safe` ou `unsafe` dans le cas où `is_malware` est `nil`. Est-ce que ça arrive vraiment, c'est quelque chose que tu as consataté en faisant des tests ?

Comme en plus on raise un `MalwareScanRetrieveStateJobError` L18 dans le cas où on aurait reçu un nil, je me demande dans quel cas on nous renverrai un `nil`, c'est pas tout à fait clair pour moi.

2024-10-14 09:54 UTC, JeSuisUnCaillou commented on app/jobs/malware_scan_retrieve_state_job.rb
> +  end
Ah je crois que je viens de comprendre : c'est quand le scan n'est pas fini.
Mais alors plutôt que de lever et rescue immédiatement une erreur, je ferait plutôt un `case nil` ici pour retourner un statut `ongoing_scan` ou un truc comme ça.

2024-10-14 09:54 UTC, JeSuisUnCaillou commented on app/jobs/malware_scan_retrieve_state_job.rb
> +  rescue StandardError
Si tu tiens à garder le système de raise/rescue pour gérer les scans qui n'ont pas terminés, rescue `MalwareScanRetrieveStateJobError` plutôt ici.

Sinon tu silence quasi toutes les erreurs là, c'est un peu chaud :D

2024-10-14 09:54 UTC, JeSuisUnCaillou commented on spec/jobs/malware_scan_retrieve_state_job_spec.rb
> +
Je dirais qu'il manque un contexte "when the scan hasn't finished" dans ces tests

2024-10-14 09:54 UTC, JeSuisUnCaillou commented on spec/jobs/malware_scan_retrieve_state_job_spec.rb
> +  describe 'after enough failures' do
context, not describe

2024-10-14 09:54 UTC, JeSuisUnCaillou commented on spec/jobs/deliver_authorization_request_webhook_job_spec.rb
> -          let(:tries_count) { described_class::THRESHOLD_TO_NOTIFY_DATA_PROVIDER }
pourquoi on retire ça dans cette PR ? :thinking:

2024-10-14 14:18 UTC, Samuelfaure commented on app/models/concerns/active_storage_attachment_extension.rb
> +end
C'est injecté dans ActiveStorage (la gem) à travers le fichier dans les initializer

2024-10-14 14:20 UTC, Samuelfaure commented on app/jobs/malware_scan_retrieve_state_job.rb
> +  rescue StandardError
OOPSI

2024-10-14 14:21 UTC, Samuelfaure commented on spec/jobs/deliver_authorization_request_webhook_job_spec.rb
> -          let(:tries_count) { described_class::THRESHOLD_TO_NOTIFY_DATA_PROVIDER }
C'est un boyscout, je m'autorise du hors-sujet dans les PRs pour les boyscouts que je découvre pendant la PR, je pense que c'est OK sauf si on décide que ça l'est pas

2024-10-14 14:23 UTC, Samuelfaure commented on spec/factories/active_storage_blob.rb
> +    # key { SecureRandom.uuid }
plutot my bad, si j'avais moins la flemme je ferais un rebase ^^´

2024-10-14 14:36 UTC, Samuelfaure commented on app/services/je_clique_ou_pas_api_client.rb
> +  end
J'aime bien comme ça en vrai, y'a une raison pour laquelle changer? (une convention?)

2024-10-14 14:39 UTC, JeSuisUnCaillou commented on app/services/je_clique_ou_pas_api_client.rb
> +  end
non rien de spécial. Osef en vrai, je resolve

2024-10-14 14:40 UTC, JeSuisUnCaillou commented on app/jobs/malware_scan_retrieve_state_job.rb
> +  end
ah oui on a déjà un statut pending ?
Est-ce que c'est bien ça le cas où `@response[:is_malware] == nil` du coup ?

2024-10-16 10:55 UTC, Samuelfaure commented on app/jobs/malware_scan_retrieve_state_job.rb
> +  end
du coup pour répondre ici, la réponse n'est jamais à nil (sauf absence de réponse)

2024-10-16 11:13 UTC, Samuelfaure commented on app/models/malware_scan.rb
> +  enum :safety_state, { safe: 'safe', unsafe: 'unsafe', unknown: 'unknown', pending: 'pending' }
ça me pose pas mal de soucis ici 🤔 notamment si je fais MalwareScan.update!(safety_state: :unknown) j'ai le safety state à nil

est-ce que je dois modifier ma migration postgresql (safety_state est un string) pour que ça marche? Je crois pas que postgresql gère les symbols en vrai

2024-10-16 11:14 UTC, Samuelfaure commented on app/jobs/malware_scan_job.rb
> +class MalwareScanJob < ApplicationJob
je vois pas pourquoi on ferait ça 🤔

2024-10-16 13:11 UTC, JeSuisUnCaillou commented on app/models/malware_scan.rb
> +  enum :safety_state, { safe: 'safe', unsafe: 'unsafe', unknown: 'unknown', pending: 'pending' }
Oui c'est évidemment pas postgresql qui va gérer des symboles. Ca sera des `:integer` en db, mais dans la couche modèle tu lui dit d'en faire des symboles.

C'est d'ailleurs la manière conventionnelle d'utiliser les enum : https://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html

En faire des strings, c'est pas recommandé, car ça fait une colonne moins opti pour les requêtes SQL :

![image](https://github.com/user-attachments/assets/4b86cd9b-7c89-4e40-b54e-0dc32b0cea74)

Je te conseille cet article si tu veux un guide : https://blog.saeloun.com/2022/01/05/how-to-use-enums-in-rails/

2024-10-16 13:14 UTC, JeSuisUnCaillou commented on app/jobs/malware_scan_job.rb
> +class MalwareScanJob < ApplicationJob
Ben c'est un job qui retry, pourquoi ne pas track ses tentatives ? Ou alors y'a un truc que j'ai pas saisi.

2024-10-16 13:17 UTC, Samuelfaure commented on app/models/malware_scan.rb
> +  enum :safety_state, { safe: 'safe', unsafe: 'unsafe', unknown: 'unknown', pending: 'pending' }
Thanks je regarde ça 🙏

2024-10-16 13:18 UTC, Samuelfaure commented on app/jobs/malware_scan_job.rb
> +class MalwareScanJob < ApplicationJob
Quel interêt de track ses tentatives?

2024-10-16 16:06 UTC, JeSuisUnCaillou commented on app/jobs/malware_scan_job.rb
> +class MalwareScanJob < ApplicationJob
Alors peut-être que je ne saisissais pas les cas dans lesquels on voulait tracker les tenatives.
Quel est l'intérêt de tracker les tenatives de `MalwareScanRetrieveStateJob` par exemple ?

2024-10-16 16:08 UTC, JeSuisUnCaillou commented on app/models/malware_scan.rb
> +  enum :safety_state, { safe: 'safe', unsafe: 'unsafe', unknown: 'unknown', pending: 'pending' }
Cela dit avoir des strings dans la DB rend la DB plus lisible telle quelle, sans avoir la couche modèle, ce qui peut se défendre. Mais par défaut, je suis plutôt pour gérer avec des integer/symboles en suivant la convention rails.

2024-10-16 16:29 UTC, JeSuisUnCaillou approved these changes
Juste deux dernières remarques, mais je valide pour que tu puisses merge une fois que tu les aura traitées, je pense que c'est pas bloquant non plus.

2024-10-16 16:29 UTC, JeSuisUnCaillou commented on app/models/malware_scan.rb
> +  validates :safety_state, presence: true, inclusion: { in: safety_states.keys }
Il n'y a pas besoin de préciser `inclusion: { in: safety_states.keys }` dans la validation, c'est redondant avec la déclaration de l'enum qui embarque déjà cette validation.

2024-10-16 16:29 UTC, JeSuisUnCaillou commented on spec/jobs/malware_scan_retrieve_state_job_spec.rb
> +    end
Le cas normal quand un scan est pas fini, c'est de recevoir un ServerError ? :thinking ça m'étonne.
Il faudrait plutôt décrire ici le cas "normal" d'un scan pas fini.

2024-10-16 16:33 UTC, Samuelfaure commented on app/jobs/malware_scan_job.rb
> +class MalwareScanJob < ApplicationJob
C'est pour pouvoir faire autre chose au dessus d'un certain nombre d'essais, ici on ne fait pas ça

2024-10-17 09:11 UTC, JeSuisUnCaillou commented
Note : Ne pas oublier de mettre les credentials jcop en sandbox aussi

2024-10-17 12:18 UTC, Samuelfaure commented
Bien vu

2024-10-18 07:05 UTC, Samuelfaure commented
re-requesting pour les derniers commits ([8c78ea9](https://github.com/etalab/data_pass/pull/469/commits/8c78ea93c6866c0ede0bec82f3d84aa999b67a70) et suivants)

2024-10-18 15:36 UTC, JeSuisUnCaillou commented
Tu pourrais joindre quelques screenshots pour qu'on puisse voir l'UI sans avoir à run le malware scan ?

2024-10-21 09:55 UTC, skelz0r requested changes
Les 2 jobs sont un peu raw, de plus les status `pending` et `ongoing_scan` devraient être fusionnés (surtout que le premier n'a pas de sens dans le code, il est déjà en cours de scan à la création)

2024-10-21 09:55 UTC, skelz0r commented on app/interactors/run_malware_scan_on_attachments.rb
> +      attachment = context.authorization_request.send(attachment_name)
```suggestion
      attachment = context.authorization_request.public_send(attachment_name)
```

2024-10-21 09:55 UTC, skelz0r commented on app/jobs/malware_scan_job.rb
> +    return if attachment&.blob.blank?
```suggestion
    return if attachment.blob.blank?
```

`find` lève déjà un `ActiveRecord::NotFoundError`

Il faudrait le catch, ou alors modifier le code pour faire un `find_by` et `return if attachment.blank? || attachment.blob.blank?` (qui est plus clair)

2024-10-21 09:55 UTC, skelz0r commented on app/jobs/malware_scan_job.rb
> +    MalwareScanRetrieveStateJob.perform_later(uuid)
c'est difficile à lire, ça mériterait de faire quelques méthodes pour que ça soit cristal clear

2024-10-21 09:55 UTC, skelz0r commented on app/models/malware_scan.rb
> +  enum :safety_state, { pending: 0, ongoing_scan: 1, safe: 2, unsafe: 3, unknown: 4 }
pourquoi avoir utilisé `safety_state` et pas `status` ..?

2024-10-21 09:55 UTC, skelz0r commented on app/jobs/malware_scan_retrieve_state_job.rb
> +    MalwareScan.find_by(uuid:).update!(safety_state: :ongoing_scan)
Pour moi ce code n'a pas lieu d'être. 

Pourquoi il ne s'agit pas du status par défaut ? Ou tout du moins, on devrait le setup dans le job précédent à mon sens. De ce fait, je pense que `pending` et `ongoing_scan` doivent être fusionné (surtout que dans le job précédent tu fais l'analyse puis tu crées le modèle, à ce stade c'est déjà en `ongoing_scan`)

2024-10-21 09:55 UTC, skelz0r commented on app/jobs/malware_scan_retrieve_state_job.rb
> +    @response = api_client.result(uuid)
```suggestion
    @api_result = api_client.result(uuid)
```

2024-10-21 09:55 UTC, skelz0r commented on app/jobs/malware_scan_retrieve_state_job.rb
> +    raise MalwareScanRetrieveStateJobError unless @response && safety_state
```suggestion
    raise MalwareScanRetrieveStateJobError unless safety_state.present?
```

plus clair

2024-10-21 09:55 UTC, skelz0r commented on app/jobs/malware_scan_retrieve_state_job.rb
> +    return unless analyzed_at_raw
ce cas existe ? je mettrai à minima la date courante non ?

2024-10-21 09:55 UTC, skelz0r commented on app/jobs/malware_scan_retrieve_state_job.rb
> +    MalwareScan.find_by(uuid:).update!(safety_state: :ongoing_scan)
Et au passage, y'a 2 fois un find sur le même objet. Cette classe au global n'est pas très claire je trouve on pourrait simplifier je pense.

2024-10-21 09:55 UTC, skelz0r commented on db/migrate/20241003093735_create_malware_scan.rb
> +      t.uuid :uuid, null: false
il manque une contrainte d'unicité ainsi qu'un index

2024-10-21 09:55 UTC, skelz0r commented on app/models/malware_scan.rb
> +class MalwareScan < ApplicationRecord
il faut ajouter une contrainte de validation sur l'unicité du uuid

2024-10-21 09:55 UTC, skelz0r commented on features/habilitations/api_entreprise/soumission.feature
> +    * Je joins une maquette au projet "API Entreprise"
pourquoi ?

2024-10-21 09:55 UTC, skelz0r commented on spec/jobs/malware_scan_job_spec.rb
> +  it 'creates a MalwareScan with right params' do
il faut aussi montrer que le status est bon à mon sens

2024-10-21 09:55 UTC, skelz0r commented on app/jobs/malware_scan_retrieve_state_job.rb
> +  def safety_state
dans le cas de `nil` du coup ça lève une erreur InvalidRecord plus haut ? Si non, il faudrait (ou explicitement raise ici ?)

2024-10-22 08:32 UTC, Samuelfaure commented on features/habilitations/api_entreprise/soumission.feature
> +    * Je joins une maquette au projet "API Entreprise"
Vu que c'est le scénario basique et que j'ai dev le step de maquette je me dit que c'est bien de tester que l'upload de maquette fonctionne

Il manque un test cucumber pour voir si le malware scan fonctionne sur un upload de maquette

2024-10-22 08:32 UTC, Samuelfaure commented on app/jobs/malware_scan_retrieve_state_job.rb
> +    MalwareScan.find_by(uuid:).update!(safety_state: :ongoing_scan)
J'étais parti sur avoir seulement "pending" mais je me disais que ça serait cool d'afficher lorsque le scan a été lancé

Mais si tu trouves ça superflu je vire 👍

2024-10-23 12:26 UTC, Samuelfaure commented on app/models/malware_scan.rb
> +  enum :safety_state, { pending: 0, ongoing_scan: 1, safe: 2, unsafe: 3, unknown: 4 }
Ça me semble plus explicite qu'on parle exactement de la mesure de sûreté, comme il s'agit de sécurité j'ai choisi d'être crystal clear

2024-10-23 12:50 UTC, Samuelfaure commented on app/jobs/malware_scan_retrieve_state_job.rb
> +  def safety_state
si safety_state est nil ça raise ici:

`raise MalwareScanRetrieveStateJobError if safety_state.blank?`

2024-10-23 12:50 UTC, Samuelfaure commented
![image](https://github.com/user-attachments/assets/6432bda6-8174-48de-a4c8-44d4c3074a36)
![image](https://github.com/user-attachments/assets/2d9c1402-fcca-4f32-9bce-f860a46f53a7)
Captures d'écrans du badge

2024-10-25 13:06 UTC, Samuelfaure commented
![image](https://github.com/user-attachments/assets/2541d1da-b405-498c-834a-623f87bb48f6)

Je re-request une review pour les 2 derniers commits, certificat + gros changement dans la classe JeCliqueOuPasAPIClient, c'est un poil moche encore je prend les conseils

2024-10-28 09:58 UTC, Samuelfaure commented
Ok c'est un peu plus propre.

Pour la review, relisez juste la classe JeCliqueOuPasAPIClient

2024-10-28 10:19 UTC, Samuelfaure commented on app/jobs/malware_scan_retrieve_state_job.rb
> +  def perform(uuid)
J'avais fait comme ça , mais pas possible de passer des objets "attachments" aux jobs 

```
     ActiveJob::SerializationError:
       Unsupported argument type: ActiveStorage::Attached::One
```

2024-10-28 10:32 UTC, Samuelfaure commented on app/interactors/run_malware_scan_on_attachments.rb
> +  end
On a pas accès à authorization_request ici (du coup faut que je vire la ligne 22)

J'ai piqué ce code depuis la classe AssignParamsToAuthorizationRequest

2024-10-28 11:14 UTC, Samuelfaure commented on app/interactors/run_malware_scan_on_attachments.rb
> +  end
Ok truc mindfuck ici: context.authorization_request est un AuthorizationRequestDecorator

faut que je fasse ceci pour que ça marche:
```
  def attachment_names
    context.authorization_request.form.authorization_request_class.documents
  end
```
Je pense que y'a un truc à clean (mais dans une autre PR)

2024-10-28 15:49 UTC, merged