Ajoute le service provider aux données des webhooks
etalab/data_pass pull request #476
Opened 2024-10-10 16:29 UTC by jbfeldis

2024-10-20 18:40 UTC, skelz0r requested changes
1. ce n'est pas testé 🤔
2. le code cog n'a rien à faire ici imo, pour plusieurs raisons: ça ne sert qu'à API Part, et le siret permet de récupérer via l'INSEE ce code cog (et donc on peut le récupérer coté API Part)

2024-10-23 09:29 UTC, skelz0r commented
cf mes 2 remarques + 2 commits

2024-10-23 13:49 UTC, Samuelfaure approved these changes

2024-10-23 13:51 UTC, skelz0r approved these changes

2024-10-23 14:21 UTC, merged