Block volumetrie
etalab/data_pass pull request #498
Opened 2024-10-22 09:11 UTC by JeSuisUnCaillou

Closes https://linear.app/pole-api/issue/DAT-597/bloc-volumetrie

2024-10-22 10:05 UTC, skelz0r commented on app/javascript/controllers/volumetrie_justification_controller.js
> +export default class extends Controller {
je pense tu peux reprendre app/javascript/controllers/personal_data_duree_conservation_justification_controller.js le refactoriser et passer la valeur en param

2024-10-24 10:05 UTC, JeSuisUnCaillou commented on app/javascript/controllers/volumetrie_justification_controller.js
> +export default class extends Controller {
yes, done :+1:

2024-10-24 10:21 UTC, skelz0r requested changes
Les 2 gros points:
* les locales dans activerecord
* le modèle definition a revert

2024-10-24 10:21 UTC, skelz0r commented on app/models/authorization_definition.rb
> +    :volumetries
Tu peux revert tout ce fichier ce n'est plus nécessaire

2024-10-24 10:21 UTC, skelz0r commented on app/form_builders/dsfr_form_builder.rb
> +    select(attribute, choices, { include_blank: opts[:include_blank] }, class: 'fr-select', **enhance_input_options(opts).except(:class))
ça aurait mérité un commit à part

2024-10-24 10:21 UTC, skelz0r commented on app/models/concerns/authorization_extensions/volumetrie.rb
> +    self.class::VOLUMETRIES
```suggestion
    self.class::VOLUMETRIES
    rescue NameError
      raise "Must declare a constant VOLUMETRIES in the model #{self.class}, for example {'20 appels / minute' => 20}"
    end
```

C'est plus ruby way de faire de cette manière

2024-10-24 10:21 UTC, skelz0r commented on app/models/concerns/authorization_extensions/volumetrie.rb
> +  def default_volumetrie
```suggestion
  def smallest_volumetrie
```

C'est peut-être le default dans la vue, mais d'un point de vue modèle ça n'est pas le cas, ni évident, et c'est brainfuck

2024-10-24 10:21 UTC, skelz0r commented on app/models/concerns/authorization_extensions/volumetrie.rb
> +    volumetrie_appels_par_minute.to_i > default_volumetrie
```suggestion
    volumetrie_appels_par_minute.to_i > smallest_volumetrie
```

2024-10-24 10:21 UTC, skelz0r commented on config/locales/activerecord.fr.yml
> +        volumetrie_justification: Pour quels motifs souhaitez-vous un débit plus grand que le minimum ?
C'est très étrange de décrire un attribute par une question. Je pense que tu confonds attribut et label (ce dernier doit être customiser dans l'autre fichier de locale).

```suggestion
        volumetrie_appels_par_minute: Volumétrie souhaitée
        volumetrie_justification: Justification de la volumétrie demandé
```

2024-10-24 10:21 UTC, skelz0r commented on config/locales/authorization_request_forms.fr.yml
> +      volumetrie:
c'est dans ce fichier que tu mets tes questions défini dans le fichier activerecord.yml

2024-10-24 10:21 UTC, skelz0r commented on config/locales/activerecord.fr.yml
> +        volumetrie_justification: Pour quels motifs souhaitez-vous un débit plus grand que le minimum ?
Surtout que si tu as des erreurs sur ces champs ça ve te faire `Quelle limitation de débit souhaitez- vous pour votre téléservice ? n'est pas inclut dans la liste`, ce qui est étrange.

2024-10-24 10:28 UTC, JeSuisUnCaillou commented on app/models/authorization_definition.rb
> +    :volumetries
Comment ça ? :thinking:

2024-10-24 10:30 UTC, JeSuisUnCaillou commented on config/locales/authorization_request_forms.fr.yml
> +      volumetrie:
haaan okaaay

2024-10-24 10:33 UTC, skelz0r commented on app/models/authorization_definition.rb
> +    :volumetries
il n'y a plus de clé `volumétries` dans la config yaml, cette clé est inutile

2024-10-24 11:31 UTC, JeSuisUnCaillou commented on app/models/authorization_definition.rb
> +    :volumetries
Ah oui j'ai compris ça y est. J'ai eu du mal x)

2024-10-24 14:47 UTC, skelz0r approved these changes

2024-10-24 15:47 UTC, merged