Feature/dat 604 gestion des scopes incompatibles entre eux
etalab/data_pass pull request #503
Opened 2024-10-24 08:58 UTC by Isalafont

2024-10-28 15:11 UTC, skelz0r requested changes
Globalement le code sur les scopes c'est OK, je request des changes pour tous les petits relicats de je ne sais pas quoi qui traîne qui n'ont pas lieu d'être dans cette PR: les `fill_attributes`, les `safety_certification_*`, la factory.

Y'a un peu de naming sur les 3 méthoes de validation aussi où c'est systématiquement `validate :validate_*` ce qui est redondant et peu explicite.

2024-10-28 15:11 UTC, skelz0r commented on app/models/authorization_request/api_impot_particulier.rb
> +  end
Le code est un poil complexe, et le nom un poil trop générique.

Ici ce qu'on test est que si `dgfip_annee_n_moins_2_si_indispo_n_moins_1` est sélectionné on ne peut pas sélectionner les 3 autres.

D'un point de vue code ceci me paraît plus simple à comprendre:

```ruby
return unless scopes.include?('dgfip_annee_n_moins_2_si_indispo_n_moins_1')
return unless scopes.intersect?(%w[dgfip_annee_n_moins_1 dgfip_annee_n_moins_2 dgfip_annee_n_moins_3])
```

après c'est kiff/kiff, imo si on fait un effort sur le nom ça sera peut-être mieux.

Il faudrait peut-être trouver un nom qui traduit la réalité de cette règle métier, j'arrive pas à mettre le doigt dessus mais si tu as ça serait cool.

Ce n'est pas très grave, c'est surtout de la réflexion.

Le seul point que j'aimerais qu'on corrige ici est de retirer le `validate_` dans le nom, donc si on garde l'existant ça ferait un truc du genre: `validate :years_scope_are_compatible`

2024-10-28 15:11 UTC, skelz0r commented on app/models/authorization_request/api_impot_particulier.rb
> +  def validate_incompatible_scopes
Bon là clairement c'est de la spec obscure, je n'ai aucune idée de si c'est valide ou non.. quelle est la justification métier de la DGFIP ici ? Parce que ça serait bien de le traduire dans le code (au même titre que la méthode du dessus).

Après ce n'est pas bloquant, juste techniquement il n'y a rien à dire, car il n'y a aucune justification métier donc on peut mettre n'importe quoi dedans :D

2024-10-28 15:11 UTC, skelz0r commented on spec/models/authorization_request/api_impot_particulier_spec.rb
> +    end
clairement ici tu peux simplifier en en testant 1 seul ça sera plus clair

2024-10-28 15:11 UTC, skelz0r commented on spec/models/authorization_request/api_impot_particulier_spec.rb
> +    end
je pense qu'ici c'est pareil, tu testes 1 cas évident, 1 cas complexe, 1 cas valide et pas besoin de plus imo

2024-10-28 15:11 UTC, skelz0r commented on features/habilitations/dgfip/api_impots_particuliers_editeur.feature
> +  Scénario: Je soumets une demande d'habilitation sans scopes d'années de revenue cochés.
Je me demande si ça ne serait pas plus clair, vu la complexité des règles des scopes, de faire carrément un fichier à part pour déporter tout ça ? Comme ça on refactor les N steps similaires dans le `Contexte`.

2024-10-28 15:11 UTC, skelz0r commented on app/models/authorization_request/api_impot_particulier.rb
> +  def validate_incompatible_scopes
Par contre j'aimerais avoir un meilleur nom que `validate :validate_*` => `validate :scopes_compatibility` ?

2024-10-28 15:17 UTC, skelz0r commented
> Le Front va être géré dans une autre PR

My 2cents là dessus: je pense que ça sera très compliqué de faire un front propre ici, surtout qu'en réalité en voyant les validations sur les scopes (tout du moins les 2 premiers, le 3e je ne le comprends pas), l'UI des checkbox est presque la pire façon de présenter ça à un usager, et imo on gagnerait à shipper ce qu'on a déjà d'un point de vue UX (même si c'est loin d'être idéal mais iso v1), faire la migration, et voir avec la DGFIP pour revoir toute cette logique de scope qui est assez tordu.

2024-10-28 15:22 UTC, Isalafont commented
Les safety_certification sont du au rebase avec develop que j'ai fait. Vu que l'on travaillait sur le même fichier spec et features, j'ai rebase avec develop pour gérer les conflicts.

2024-10-28 15:26 UTC, skelz0r commented on spec/factories/authorization_requests.rb
> -      with_cadre_juridique
ah oui en effet. ça aurait mérité un commit à part parce que là on ne comprend pas pourquoi

2024-10-28 15:34 UTC, Isalafont commented on app/models/authorization_request/api_impot_particulier.rb
> +  validate :validate_incompatible_scopes, if: -> { current_build_step == 'scopes' }
Pour une raison que je ne saurais expliquer, sans `if: -> { current_build_step == 'scopes' }`, nous nous trouvons bloqués par la validation à la création de la demande dès la première page car on nous demande de valider les scopes mais ceux ci se trouvent plusieurs steps plus loin. 
D'ailleurs si on retire cette partie la, en laissant cucumber sur le fichier, les tests s'arrêtent rapidement avec pour message d'erreur: 
`Capybara::ElementNotFound: Unable to find field "Destinataire des données" that is not disabled`

2024-10-28 15:36 UTC, skelz0r commented on app/models/authorization_request/api_impot_particulier.rb
> +  validate :validate_incompatible_scopes, if: -> { current_build_step == 'scopes' }
> Pour une raison que je ne saurais expliquer, sans `if: -> { current_build_step == 'scopes' }`, nous nous trouvons bloqués par la validation à la création de la demande dès la première page car on nous demande de valider les scopes mais ceux ci se trouvent plusieurs steps plus loin.

Ok donc c'est bien ce que je propose d'utiliser, le `->(record) { record.need_complete_validation?(:scopes) }` qui fait exactement ton test mais gère tous les edge cases liés au wizard/single page etc etc..

2024-10-28 15:38 UTC, skelz0r commented on app/models/authorization_request/api_impot_particulier.rb
> +  validate :validate_incompatible_scopes, if: -> { current_build_step == 'scopes' }
(et en fait la raison est simple: sur un wizard, il faut bien créer le modèle à la première étape, mais si tu mets des validations sur des fields plus loin il faut bien les ignorer sur les étapes précédentes).

C'est ce cas là https://github.com/zombocom/wicked/wiki/Building-Partial-Objects-Step-by-Step

2024-10-29 09:30 UTC, skelz0r commented on spec/models/authorization_request/api_impot_particulier_spec.rb
> +  let(:safety_certification_end_date) { nil }
Oui c'est évident vu que c'est référencé dans le subject, mais je ne comprends pas pourquoi ils sont ici dans le sens l'intérêt.

2024-10-30 09:29 UTC, Isalafont commented on app/models/authorization_request/api_impot_particulier.rb
> +  def validate_incompatible_scopes
A dire vrai, je sèche un peu sur comment renommer cette méthode d'incompatibilité de scopes.

Car on a 2 cas qui se distinguent, un premier array de scope on va dire "speciaux" concernant la demande d'année de revenue (cas ou on veut souhaite avoir l'Avant-dernière année de revenu, si la dernière année de revenu est indisponible et ou les Données fiscales au 31/12 en cas de décès d'un contribuable marié ou pacsé) 
et les scopes incompatibles qui peuvent être de la catégorie "agrégat fiscaux, revenus catégoriels déclarés ainsi que tous les scopes se trouvant dans la catégorie : revenus net, charges déductibles et éligibilité LEP)

2024-10-30 09:36 UTC, Isalafont commented on spec/models/authorization_request/api_impot_particulier_spec.rb
> +  let(:safety_certification_end_date) { nil }
Je les ai tous placé ici car j'ai besoin de les déclarer pour tous les tests à venir  en même temps que l'on appelle le subject.
ça m'évite de devoir rajouter les valeurs manquantes dans tous les tests.

2024-10-30 10:01 UTC, skelz0r commented on spec/models/authorization_request/api_impot_particulier_spec.rb
> +  let(:safety_certification_end_date) { nil }
Ok tu as tout remonté d'un test plus bas got it.

2024-10-30 10:02 UTC, skelz0r commented on app/models/authorization_request/api_impot_particulier.rb
> +  def validate_incompatible_scopes
Comme dit hier en réunion ce n'est pas grave, faudrait challenger/demander à la DGFIP comment ils nomment cette règle métier.

Tu peux juste renommer en `vallidate :scope_compatibility` (jarter le `validate_`)

2024-10-30 10:53 UTC, skelz0r requested changes
c'est du mega détail, dès que c'est green tu peux merge sans re-review

2024-10-30 10:53 UTC, skelz0r commented on app/models/authorization_request/api_impot_particulier.rb
> +
```suggestion
```

Ce n'est plus utilisé.

2024-10-30 10:53 UTC, skelz0r commented on spec/factories/authorization_requests.rb
> +          next if authorization_request.scopes.present?
imo tu peux revert ici (`present?` n'est pas assez permissif), surtout que ça ne touche plus du tout ta PR

```suggestion
          next if authorization_request.scopes.any?
```

2024-10-30 10:53 UTC, skelz0r commented on spec/factories/authorization_requests.rb
> +        authorization_request.scopes << 'dgfip_annee_n_moins_1' unless AuthorizationRequest::APIImpotParticulier::MANDATORY_REVENUE_YEARS.intersect?(authorization_request.scopes)
```suggestion
        authorization_request.scopes << 'dgfip_annee_n_moins_1'
```

le `unless` est tout le temps faux car scopes est systématiquement vide

2024-10-30 11:29 UTC, Isalafont commented on spec/factories/authorization_requests.rb
> +          next if authorization_request.scopes.present?
Ah non c'est bon, j'avais pas lu le bon bout de code !

2024-10-30 12:05 UTC, merged