Ajout des contact supplémentaires pour la dgfip
etalab/data_pass pull request #538
Opened 2024-11-14 17:27 UTC by jbfeldis

2024-11-15 13:45 UTC, skelz0r requested changes
pour moi les 2 commits sont à regrouper, j'aurais tout squash vu que c'est une feature du sdk drivé par la spec de la DGFIP

2024-11-15 13:45 UTC, skelz0r commented on app/helpers/authorization_request_forms_helper.rb
> +  def render_custom_form_or_default(authorization_request, partial, locals = {})
Pourquoi ne pas utiliser le même pattern que https://github.com/etalab/data_pass/blob/a611c336659925a023054c9e5652633c6f85fca7/app/views/authorization_requests/new.html.erb ? Je trouve ça plus clair, et c'est plus rails way, et ça a le mérite d'être directement dans la vue.

2024-11-15 13:45 UTC, skelz0r commented on app/views/authorization_request_forms/blocks/api_impot_particulier/_contact.html.erb
> +<% if local_assigns[:contact_type] %>
je vois ça je trouve ça brainfuck, mais en fait c'est dans le code initial, ça mériterait un refactor en utilisant directement `contacts` (dans un commit à part)

2024-11-15 13:45 UTC, skelz0r commented on app/views/authorization_request_forms/blocks/api_impot_particulier/_contact.html.erb
> +<div class="fr-col-12 fr-col-lg-6">
Je me dis qu'au lieu de tout ré-écrire `_contacts` on devrait utiliser la même approche de lookup sur `_contact` directement, voir même `_contact_#{kind}` en fait

2024-11-15 13:45 UTC, skelz0r commented on app/views/authorization_request_forms/build/basic_infos.html.erb
>  <%= authorization_request_form(@authorization_request) do |f| %>
Est-ce qu'on ne pourrait pas refactor ça dans le controller et flip toutes ces vues ? C'est un peu à part de cette PR en vrai mais c'est pas très DRY en réalité.

2024-11-15 13:45 UTC, skelz0r commented on app/views/authorization_requests/blocks/api_impot_particulier/_contacts.html.erb
> +            <% if contact_type == :contact_technique %>
même logique qu'en haut, je me dis qu'on pourrait faire un partial de `contact`, et laisser la possibilité de customiser la vue, voir même `contact_#{kind}`

2024-11-15 13:45 UTC, skelz0r commented on app/views/authorization_requests/blocks/api_impot_particulier/_contacts.html.erb
> +      <div class="fr-col-12 fr-col-lg-6">
Bon, en vrai ici on a besoin quand même d'override `contacts`.. 

je me dis aussi qu'on pourrait faire une partial de `contact_card` qui exploite du bloc pour faire DRY

2024-11-15 13:45 UTC, skelz0r commented on config/locales/activerecord.fr.yml
> +        contact_technique_extra_email: Adresse email générique
ce nom n'est pas assez précis, pourquoi ne pas mettre `Adresse email générique du contact technique` ?

2024-11-15 13:45 UTC, skelz0r commented on config/locales/activerecord.fr.yml
> +        extra_organization_contact_name: Nom de l'organisation
Je suis brainfuck par ce truc, de quoi on parle ici ? Cette info on l'a déjà. Je suis allé voir les maquettes et en effet c'est écrit ça mais c'est évidemment une typo.

Je mettrais ici d'ailleurs:

```suggestion
        extra_organization_contact_name: Nom du contact supplémentaire
```

le nom de l'attribut ne me parait clair btw

2024-11-15 13:45 UTC, skelz0r commented on config/locales/activerecord.fr.yml
> +        extra_organization_contact_email: Email du contact
```suggestion
        extra_organization_contact_email: Email du contact supplémentaire
```

2024-11-15 13:45 UTC, skelz0r commented on app/models/authorization_request/api_impot_particulier.rb
> +  add_attributes :extra_organization_contact_email, :extra_organization_contact_name, :contact_technique_extra_email
aucune validation ? sur l'email à minima le format imo

2024-11-25 14:02 UTC, skelz0r commented on app/helpers/authorization_request_forms_helper.rb
> +  def render_custom_form_or_default(authorization_request, partial, locals = {})
> c'est vrai que ce `lookup_context.exists?` est un peu moche mais si on peut éviter d'utiliser une exception comme condition c'est plutôt bien

Je suis justement pour utiliser une exception car c'est beaucoup plus explicite. Le pattern utilisé dans le fichier est à mon sens crystal clear -> on catch l'erreur du template qui n'existe pas et on render la vue.

Quelque soit le naming que tu vas utiliser je trouve qu'on ne peut pas faire plus clair que le `begin / render / rescue` qui est du PORO en 5 ligne.

2024-11-25 15:19 UTC, jbfeldis commented on app/helpers/authorization_request_forms_helper.rb
> +  def render_custom_form_or_default(authorization_request, partial, locals = {})
vendu pour gérer avec les exceptions par contre je suis toujours pas chaud de mettre ces 5 lignes _partout_ où on va faire ça 

surtout que si on veut appliquer le concept de manière plus poussée il va y en avoir pas mal, donc autant commencer à construire un petit sdk

2024-11-25 18:51 UTC, jbfeldis commented on config/locales/activerecord.fr.yml
> +        extra_organization_contact_name: Nom de l'organisation
peut-être plus directement "extra_contact_*" ou "additional_contact_*" ?

2024-11-25 19:52 UTC, skelz0r commented on config/locales/activerecord.fr.yml
> +        extra_organization_contact_name: Nom de l'organisation
C'est étrange le `extra` seul : extra de quoi ? ça me semble logique que ça soit lié à l'orga

2024-11-25 19:59 UTC, jbfeldis commented on config/locales/activerecord.fr.yml
> +        extra_organization_contact_name: Nom de l'organisation
est-ce qu'il manque un "pas" ou est-ce qu'il y a un "ne" en trop dans "le nom de l'attribut ne me parait clair btw" ? :smile:

2024-11-25 20:00 UTC, jbfeldis commented on config/locales/activerecord.fr.yml
> +        extra_organization_contact_name: Nom de l'organisation
mais ouais j'ai traduit "contact supplémentaire" assez littéralement, je suis toujours preneur d'un meilleur naming

2024-11-25 20:05 UTC, skelz0r commented on config/locales/activerecord.fr.yml
> +        extra_organization_contact_name: Nom de l'organisation
> est-ce qu'il manque un "pas" ou est-ce qu'il y a un "ne" en trop dans "le nom de l'attribut ne me parait clair btw" ? 😄

il manque un pas

2024-12-03 15:11 UTC, skelz0r commented
je veux bien que tu squash les commits qui ont du sens entre eux. à minima en 2 : la feature du sdk pour override, et le override effectif pour la DGFIP

2024-12-06 11:18 UTC, merged