Feature/dat 577 meta issue creation habillitation avec formulaires
etalab/data_pass pull request #539
Opened 2024-11-15 11:36 UTC by Samuelfaure

https://linear.app/pole-api/issue/DAT-577/[meta-issue]-creation-habillitation-avec-formulaires

Etapes 1 et 2

@SchweisguthN ou @evaspae si vous pouvez me faire les wordings...

2024-11-15 11:49 UTC, skelz0r requested changes
cf mes coms

2024-11-15 11:49 UTC, skelz0r commented on config/authorization_definitions.yml
> +    kind: 'api'
```suggestion
    kind: 'service'
```

2024-11-15 11:49 UTC, skelz0r commented on config/authorization_request_forms/france_connect.yml
> +france-connect-collectivite-administration:
tu as l'ensemble des infos de la clé `data` ici: https://github.com/betagouv/datapass/blob/master/frontend/src/pages/FranceConnect.tsx

ceci est valide pour tous les forms ci-dessous

2024-11-15 11:49 UTC, skelz0r commented on spec/factories/authorization_requests.rb
> +      with_scopes
```suggestion
      france_connect
```

idem en dessous.

2024-11-15 13:45 UTC, Samuelfaure commented on config/authorization_request_forms/france_connect.yml
> +france-connect-collectivite-administration:
Y'a pas énormément de contenu

2024-11-15 13:50 UTC, skelz0r requested changes
Manque toujours les données pré-remplies

2024-11-15 13:50 UTC, skelz0r commented on config/authorization_request_forms/france_connect.yml
> +france-connect-collectivite-epermis:
il manque encore les donnés pré-remplies

2024-11-15 13:50 UTC, skelz0r commented on config/authorization_definitions.yml
> +    kind: 'service'
c'est du détail mais tu n'as pas mis ce changement dans le bon commit imo (après tbh tu peux squash le bouzin)

2024-11-15 13:51 UTC, skelz0r commented
d'ailleurs les données pré-remplies peuvent jouer sur les étapes qu'on affiche ou non, je n'ai pas regardé mais c'est à analyser

2024-11-15 13:52 UTC, skelz0r commented
et je vois qu'ils ont tous des cadres juridiques, on peut donc les passer en bloc statiques et retirer l'étape imo

2024-11-15 13:52 UTC, skelz0r commented
faut creuser ici https://metabase.entreprise.api.gouv.fr/dashboard/50-datapass-exploration?nom_de_l%27api_(target_api)=franceconnect

2024-11-15 14:05 UTC, Samuelfaure commented on config/authorization_request_forms/france_connect.yml
> +france-connect-collectivite-epermis:
Erreur de compréhension de ma part de ta remarque précédente 👍

2024-11-18 16:00 UTC, Samuelfaure commented
@skelz0r Je suis encore un peu perdu dans ces histoires de formulaire, mais:

- J'ai ajouté les datas, il semble qu'il s'agisse uniquement d'un contact technique pour FC-epermis (+ le légal, mais cf point suivant)
- Pour le légal, j'ai tenté de supprimer ça mais ça bug; je propose de faire ce que tu proposes (supprimer l'étape et remplacer par bloc statique dans PR subséquente)

Je te propose de merge et itérer, WDYT?

2024-11-18 16:08 UTC, skelz0r commented
tbh t'aurasi pu juste ajouter les data pré-remplies pour être iso v1. 

le reste j'ai proposé au cas où des choses obvious sortait (du genre "il n'y a jamais eu de maquette sur les anciennes demandes", bah là on supprime).

Je fais l'effort de nettoyer les formulaires quand c'est évident, mais après tu peux kick en touche et demander à @SchweisguthN de gérer. 

Fondamentalement l'objectif de DataPass est de drastiquement simplifier les délivrances d'habilitations, donc on peut prendre chaque champs et dire "ca sert" -> oui/non. si c'est non on flip.

2024-11-18 16:10 UTC, skelz0r commented
Par contre je ne comprends pas pourquoi t'as importé qu'une partie des data de https://github.com/betagouv/datapass/blob/master/frontend/src/pages/FranceConnect.tsx#L84 ..? Il manque aussi un form d'ailleurs.

2024-11-18 16:25 UTC, skelz0r requested changes
Il manque encore des data (scopes, cadres légaux..)

2024-11-18 18:08 UTC, Samuelfaure commented
My bad again, j'ai pas vu qu'il y avait aussi les scopes dans les data préremplies!

Pour les cadres légaux pas la peine que je les ajoute, on va les flip pour un bloc statique non?

Par contre je vois pas quel form il manque? Je compte 4 scopes sur https://github.com/betagouv/datapass/blob/master/frontend/src/pages/FranceConnect.tsx#L84

2024-11-18 18:13 UTC, skelz0r commented
> Pour les cadres légaux pas la peine que je les ajoute, on va les flip pour un bloc statique non?

Tu confonds formulaire et demande d'habilitation ici : la demande doit avoir ces infos (on la veut sur la demande libre), il faut donc l'ajouter dans la clé `data` pour que ça soit rempli à la création, et si on le marque comme étant un bloc statique, il ne pourra pas être modifié.

> Par contre je vois pas quel form il manque?

En effet mybad

2024-11-19 10:16 UTC, Samuelfaure commented
OK cette fois c'est la bonne imo

2024-11-19 10:31 UTC, skelz0r commented
M-M-M-MERGE IT

2024-11-19 10:54 UTC, merged

2024-11-21 09:20 UTC, skelz0r commented
@evaspae j'ai reporté ici https://linear.app/pole-api/issue/DAT-701 (cette PR n'a pas du tout touché à cette partie)

2024-11-21 09:21 UTC, evaspae commented
> @evaspae j'ai reporté ici https://linear.app/pole-api/issue/DAT-701 (cette PR n'a pas du tout touché à cette partie)

My bad, merci !