Harden test factories
etalab/data_pass pull request #55
Opened 2024-01-15 15:32 UTC by Isalafont

2024-01-15 15:41 UTC, Isalafont commented
Je ne sais pas si c'est cela que tu attendais dans le fait de renforcer les tests de factories de AuthorizationRequest. 

Par contre j'ai une question, lorsque je créé des seeds, je ne peux plus créer dans ma console des formulaires car j'ai un conflit de validation avec des `users email et external_id` et `organization` déjà existants. C'est un peu dérengeant, je suis obligée de drop la db pour pouvoir executer une factory en console. 
Je ne vois pas comment résoudre ce conflit.

2024-01-15 16:37 UTC, skelz0r commented
> Par contre j'ai une question, lorsque je créé des seeds, je ne peux plus créer dans ma console des formulaires car j'ai un conflit de validation avec des `users email et external_id` et `organization` déjà existants. C'est un peu dérengeant, je suis obligée de drop la db pour pouvoir executer une factory en console.
> Je ne vois pas comment résoudre ce conflit.

Tu ne peux pas résoudre ce conflit, ce n'est pas vraiment fait pour ça, les séquences sont réinitialisé à chaque lancement de rails.

2024-01-15 16:41 UTC, skelz0r requested changes
cf mes coms

2024-01-15 16:41 UTC, skelz0r commented on spec/factories/authorization_requests.rb
> +    trait :api_entreprise do
c'est strictement identique au `common`.

2024-01-15 16:41 UTC, skelz0r commented on spec/models/authorization_request_spec.rb
> +  %w[hubee_cert_dc
Ce que j'attendais était ça:

> Pour chaque formulaire disponible, vérifier que la factory associée est valide en state draft et en state submit.

Globalement ce qui manquait sur l'ancien test, c'était le "chaque formulaire disponible", ce que tu ne résoud pas ici car si on ajoute un formulaire, ça ne répond plus à la problématique.

2024-01-15 16:41 UTC, skelz0r commented on spec/factories/authorization_requests.rb
> +    trait :api_entreprise do
Tu peux mettre les `_common` dans le formulaire principal, et override les autres en référençant le principal. Cela a l'avantage de ne pas avoir des traits orphelins (et potentiellement invalides)

2024-01-16 11:21 UTC, skelz0r requested changes
Cf mes 2 coms (on y est presque)

2024-01-16 11:21 UTC, skelz0r commented on spec/models/authorization_request_spec.rb
> +  form_uids.each do |form_uid|
Ici tu peux utiliser le modèle `AuthorizationRequestForm.all` ça sera plus simple.
D'ailleurs sans utiliser `YAML` tu aurais pu faire `Rails.application.config_for(:authorization_request_forms)` comme dans le modèle.

2024-01-16 11:21 UTC, skelz0r commented on spec/models/authorization_request_spec.rb
> +      end
En théorie c'est mieux de faire N tests comme tu l'as fait, mais en pratique c'est très gourmand de taper en db, d'où le fait que j'avais initialement fait un seul `it` (i.e. test case) pour justement optimiser tout ça.

Je te suggère de revert à ce que j'avais fait histoire de garder ça performant.

2024-01-16 11:21 UTC, skelz0r commented
Les factories sont bonnes en tout cas.

2024-01-16 11:28 UTC, Isalafont commented on spec/models/authorization_request_spec.rb
> +  form_uids.each do |form_uid|
3 façons de faire différente :) Je vais me les noter dans Obsidian, histoire de ne pas oublier que ces 3 façons fassent bien la même chose et de ne pas les oublier surtout 👍🏻

2024-01-16 11:34 UTC, skelz0r commented on spec/models/authorization_request_spec.rb
> +  form_uids.each do |form_uid|
Ta façon c'est du ruby pur, la 2e c'est pratique pour sortir des configurations, mais là la meilleure est d'utiliser directement le modèle qui existent et ainsi abstraire cette complexité. Si demain on décide de changer la structure de donnée les tests ne casseront pas..

2024-01-16 11:55 UTC, Isalafont commented on spec/models/authorization_request_spec.rb
> +  form_uids.each do |form_uid|
Ah zut, dans ma nouvelle version, j'ai opté pour Rails.application.config_for(:authorization_request_forms) 🫣

2024-01-16 11:57 UTC, skelz0r commented on spec/models/authorization_request_spec.rb
> +  form_uids.each do |form_uid|
La complexité du traitement a déjà été géré, ça ne sert à rien de la recoder.

2024-01-16 13:55 UTC, Isalafont commented
J'ai une question. Pour les tests cucumber, on a un helper qui récupère les noms des traits des factories via le fichier `AuthorizationDefinition` ce qui fonctionne pour toutes les apis SAUF pour le service `Hubee cert dc`. C'est le seul cas ou la key de l'api, ne correspond pas au nom du form de AuthorizationRequestForm (par lesquels sont récupérés les noms des traits de factory  
=> `hubee_cert_dc` contre `portail_hubee_demarche_certdc`. 

y a t'il une volonté d'avoir une key différente pour le même service (HubEE) entre les fichiers de config `authorization_request_forms.yml` et `authorization_definitions.yml`?

2024-01-16 13:57 UTC, skelz0r commented
Rename le formulaire c'est pas important (et c'est le plus simple).

2024-01-16 14:05 UTC, Isalafont commented
Je suis en train de regarder mais je ne suis pas certaine que ça soit le plus simple, maintenant j'ai plusieurs tests cucumber qui failed... 
je commence à comprendre pourquoi il y avait 2 traits pour ce service...

2024-01-17 15:01 UTC, merged