Bloc for modalites
etalab/data_pass pull request #563
Opened 2024-11-27 11:44 UTC by JeSuisUnCaillou

Closes https://linear.app/pole-api/issue/DAT-709/bloc-de-modalite-dacces-dans-le-formulaire

2024-11-29 13:09 UTC, skelz0r commented on app/helpers/authorization_requests_helpers.rb
> +  def hidden_modalities_params?
Je suis un peu gêné par cet approche car c'est spécifique aux demandes avec des modalités.

Je proposerai plutôt de faire ceci par convention: on passe des get params en mode `attributes= { modalities:, france_connect_authorization_id: }` et on loop dans la vue `_form` de la manière suivante:

```
params[:attributes].each do |key, value|
  <%= render hidden_field key, value: value %>
end
```

Sur l'arbre de décision:

```
start_authorization_request_form(form, disabled: false, { modalities: AuthorizationRequest::APIImpotParticulier::MODALITIES, france_connect_authorization_id: })
```

ça me semblerait plus KISS

2024-11-29 13:10 UTC, skelz0r commented on app/helpers/authorization_requests_helpers.rb
> +  def hidden_modalities_params?
Et du coup la méthode

```ruby
  def start_authorization_request_form(form, disabled: false, attributes: nil)
    text = t('start_authorization_request_form.cta', authorization_name: form.authorization_definition.name)
    css_classes = %w[fr-btn fr-icon-save-line fr-btn--icon-left]

    if disabled
      button_tag(text, class: css_classes, disabled: true, id: dom_id(form, :start_authorization_request))
    else
      link_to(text, start_authorization_request_forms_path({form_uid: form.id, params: attributes}.compact), class: css_classes, id: dom_id(form, :start_authorization_request))
    end
  end

2024-11-29 13:17 UTC, JeSuisUnCaillou commented on app/helpers/authorization_requests_helpers.rb
> +  def hidden_modalities_params?
faut quand même que j'en permit une liste définie

2024-11-29 13:18 UTC, skelz0r commented on app/views/authorization_request_forms/shared/_hidden_modalities_fields.html.erb
> +<%= f.text_field :france_connect_authorization_id, value: modalities_params[:france_connect_authorization_id], class: 'fr-hidden' %>
c'est moche le `text_field` en fr-hidden alors que bon.. `hidden_field` hein :D

2024-11-29 13:36 UTC, JeSuisUnCaillou commented on app/helpers/authorization_requests_helpers.rb
> +  def hidden_modalities_params?
Done

2024-11-29 13:46 UTC, JeSuisUnCaillou commented on app/models/concerns/authorization_extensions/modalities.rb
> +    add_attributes :france_connect_authorization_id
tu parles de juste `:france_connect_authorization_id` ?

2024-11-29 15:05 UTC, JeSuisUnCaillou commented on app/models/concerns/authorization_extensions/modalities.rb
> +    add_attributes :france_connect_authorization_id
Oui.

2024-11-29 15:06 UTC, JeSuisUnCaillou commented on app/models/concerns/authorization_extensions/modalities.rb
> +  end
On va rester spécifique tant que c'est spécifique je pense

2024-11-29 15:23 UTC, JeSuisUnCaillou commented
Est-ce qu'on veut valider l'existence de l'authorization france connect linkée ?

2024-11-29 16:34 UTC, JeSuisUnCaillou commented on app/models/concerns/authorization_extensions/modalities.rb
> +module AuthorizationExtensions::Modalities
API particulier l'utilise comme un array, alors que api impot part l'utilise comme une string.

Par soucis d'en avoir complètement marre de me casser le cul, je propose qu'on refactor pas.

2024-12-02 08:31 UTC, skelz0r commented on app/models/concerns/authorization_extensions/modalities.rb
> +module AuthorizationExtensions::Modalities
Soit (I.) on refactor en 1 seul module, et on applique, au choix:

1. API Impot part on transforme le `modalities` en un vrai array (et on passe des options pour customiser la vue en mode "1 choix ou plusieurs")
2. On override dans API Impot Part (car on inclut `modalities` qui implique du pluriel, donc c'est dans la classe où on fait du singulier qu'on doit override). Cela implique d'override la vue aussi (sujet que JB tacle dans sa PR)

Soit (II.) on split en 2 modules : `Modalities` (pluriel), `Modality` (singulier) et on duplique le taff

Je ferai I.1. si techniquement ce n'est pas trop compliqué à comprendre, sinon II. (qui est moins dry, mais plus no-brainer)

2024-12-02 13:45 UTC, JeSuisUnCaillou commented on app/models/concerns/authorization_extensions/modalities.rb
> +module AuthorizationExtensions::Modalities
Bon alors comme va y avoir d'autres forms avec une liste de valeurs possibles (des checkboxes au lieu de radioboutons) va falloir changer mon code pour dtf autoriser un array dans modalities, même pour la dgfip. Donc FLBLBLBL j'avais même pas besoin d'autant m'emmerder avec les radioboutons tout ce temps.

2024-12-02 14:34 UTC, JeSuisUnCaillou commented
Est-ce qu'on peut merge ça comme ça, et que je bosse sur la version avec checkboxes et array dans une autre PR ? @skelz0r

2024-12-03 10:54 UTC, skelz0r requested changes
a minima fixer/harden pour ne pas permettre de mettre whatever ce qu'on veut en attributs quand le modèle est persisté.

2024-12-03 10:54 UTC, skelz0r commented on app/views/authorization_request_forms/_form.html.erb
> +  <%= render partial: "authorization_request_forms/shared/hidden_attributes", locals: { f: f } %>
C'est pas assez safe ici, je ferai une restriction à minima sur le fait que le modèle n'est pas persisté.

2024-12-03 10:54 UTC, skelz0r commented on app/models/concerns/authorization_extensions/modalities.rb
> +module AuthorizationExtensions::Modalities
Du coup tout ça tu le mets dans le APIImpotParticulier direct ? (ou son concern), pour éviter que ça soit brainfuck avec API Particulier ?

2024-12-03 10:54 UTC, skelz0r commented on app/helpers/authorization_requests_helpers.rb
> +
peu fan de ce nom, et cf mon com dans la vue en vrai je pense que tu peux harden ici avec un truc du genre:

```suggestion
  def new_authorization_request_default_params(authorization_request)
    return {} if authorization_request.persisted?
    
    params[:attributes]
  end

```

2024-12-03 10:54 UTC, skelz0r commented on app/views/authorization_request_forms/shared/_hidden_attributes.html.erb
> +<% end %>
cette complexité de if est à mettre dans le helper (cf ma reco en faisant un return `{}`)

```suggestion
  <% hidden_attributes[:attributes].each do |key, value| %>
    <%= f.hidden_field key, value: %>
  <% end %>
```

2024-12-03 12:38 UTC, JeSuisUnCaillou commented on app/views/authorization_request_forms/_form.html.erb
> +  <%= render partial: "authorization_request_forms/shared/hidden_attributes", locals: { f: f } %>
Why not, mais pourquoi ? Je vois pas bien ce qu'on risque

2024-12-03 12:45 UTC, JeSuisUnCaillou commented on app/helpers/authorization_requests_helpers.rb
> +
si je permit! pas, rails lâche une erreur. Mais je vois l'idée

2024-12-03 13:05 UTC, JeSuisUnCaillou commented
> Du coup tout ça tu le mets dans le APIImpotParticulier direct ? (ou son concern), pour éviter que ça soit brainfuck avec API Particulier ?

J'ai pas vraiment compris la question.

Je compte utiliser `AuthorizationExtensions::Modalities` dans api particulier, c'est pour ça que je l'ai séparé de `DGFIPExtensions::APIImpotParticulierModalities` dans cette PR

2024-12-03 13:25 UTC, JeSuisUnCaillou commented on app/models/concerns/authorization_extensions/modalities.rb
> +module AuthorizationExtensions::Modalities
Je compte importer `AuthorizationExtensions::Modalities` dans api particulier ainsi que dans `DGFIPExtensions::APIImpotParticulierModalities` qui l'étend pour rajouter le champ `france_connect_authorization_id`

2024-12-03 14:47 UTC, skelz0r commented
@JeSuisUnCaillou petit conflit faut rebase

2024-12-03 14:49 UTC, skelz0r commented on app/views/authorization_request_forms/_form.html.erb
> +  <%= render partial: "authorization_request_forms/shared/hidden_attributes", locals: { f: f } %>
J'allais argumenter mais en vrai la liste est aussi dynamique côté serveur donc flip it

2024-12-03 14:51 UTC, skelz0r commented on app/models/concerns/authorization_extensions/modalities.rb
> +module AuthorizationExtensions::Modalities
je sais, mais là c'est brainfuck d'où ma question

2024-12-03 14:53 UTC, skelz0r commented on app/views/authorization_request_forms/shared/_hidden_params.html.erb
> +<% new_authorization_request_hidden_params[:attributes].each do |key, value| %>
c'est cheum comme interface, j'aurais juste fait `new_authorization_request_hidden_params` au lieu de `new_authorization_request_hidden_params[:attributes]`

2024-12-03 14:54 UTC, skelz0r requested changes
c/c le code du module `Modalities` dans le code de concern de la DGFIP parce que c'est brainfuck d'avoir un module à part qui a le cul entre 2 chaises.

y'a le `new_authorization_request_hidden_params` aussi

2024-12-05 08:34 UTC, JeSuisUnCaillou commented on app/views/authorization_request_forms/shared/_hidden_params.html.erb
> +<% new_authorization_request_hidden_params[:attributes].each do |key, value| %>
J'ai besoin d'avoir la clef `attributes` [ici](https://github.com/etalab/data_pass/blob/bloc_for_modalites/app/helpers/authorization_requests_helpers.rb/#L17), du coup c'est un tradeoff : soit je répète la clef `:attributes` dans `start_authorization_request_form`, soit je la répète dans `_hidden_params.html.erb`.

IMO c'est kiff kiff.

2024-12-05 08:36 UTC, JeSuisUnCaillou commented
> c/c le code du module `Modalities` dans le code de concern de la DGFIP parce que c'est brainfuck d'avoir un module à part qui a le cul entre 2 chaises.

J'ai split les 2 dans l'optique de pouvoir include `Modalities` directement dans api particulier, donc je peux les fusionner mais ça sera pour les re-split juste derrière, je vois pas bien l'intérêt

2024-12-05 08:59 UTC, Isalafont commented
J'ai commencé a regarder le code et j'avoue que j'ai besoin d'un peu plus de temps pour tout bien comprendre. 
Mais j'ai une question, que fais t'on de la première page du formulaire ? 
<img width="1140" alt="Capture d’écran 2024-12-05 à 09 57 38" src="https://github.com/user-attachments/assets/35aaa247-f276-41d5-96e2-4c80b8e2e3cc">

Avec l'implémentation du nouveau bloc de modalité, on en aura plus besoin et surtout l'utilisateur ne comprendra pas pourquoi on lui repose exactement la même question au début non ?

2024-12-05 09:17 UTC, Isalafont commented on app/models/concerns/authorization_extensions/modalities.rb
> +module AuthorizationExtensions::Modalities
Je viens participer à la conversation (un peu tarfivement), si on part du principe que dans les prochains formulaire DGFiP, on aura d'autres `access_mode` aka `modalité d'acces` à integrer, je confirme que l'on aura bien besoin d'autoriser un Array dans modalities (Voir avec les 9 access mode pour l'API Ficoba qui va être mis en prod sur la V1)

2024-12-05 09:55 UTC, JeSuisUnCaillou commented
> Si on clique france_connect mais que l'on change et clique sur spi, l'habilitation France connect est quand même liée à l'authorization request en back.

Normalement non, j'ai fait gaffe à bien vider le paramètre dans le js. J'arrive pas à reproduire ce que tu dis :thinking:

2024-12-05 13:12 UTC, Isalafont commented
> Normalement non, j'ai fait gaffe à bien vider le paramètre dans le js. J'arrive pas à reproduire ce que tu dis 🤔

Je t'ai induite en erreur sur comment le reproduire, en fait j'avais selectionné france connect sur la premiere page de modalité d'accès et puis j'ai fait le parcours et la j'ai re eut à nouveau un bloc de modalité à selectionner et la j'ai cliqué sur sfip et non France connect comme déjà préselectionné. 

Résultat en backend d'enregistrer, j'ai la modalité with_sfip avec une habilitation France connect attaché. 

C'est tricky je sais, mais ne sous estimons pas les utilisateurs pour reproduire ce cas 😅

2024-12-05 13:42 UTC, skelz0r commented
> > Normalement non, j'ai fait gaffe à bien vider le paramètre dans le js. J'arrive pas à reproduire ce que tu dis 🤔
> 
> Je t'ai induite en erreur sur comment le reproduire, en fait j'avais selectionné france connect sur la premiere page de modalité d'accès et puis j'ai fait le parcours et la j'ai re eut à nouveau un bloc de modalité à selectionner et la j'ai cliqué sur sfip et non France connect comme déjà préselectionné.
> 
> Résultat en backend en enregistré, j'ai la modalité `with_sfip` avec une habilitation France connect attaché.
> 
> C'est tricky je sais, mais ne sous estimons pas les utilisateurs pour reproduire ce cas 😅

Pour le coup c'est une question d'intégrité de la donnée, ce qui est critique. Bien vu !

2024-12-05 13:52 UTC, merged

2024-12-05 15:37 UTC, JeSuisUnCaillou commented on app/models/concerns/authorization_extensions/modalities.rb
> +module AuthorizationExtensions::Modalities
Yes je vais m'en occuper dans une PR de followup