make the model an array
etalab/data_pass pull request #582
Opened 2024-12-05 17:32 UTC by JeSuisUnCaillou

Closes https://linear.app/pole-api/issue/DAT-725/on-peut-selectionner-plusieurs-modalites-dacces

2024-12-06 11:07 UTC, JeSuisUnCaillou commented
Comment je suis bien content d'avoir écrit autant de tests lors de la précédente PR ! J'aurais zappé mille trucs sinon là :o

2024-12-06 11:40 UTC, skelz0r commented
@JeSuisUnCaillou sérouge et en conflit

2024-12-06 11:43 UTC, JeSuisUnCaillou commented
> @JeSuisUnCaillou sérouge et en conflit

séparouj, c'est le flaky.
-> Je m'occupe de rebase

2024-12-06 11:44 UTC, JeSuisUnCaillou commented
Bizarre j'ai pas eu de conflits à résoudre quand j'ai rebase en local :thinking:

2024-12-06 11:45 UTC, JeSuisUnCaillou commented
-> Y'a probablement des commits à regrouper ensemble dans le tas aussi

2024-12-06 11:52 UTC, skelz0r requested changes
quelques broutilles

2024-12-06 11:52 UTC, skelz0r commented on app/form_builders/dsfr_form_builder.rb
> +    opts[:checked] = opts[:checked_proc].call(value) if opts[:checked_proc].is_a? Proc
Limite je serai partisan d'appeler cette clé `checked` directement, histoire de surcharger la logique (limite ça pourrait faire une PR pour rails)

2024-12-06 11:52 UTC, skelz0r commented on app/javascript/controllers/choose_modalite_impot_particulier_controller.js
> +    this.addToLinks({ 'attributes[modalities][]': modalityValue })
on adore ce genre de subtilités 😅

2024-12-06 11:52 UTC, skelz0r commented on app/models/concerns/authorization_core/attributes.rb
> +          raise(TypeError, "#{name} should be an array") unless value.is_a?(Array) || value.nil?
```suggestion
          raise(TypeError, "#{name} should be an array") unless value.is_a?(Array)
```

non ?

2024-12-06 11:52 UTC, skelz0r commented on app/views/authorization_request_forms/blocks/default/_modalities.html.erb
> +    <%= @authorization_request.modalities %>
un oubli ?

2024-12-06 11:52 UTC, skelz0r commented on app/models/concerns/authorization_core/attributes.rb
> +          raise(TypeError, "#{name} should be an array") unless value.is_a?(Array) || value.nil?
en fait je me dis qu'on pourrait forcer avec `Array(value)`

```
3.3.6 (main):0 > Array('test')
=> ["test"]
3.3.6 (main):0 > Array(['test'])
=> ["test"]
```

je ne sais pas si c'est le comportement d'ActiveRecord sur un type array, faudrait coller pour que ça soit logique/consistent.

2024-12-06 12:52 UTC, JeSuisUnCaillou commented on app/form_builders/dsfr_form_builder.rb
> +    opts[:checked] = opts[:checked_proc].call(value) if opts[:checked_proc].is_a? Proc
J'avais appelé ça `checked` au début, et du coup ça faisait chier par ce que ça me faisait remplacer le pointeur vers le proc quand je calculais le résultat du proc et que je le stockait dans `opts[:checked]`, ce qui niquait les checkboxes suivantes

2024-12-06 12:54 UTC, skelz0r commented on app/form_builders/dsfr_form_builder.rb
> +    opts[:checked] = opts[:checked_proc].call(value) if opts[:checked_proc].is_a? Proc
Je ne suis pas sûr de comprendre le problème. Ceci ne fonctionne pas ? 

```ruby
opts[:checked] = opts[:checked].is_a?(Proc) ? opts[:checked].call(value) : opts[:checked]
```

2024-12-06 14:27 UTC, JeSuisUnCaillou commented on app/form_builders/dsfr_form_builder.rb
> +    opts[:checked] = opts[:checked_proc].call(value) if opts[:checked_proc].is_a? Proc
Ouais. ça remplace le proc et ça tente de mettre checked=true sur toutes les options si al première est true.

2024-12-06 14:35 UTC, skelz0r commented on app/models/concerns/authorization_core/attributes.rb
> +          raise(TypeError, "#{name} should be an array") unless value.is_a?(Array) || value.nil?
Seems legit. Après mon commentaire suivant propose de suivre Rails donc imo ça annule et remplace.

2024-12-06 14:35 UTC, JeSuisUnCaillou commented on app/form_builders/dsfr_form_builder.rb
> +    opts[:checked] = opts[:checked_proc].call(value) if opts[:checked_proc].is_a? Proc
ça change rien. Attend je reteste, mais je suis 90% sûr que ça nique le pointeur du proc de faire ça.

2024-12-06 14:43 UTC, JeSuisUnCaillou commented on app/form_builders/dsfr_form_builder.rb
> +    opts[:checked] = opts[:checked_proc].call(value) if opts[:checked_proc].is_a? Proc
Je confirme, ça fout la merde.

En gros, ma compréhension c'est que : 

- `opts[:checked]` est un pointeur vers le Proc, par ce qu'on est dans un hash
- `opts[:checked] = nimportequoi` remplace la valeur qu'il y a derrière le pointeur, sans changer le pointeur
- dès le premier appel de `opts[:checked] = nimportequoi` on perd le pointeur, et il est remplacé par le premier résultat que le proc a calculé, et donc on ne rentre plus jamais dans le `if opts[:checked].is_a?(Proc)`

Je suis 99,9% sûr maintenant que j'ai retesté

2024-12-06 15:02 UTC, JeSuisUnCaillou commented on app/form_builders/dsfr_form_builder.rb
> +    opts[:checked] = opts[:checked_proc].call(value) if opts[:checked_proc].is_a? Proc
Soluce : `opts.dup` dans `dsfr_radio_buttons`

2024-12-06 15:02 UTC, JeSuisUnCaillou commented on app/models/concerns/authorization_core/attributes.rb
> +          raise(TypeError, "#{name} should be an array") unless value.is_a?(Array) || value.nil?
Qu'est-ce qui annulle et remplace quoi ? :thinking: 
sépaklair

2024-12-06 15:04 UTC, skelz0r commented on app/models/concerns/authorization_core/attributes.rb
> +          raise(TypeError, "#{name} should be an array") unless value.is_a?(Array) || value.nil?
Je propose de suivre la convention rails, qui imo cast en array, à vérifier.

2024-12-09 09:01 UTC, JeSuisUnCaillou commented on app/models/concerns/authorization_core/attributes.rb
> +          raise(TypeError, "#{name} should be an array") unless value.is_a?(Array) || value.nil?
Du coup je raise plus d'erreur ? Juste je cast en array et j'envoie comme ça ?

2024-12-09 11:08 UTC, JeSuisUnCaillou commented on app/models/concerns/authorization_core/attributes.rb
> +          raise(TypeError, "#{name} should be an array") unless value.is_a?(Array) || value.nil?
ActiveRecord il raise pas d'erreur, il caste rien, il fait juste rien quand je lui passeu nnon-array :D

![image](https://github.com/user-attachments/assets/bc42aa25-3963-4e71-9d4f-704d60d69ea9)
![image](https://github.com/user-attachments/assets/469c5bd8-7ce6-42c3-a6b1-7738c0e5bda2)

2024-12-09 11:09 UTC, JeSuisUnCaillou commented on app/models/concerns/authorization_core/attributes.rb
> +          raise(TypeError, "#{name} should be an array") unless value.is_a?(Array) || value.nil?
What ... Il caste un booléen en string par contre

![image](https://github.com/user-attachments/assets/fad48c27-ff72-4329-9dfc-c6cd706cee4b)

2024-12-09 11:10 UTC, JeSuisUnCaillou commented on app/models/concerns/authorization_core/attributes.rb
> +          raise(TypeError, "#{name} should be an array") unless value.is_a?(Array) || value.nil?
ça me paraît pas solide comme comportement, j'ai pas envie de reproduire ça. Je préfère mon raise.

2024-12-09 11:50 UTC, Samuelfaure commented on app/form_builders/dsfr_form_builder.rb
> +    opts[:checked] = opts[:checked].call(value) if opts[:checked].is_a? Proc
C'est quoi les cas où il s'agit d'un Proc VS les cas où il ne s'agit pas?

2024-12-09 13:20 UTC, JeSuisUnCaillou commented on app/form_builders/dsfr_form_builder.rb
> +    opts[:checked] = opts[:checked].call(value) if opts[:checked].is_a? Proc
Je vais chercher par convention les labels du fichier `config/locales/authorization_request_forms.fr.yml`, comme le font les autres champs de formulaire.

2024-12-09 13:21 UTC, skelz0r commented on app/models/concerns/authorization_core/attributes.rb
> +          raise(TypeError, "#{name} should be an array") unless value.is_a?(Array) || value.nil?
Ok, si c'est non-consistant ou qu'il y a des comportements chelou avec le reste du framework on avisera.

2024-12-09 13:21 UTC, JeSuisUnCaillou commented on app/form_builders/dsfr_form_builder.rb
> +    opts[:checked] = opts[:checked].call(value) if opts[:checked].is_a? Proc
Ah pardon j'ai répondu à côté de la question.

J'ai eu besoin de passer un proc pour savoir si la valeur était checked, par ce que la variable du model que je remplis avec ces radio boutons, c'est un array de valeurs.

On pourrait défendre l'avis que dans ce cas faut plutôt mettre des checkboxes.

2024-12-09 15:18 UTC, JeSuisUnCaillou commented
> Je vais un petit peu casser l'ambiance... mais j'ai une erreur en local lorsque j'essaie de valider les contacts.
> 
> `@authorization_request.associated_france_connect_authorization.full_name`
> 
> ```
> NoMethodError in AuthorizationRequestForms#summary
> Showing /Users/isalafont/code/BetaGouv/Etalab/data_pass/app/views/authorization_requests/shared/blocks/_summary_block.html.erb where line #24 raised:
> 
> undefined method `full_name' for an instance of Authorization
> ```
> 
> Je pense que c'est lié au contact supplémentaire rajouté.

C'est corrigé et testé, bien vu merci :+1:

2024-12-09 15:23 UTC, JeSuisUnCaillou commented on app/form_builders/dsfr_form_builder.rb
> +    opts[:checked] = opts[:checked].call(value) if opts[:checked].is_a? Proc
Done

2024-12-09 15:29 UTC, skelz0r approved these changes
cf me 2 suggestions que tu peux commit en scout commit (ou pas)

2024-12-09 15:29 UTC, skelz0r commented on features/habilitations/dgfip/api_impot_particulier/editeur_modalites.feature
> +    Et que Cette dernière demande d'habilitation s'appelait "Demande d'accès à france connect pour mon appli"
```suggestion
    Et que cette dernière demande d'habilitation s'appelait "Demande d'accès à france connect pour mon appli"
```

2024-12-09 15:29 UTC, skelz0r commented on features/step_definitions/authorization_requests_steps.rb
> +Quand("Cette dernière demande d'habilitation s'appelait {string}") do |intitule|
```suggestion
Quand("cette dernière demande d'habilitation s'appelait {string}") do |intitule|
```

quezac

2024-12-09 15:32 UTC, JeSuisUnCaillou commented on features/habilitations/dgfip/api_impot_particulier/editeur_modalites.feature
> +    Et que Cette dernière demande d'habilitation s'appelait "Demande d'accès à france connect pour mon appli"
bien vu

2024-12-09 15:50 UTC, merged