Export DGFIP authorization requests
etalab/data_pass pull request #591
Opened 2024-12-09 11:49 UTC by skelz0r

2024-12-10 15:34 UTC, skelz0r commented
Bon en vrai je ne sais pas trop ce qui est intéressant à relire.. parce que ici ça sera surtout de la méga itération au moment où on va faire la migration 🤷

2024-12-12 16:10 UTC, Samuelfaure approved these changes
quelques chipotages mais good

2024-12-12 16:10 UTC, Samuelfaure commented on app/services/dgfip_spreadsheet_generator.rb
> +        with_spi: 'acces_spi',
j'aurais pas utilisé l'acronyme `spi` mais mis un truc plus verbeux, mais je chipote

2024-12-12 16:10 UTC, Samuelfaure commented on spec/services/dgfip_spreadsheet_generator_spec.rb
> +      # FileUtils.cp(file.path, 'tmp/dgfip_spreadsheet.xlsx')
oopsie

2024-12-12 16:10 UTC, Samuelfaure commented on spec/services/dgfip_spreadsheet_generator_spec.rb
> +        leagcy_data.each do |key, value|
```suggestion
      subject(:legacy_data) do
        sheet_as_csv.to_a[1].to_h
      end

      it 'has valid data' do
        initial_data = JSON.parse(File.read('spec/fixtures/api_impot_particulier_v1_attributes.json'))

        legacy_data.each do |key, value|
```

2024-12-12 16:10 UTC, Samuelfaure commented on spec/services/dgfip_spreadsheet_generator_spec.rb
> +        leagcy_data.each do |key, value|
nevermind ya un commit plus tard

2024-12-12 17:53 UTC, skelz0r commented on app/services/dgfip_spreadsheet_generator.rb
> +        with_spi: 'acces_spi',
en effet, c'est un acronyme métier

2024-12-13 08:41 UTC, skelz0r commented on spec/services/dgfip_spreadsheet_generator_spec.rb
> +      # FileUtils.cp(file.path, 'tmp/dgfip_spreadsheet.xlsx')
j'ai laissé ça pour le debug, tbh c'est du code qui va être jeté donc bon..

2024-12-13 08:43 UTC, skelz0r commented
Faudra coupler ça avec l'import/migration et comparer side by side entre l'export v1 et v2 pour être "sûr" et ajuster en fonction. Le but étant d'avoir 2 spreadsheet "identique" (j'ai omis des colonnes de la v1 qui ne sont pas exploités par le script python)

2024-12-13 09:26 UTC, JeSuisUnCaillou reviewed
Juste quelques retours déjà, avant de plonger dans le code :point_down: 

- Y'a pas encore le bouton d'export dans l'interface exprès ?
- Y'a sûrement des opti à faire sur les requêtes effectuées, par ce que j'en compte 18 par authorization là
- Je ne reçoit pas le fichier, et j'ai une erreur cheloue dans mon serveur quand je tente d'acccéder à `http://localhost:3000/dgfip/export` depuis mon navigateur, en tant que `datapass@yopmail.com` : 

![Screenshot from 2024-12-13 10-24-47](https://github.com/user-attachments/assets/83b78488-ccf2-4152-aae1-4c1fc67101ac)

2024-12-13 10:21 UTC, JeSuisUnCaillou approved these changes
Globalement ok, dtf faudra itérer comme tu l'as dit.

2024-12-13 10:23 UTC, skelz0r commented on spec/services/dgfip_spreadsheet_generator_spec.rb
> +        legacy_data.each do |key, value|
oui bon hein :D je vais rebase

2024-12-13 10:27 UTC, skelz0r commented on app/services/dgfip_spreadsheet_generator.rb
> +      authorization_request.definition.stage.exists? ? authorization_request.latest_authorization&.request_as_validated&.id : nil,
je sais plus ce que c'est, et en recreusant le code je tombe là : https://github.com/betagouv/datapass/blob/master/backend/app/models/enrollment.rb#L585
(c'est drôle, ça n'a pas de sens :'))

2024-12-13 10:33 UTC, skelz0r commented on app/controllers/dgfip/export_controller.rb
> +  end
J'ai flemmé de faire ça proprement dans `DataProvider` (parce que c'est là qu'on devrait le mettre imo) (y'avait un peu de code à faire).

je vais le faire aller

2024-12-13 10:36 UTC, skelz0r commented on app/services/dgfip_spreadsheet_generator.rb
> +      authorization_request.definition.stage.exists? ? authorization_request.latest_authorization&.request_as_validated&.id : nil,
ici c'est une FC https://datapass.api.gouv.fr/api-impot-particulier-sandbox/64471 (qui n'apparaît pas sur l'UI d'ailleurs)

2024-12-13 10:37 UTC, skelz0r commented on app/services/dgfip_spreadsheet_generator.rb
> +      authorization_request.definition.stage.exists? ? authorization_request.latest_authorization&.request_as_validated&.id : nil,
Et je me souviens: si on a eu une réouverture validée, ce n'est pas la dernière habilitation.

Et du coup ici on ne gère pas FC (lol)

2024-12-13 11:47 UTC, skelz0r commented
@JeSuisUnCaillou les 3 derniers commits

2024-12-13 14:52 UTC, JeSuisUnCaillou reviewed
Tu peux simplifier `dgfip_reporter?` et tej `users_for_roles` je pense.

2024-12-13 14:52 UTC, JeSuisUnCaillou commented on app/controllers/dgfip/export_controller.rb
> +    data_provider.reporters.exists?(id: current_user.id)
C'est quand même pas ouf de devoir sortir la liste complète de tous les users qui ont le rôle qu'on cherche, juste pour checker un seul user au final.

Tu peux très certainement faire une méthode plus directe, du genre `DataProvider#reporter?(user)`

2024-12-13 14:54 UTC, skelz0r commented on app/models/data_provider.rb
> +  end
C'est du SQL de base de manipulation de tableau, y'a rien de compliqué 🤔
Btw c'est comme ça dans User.

2024-12-13 14:55 UTC, JeSuisUnCaillou commented on app/controllers/dgfip/export_controller.rb
> +    data_provider.reporters.exists?(id: current_user.id)
Il resterait juste à faire un 

```ruby
"WHERE roles LIKE '%#{authorization_definition.id}:#{role}%'"
```

2024-12-13 14:56 UTC, JeSuisUnCaillou commented on app/controllers/dgfip/export_controller.rb
> +    data_provider.reporters.exists?(id: current_user.id)
Il resterait juste à faire un 

```
user.roles =~ /#{authorization_definition.id}:#{role}/
```

2024-12-13 14:57 UTC, skelz0r commented on app/controllers/dgfip/export_controller.rb
> +    data_provider.reporters.exists?(id: current_user.id)
> C'est quand même pas ouf de sortir la liste complète de tous les users qui ont le rôle qu'on cherche, juste pour checker un seul user au final.

C'est pour ça qu'il y a le `exists?(id: current_user.id)`, qui simplifie drastiquement la requête SQL et ne sort justement pas la liste de tous les users.

> Tu peux très certainement faire une méthode plus directe, du genre `DataProvider#reporter?(user)`

Je peux, c'est différent, mais le même résultat.

2024-12-13 14:58 UTC, JeSuisUnCaillou commented on app/controllers/dgfip/export_controller.rb
> +    data_provider.reporters.exists?(id: current_user.id)
En fait je trouve que c'est vraiment plus simple de créer `User#has_role_for?(authorization_definition, role)` et `User#reporter_for?(authorization_definition)` du coup

2024-12-13 14:58 UTC, skelz0r commented on app/controllers/dgfip/export_controller.rb
> +    data_provider.reporters.exists?(id: current_user.id)
Et en fait non, c'est pas son rôle, c'est le rôle d'une policy, et donc je referrai ce que j'ai fait avant mais je le mets dans une policy quoi.

2024-12-13 14:59 UTC, skelz0r commented
Et du coup.. je fais quoi ? Je laisse comme ça ou je fais une policy qui c/c ce qu'il y avait dans le controller ?
Et après, vu que c'est jetable comme code, je supprime la policy et je le remet dans le controller ? 🙃

2024-12-13 15:11 UTC, JeSuisUnCaillou requested changes
Ah oui en fait y'a encore ça :point_down: 
> * Y'a sûrement des opti à faire sur les requêtes effectuées, par ce que j'en compte 18 par authorization_request là
> * Je ne reçoit pas le fichier, et j'ai une erreur cheloue dans mon serveur quand je tente d'acccéder à `http://localhost:3000/dgfip/export` depuis mon navigateur, en tant que `datapass@yopmail.com` :
> 
> ![Screenshot from 2024-12-13 10-24-47](https://private-user-images.githubusercontent.com/6117264/395505189-83b78488-ccf2-4152-aae1-4c1fc67101ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxMDI2MTUsIm5iZiI6MTczNDEwMjMxNSwicGF0aCI6Ii82MTE3MjY0LzM5NTUwNTE4OS04M2I3ODQ4OC1jY2YyLTQxNTItYWFlMS00YzFmYzY3MTAxYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTNUMTUwNTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTJiM2UwNjVkYWMyYWQ0YjY2NGFmNDk2NTg4ZDMxMjJlNWJhODIzY2U5OGJmOGM4ZGNkMGZjODAzNjRmOThlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.29l43jsCSONzFC4qj7aWcSnku4C1OTxGBpnNq05FMA0)

2024-12-13 15:15 UTC, JeSuisUnCaillou commented
> Et du coup.. je fais quoi ? Je laisse comme ça ou je fais une policy qui c/c ce qu'il y avait dans le controller ? Et après, vu que c'est jetable comme code, je supprime la policy et je le remet dans le controller ? 🙃

Vu à l'oral, on est ok tel quel (j'avais pas pigé qu'il fallait checker plusieurs auth_definitions par user)

2024-12-13 15:17 UTC, JeSuisUnCaillou approved these changes
Reste juste à opti les requêtes, mais on peut voir plus tard.

2024-12-13 15:32 UTC, merged

2024-12-13 15:32 UTC, skelz0r commented
> Reste juste à opti les requêtes, mais on peut voir plus tard.

En effet, quand on aura des real lifes data on mettra les bons includes