api service national
etalab/data_pass pull request #6
Opened 2023-12-11 12:01 UTC by Isalafont

model
  authorization request forms yml
  modif fr.yml to add new api

2024-01-03 17:13 UTC, skelz0r commented
Je pense que tes rebase ont foiré (et là c'est un peu violent). Je te conseille de repartir d'une branche depuis develop, de cherry-pick tes commits un à un et de fixer un à un les soucis.

2024-01-08 14:36 UTC, Isalafont commented
> Je pense que tes rebase ont foiré (et là c'est un peu violent). Je te conseille de repartir d'une branche depuis develop, de cherry-pick tes commits un à un et de fixer un à un les soucis.

C'est exactement ce que je comptais faire, le rebase à foiré, je ne sais pas trop pourquoi mais ce n'est pas grave.

2024-01-08 16:21 UTC, skelz0r requested changes
cf mes coms

2024-01-08 16:21 UTC, skelz0r commented on config/authorization_definitions.yml
> +        value: "en_regle"
Y'a-t-'il un cas où ce scope peut ne pas être coché ? Si non, il n'y a pas lieu d'avoir de clé scopes.

2024-01-08 16:21 UTC, skelz0r commented on app/views/authorization_request_forms/api_service_national_inscription_concours_examen.html.erb
> +<%= authorization_request_form(@authorization_request) do |f| %>
Sans pré-remplissage des données personnelles ce formulaire sera forcément faux. Il y a 2 choix possibles:

1. On ajoute `destinataire_donnees_caractere_personnel` et `duree_conservation_donnees_caractere_personnel` dans ce formulaire
2. On les pré-remplis dans `data` sur les forms

Il manque aussi `description` que tu ajoutes et qui est exactement dans le même cas.

Cette remarque est valable pour le 2e form.

2024-01-08 16:21 UTC, skelz0r commented on spec/factories/authorization_requests.rb
> +    trait :api_service_national_inscription_concours_examen do
Teste aussi cette factory, tu vas voir qu'elle est fausse. (idem pour celle du dessous)

2024-01-08 16:52 UTC, Isalafont commented on app/views/authorization_request_forms/api_service_national_inscription_concours_examen.html.erb
> +<%= authorization_request_form(@authorization_request) do |f| %>
Dans les formulaires DataPass, les seules elements pré rempli étaient uniquement l'intitulé et le cadre juridique nature et url. 
Je laisse vide `description` et `destinataire_données_caractere_personnel` et `duree conservation donnees caractère personnel` pour que l'utilisateur le remplisse lui même ?

2024-01-08 16:55 UTC, skelz0r commented on app/views/authorization_request_forms/api_service_national_inscription_concours_examen.html.erb
> +<%= authorization_request_form(@authorization_request) do |f| %>
Ce que tu proposes est donc la solution 2.
Pour répondre à ta question: j'en sais rien, cela dépend de la logique métier / ce qui est le plus pertinent.

2024-01-08 16:56 UTC, skelz0r commented on app/views/authorization_request_forms/api_service_national_inscription_concours_examen.html.erb
> +<%= authorization_request_form(@authorization_request) do |f| %>
Tu peux par ailleurs pré-remplir ET mettre des inputs aussi: la couche modèle et la vue sont décorellés.

2024-01-09 11:44 UTC, Isalafont commented on spec/factories/authorization_requests.rb
> +    trait :api_service_national_inscription_concours_examen do
Je les ai testé dans `spec/models/authorization_request_spec.rb` et cela ne rend pas de message d'erreur.

2024-01-09 13:09 UTC, skelz0r commented on spec/factories/authorization_requests.rb
> +    trait :api_service_national_inscription_concours_examen do
Qu'est-ce que je dois regarder ?

2024-01-09 13:10 UTC, skelz0r commented on spec/factories/authorization_requests.rb
> +    trait :api_service_national_inscription_concours_examen do
Ok j'ai. Ici je suppose qu'un instructeur ne peut pas voir le formulaire en instruction. (vu que ça ne test que ça).

2024-01-09 13:11 UTC, skelz0r commented on spec/factories/authorization_requests.rb
> +    trait :api_service_national_inscription_concours_examen do
```ruby
visit instruction_authorization_request_path(authorization_request)
```

lève une exception, faut aller voir ce qui ne va pas.

2024-01-10 08:50 UTC, skelz0r requested changes
Rien de bien méchant à changer.

2024-01-10 08:50 UTC, skelz0r commented on app/models/authorization_request/api_service_national.rb
> +  end
Cette boucle ne sert pas

2024-01-10 08:50 UTC, skelz0r commented on app/models/authorization_request/api_service_national.rb
> +    :volumetrie_approximative
Ces données sont-elles obligatoires pour cette API ?

2024-01-10 08:50 UTC, skelz0r commented on app/views/authorization_request_forms/api_service_national_inscription_concours_examen.html.erb
> +      <%= "Information de base" %>
Déjà:

```suggestion
      Information de base
```

Ensuite : check pour mettre de l'i18n imo, c/c la logique de app/views/authorization_request_forms/api_infinoe_production.html.erb

Ce commentaire est valide pour l'ensemble des titres ci-dessous.

2024-01-10 08:50 UTC, skelz0r commented on app/views/authorization_request_forms/api_service_national_inscription_concours_examen.html.erb
> +  <div class="fr-mt-2w">
A ce stade je ne mettrais pas trop de class d'espacement, on verra pour faire du css plus high level et ainsi modifier d'une pierre N coups.

2024-01-10 08:50 UTC, skelz0r commented on app/views/authorization_request_forms/api_service_national_obligation_service_national.html.erb
> +<%= render 'authorization_request_forms/build/header' %>
Si c'est la même vue je ferai un partial: `_api_servicea_national_single_page.html.erb`:

```erb
<%= render partial: 'authorization_request_forms/api_service_national_single_page' %>
```

2024-01-10 08:50 UTC, skelz0r commented on config/authorization_request_forms.yml
> +      contact_technique_phone_number:
On peut simplifier en omettant à minima ces clés (vu que c'est vide dans les 2 forms).

2024-01-10 08:50 UTC, skelz0r commented on config/data_providers.yml
> +  minarm:
```suggestion
  ministere_des_armees:
```

quand même plus clair.

2024-01-10 08:50 UTC, skelz0r commented on config/data_providers.yml
> +    name: ApiServiceNational
Le nom du fournisseur de données est `ApiServiceNational` ? J'en doute.

2024-01-10 08:50 UTC, skelz0r commented on features/habilitations/api_service_national.feature
> +    * je remplis "Date de mise en production" avec "08/01/2042"
je vois que tu remplis systématiquement ce champ: est-il nécessaire ?

2024-01-10 08:50 UTC, skelz0r commented on spec/factories/authorization_requests.rb
> +    end
Je remonterai les 2 traits dans celui de `api_service_national`:

```suggestion
    trait :api_service_national do
      type { 'AuthorizationRequest::APIServiceNational' }
      form_uid { 'api-service-national' }

      with_basic_infos
      with_personal_data
      with_cadre_juridique
      with_contacts

      trait :api_service_national_inscription_concours_examen do
        form_uid { 'api-service-national-inscription-concours-examen' }
      end
  
      trait :api_service_national_obligation_service_national do
        form_uid { 'api-service-national-obligation-service-national' }
      end
    end
```

Vu que les `with_*` sont nécessaires pour que cela fonctionne. Si tu ajoutes ces 2 traits dans le test de factory tu te rendras compte que ça ne fonctionne pas.

2024-01-10 09:34 UTC, Isalafont commented on app/models/authorization_request/api_service_national.rb
> +    :volumetrie_approximative
Bonne question, parfois c'est rempli, d'autres fois non, je pense que @SchweisguthN pourra nous éclairer d'un point de vue métier du besoin ou non de garder ces attributs ?

2024-01-10 09:36 UTC, Isalafont commented on app/models/authorization_request/api_service_national.rb
> +    :volumetrie_approximative
La question de pose aussi pour l'attribut `maquette_projet` d'ailleurs

2024-01-10 09:38 UTC, skelz0r commented on app/models/authorization_request/api_service_national.rb
> +    :volumetrie_approximative
Si ce n'est pas rempli et validé ce n'est pas obligatoire donc.

2024-01-10 09:56 UTC, Isalafont commented on app/views/authorization_request_forms/api_service_national_inscription_concours_examen.html.erb
> +      <%= "Information de base" %>
Je me suis faite piéger par mon IDE qui m'avait traduit directement le i18n, je corrige ça !

2024-01-10 10:00 UTC, Isalafont commented on app/views/authorization_request_forms/api_service_national_inscription_concours_examen.html.erb
> +  <div class="fr-mt-2w">
Je retire les espacements des titres mais entre les sections, ça risque de rendre l'habilitation un peu illisible pour le moment ? Mais je suis d'accord que ce sera une chose sur laquelle travailler plus tard

2024-01-10 10:12 UTC, Isalafont commented on app/views/authorization_request_forms/api_service_national_obligation_service_national.html.erb
> +<%= render 'authorization_request_forms/build/header' %>
je créé un dossier `single_page` pour ce partial, je ne sais pas si c'est bien de mélanger les partials shared d'infos avec ceux des apis

2024-01-10 10:19 UTC, Isalafont commented on features/habilitations/api_service_national.feature
> +    * je remplis "Date de mise en production" avec "08/01/2042"
@SchweisguthN, cf question ci dessus, est ce que l'on garde ou pas ce champs pour ce formulaire ?

2024-01-10 11:02 UTC, Isalafont commented on spec/factories/authorization_requests.rb
> +    end
Ce qui veut dire que ce sera également le cas pour `api_entreprise_mdgis`

2024-01-10 11:05 UTC, skelz0r commented on spec/factories/authorization_requests.rb
> +    end
Oui. Faudrait harden le test de factory en utilisant l'ensemble des forms pour être sûr.

2024-01-10 11:14 UTC, Isalafont commented on spec/factories/authorization_requests.rb
> +    end
En fait, il y a une chose que je ne comprends pas, dans le cas `api_entreprise_mgdis`
```ruby
trait :api_entreprise do
      type { 'AuthorizationRequest::APIEntreprise' }
      form_uid { 'api-entreprise' }

      with_basic_infos
      with_personal_data
      with_cadre_juridique
      with_scopes
      with_contacts
    end

    trait :api_entreprise_mgdis do
      form_uid { 'api-entreprise-mgdis' }
    end
 ```
 
 Lorsque je rajoute `api_entreprise_mgdis` dans le test `spec/models/authorization_request_spec.rb`, je n'ai pas de message d'erreur 
 Pourtant si je fais un `FactoryBot.build(:authorization_request, :api_entreprise_mgdis)` en console, j'ai un message d'erreur `ActiveRecord::RecordInvalid: La validation a échoué : External est déjà utilisé(e), Organizations n'est pas valide `
 
 lorsqu'au trait de rajoute pour api_entreprise_mgdis le type, j'ai un FactoryBot fonctionnel mais le test qui failed car effectivement je dois également rajouter les with_*
 
 Je ne comprends pas trop pourquoi, on n'a pas eut d'erreur avant avec cette api ? 
 
 Et surtout, je dois rajouter à la main tous les attributs demandé dans la factorie du coup ?

2024-01-10 11:17 UTC, skelz0r commented on spec/factories/authorization_requests.rb
> +    end
> Pourtant si je fais un FactoryBot.build(:authorization_request, :api_entreprise_mgdis) en console, j'ai un message d'erreur ActiveRecord::RecordInvalid: La validation a échoué : External est déjà utilisé(e), Organizations n'est pas valide 

Cette erreur n'a rien à voir avec les demandes mais plutôt avec des séquences mal initialisées. Faut que tu cleans ta db si tu utilises la factory en dev.

> Je ne comprends pas trop pourquoi, on n'a pas eut d'erreur avant avec cette api ?

Parce qu'on ne testait pas ce comportement (i.e. crée ce modèle avec tous les attributs)

> Et surtout, je dois rajouter à la main tous les attributs demandé dans la factorie du coup ?

Je ne comprends pas cette partie. Je vais tenter d'y répondre: oui, mais c'est déjà fait avec les `with_*` du trait `:api_entreprise`.

2024-01-10 13:53 UTC, Isalafont commented on features/habilitations/api_service_national.feature
> +    * je remplis "Date de mise en production" avec "08/01/2042"
J'ai vérifié et toutes les habilitations validées ont ce champs de renseigné.

2024-01-10 13:56 UTC, skelz0r commented on features/habilitations/api_service_national.feature
> +    * je remplis "Date de mise en production" avec "08/01/2042"
Donc c'est potentiellement obligatoire ? Si oui il faut le valider dans la couche modèle.

2024-01-10 15:33 UTC, Isalafont commented on features/habilitations/api_service_national.feature
> +    * je remplis "Date de mise en production" avec "08/01/2042"
Ce n'est pas déjà validé dans le module `module AuthorizationExtensions::PersonalData` ligne 10 `      validates attr, presence: true, if: -> { need_complete_validation?(:personal_data) }` ?

2024-01-10 15:55 UTC, skelz0r requested changes
Y'a que le nom du provider qui est bloquant pour moi.

2024-01-10 15:55 UTC, skelz0r commented on config/data_providers.yml
> +    name: MinistereDesArmees
```suggestion
    name: Ministère Des Armées
```
pourquoi c'est collé ..?

2024-01-10 15:55 UTC, skelz0r commented on features/step_definitions/authorization_requests_steps.rb
> +Quand('je renseigne les infos de minimales du projet') do
```suggestion
Quand('je renseigne les infos minimales du projet') do
```

limite en vrai j'utiliserai celui des infos de base

2024-01-10 15:57 UTC, Isalafont commented on config/data_providers.yml
> +    name: MinistereDesArmees
faute de frappe...

2024-01-10 15:59 UTC, Isalafont commented on features/step_definitions/authorization_requests_steps.rb
> +Quand('je renseigne les infos de minimales du projet') do
Zut, je ne voulais pas commit ce changement qui ne sert à rien... surtout que les infos de base ne remplissent que intitulé et description dans features

2024-01-10 16:07 UTC, merged