Feature/dat 654 formulaires preremplis pour les cas dusage dimpot
etalab/data_pass pull request #616
Opened 2024-12-17 16:21 UTC by Samuelfaure

Encore un peu de polissage mais on y est presque

![image](https://github.com/user-attachments/assets/4cc0c2be-9bd4-47f3-a2e9-b2607640e894)

2024-12-20 13:55 UTC, skelz0r requested changes
Globalement je propose de déporter des classes partagées (définition/facade) dans des classes spécifiques, car cette logique ne sert que pour API Impot Particulier, n'a pas de sens ailleurs, et est par ailleurs basé sur une assertion fausse.

Et aussi les locales : en écrire des spécifiques pour API Impot Part (c'est une vue à part, ça semble logique d'utiliser des locales à part)/

2024-12-20 13:55 UTC, skelz0r commented on app/facades/new_authorization_request/base.rb
> +  def public_available_forms_sandbox
L'intégralité du code qui exploite le `public_available_forms_sandbox` devrait être cantonné dans une facade spécifique à API Impot Particulier.

Pour moi il faut intégralement déporter les itérations sur la couche modèle dans une classe `NewAuthorizationRequest::APIImpotParticulier` et non dans la base.

2024-12-20 13:55 UTC, skelz0r commented on app/models/authorization_definition.rb
> +  def public_available_forms_sandbox
Cf mon com sur la facade, ce fichier ne doit pas être modifié dans le cadre de cette PR.

2024-12-20 13:55 UTC, skelz0r commented on app/models/authorization_definition.rb
> +    @authorization_request_class_sandbox ||= AuthorizationRequest.const_get("#{id}_sandbox".classify)
Btw ceci est faux et n'exploite pas la conception des stages : il peut y avoir plusieurs prédécesseurs (`previouses` dans la config est un tableau), et l'id n'est pas conventionné.

2024-12-20 13:55 UTC, skelz0r commented on app/views/authorization_requests/new/api_impot_particulier.html.erb
> +    <h2 class="fr-h4"><%= t("authorization_requests.new.choose_form_title.sandbox") %></h2>
je me rends compte que la construction du fichier de locale est un peu pétée -> ici on veut complétement scoper cette locale à uniquement api impot particulier.

2024-12-20 13:55 UTC, skelz0r commented on app/views/authorization_requests/new/api_impot_particulier.html.erb
> +              <%= t(
typiquement ma remarque du dessus : c'est un peu wtf d'utiliser le même wording, autant spécifier uniquement pour cette page et complètement séparer.

2024-12-20 13:55 UTC, skelz0r commented on config/authorization_request_forms/api_impot_particulier.yml
> +  description: Dites-le nous une fois - Place en crèche (Production)
je le dis ici mais c'est valable pour les autres: si c'est non public la description ne sert pas.

2024-12-20 13:55 UTC, skelz0r commented on features/step_definitions/authorization_requests_steps.rb
> +  if authorization_definition.available_forms.any?
Tu viens d'introduire un bug pour moi, faut traiter ce cas à part et réfléchir à comment gérer : qu'est-ce qui se passe si on a 2 formulaires avec le même nom ? On prend lequel ? Ça me parait pas viable comme approche, il faut changer.

2024-12-20 13:55 UTC, skelz0r commented on spec/factories/authorization_requests.rb
> +    trait :api_impot_particulier_production_editeur do
pourquoi avoir changé le nom ?

2024-12-20 15:38 UTC, evaspae submitted a review, later dismissed
Pour le côté UX / UI, je te mets [le lien vers la maquette](https://www.figma.com/design/ANSlIiYhXtQNnsDVWtePH3/Datapass-V2?node-id=9189-86574&m=dev&t=cQdFOiRFs1ksKRQv-1) afin que tu récupères les pictos pour les cas d'usage + que tu vois les espacements entre les éléments.

2024-12-24 10:41 UTC, Samuelfaure commented on spec/factories/authorization_requests.rb
> +    trait :api_impot_particulier_production_editeur do
Me semblait juste mieux d'ajouter `editeur` que d'ajouter `avec_editeur` sur tous ces forms editeurs 🤷

2024-12-26 08:55 UTC, Samuelfaure commented
@evaspae Je réutilise le component qu'on utilise dans ces situations; pas de soucis pour effectuer ces changements mais je te préviens que ça se répercutera ailleurs (après, cette maquette est mieux que l'actuel donc ça sera un gain IMO)

2024-12-26 13:41 UTC, Samuelfaure commented on app/views/authorization_requests/new/api_impot_particulier.html.erb
> +    <h2 class="fr-h4"><%= t("authorization_requests.new.choose_form_title.sandbox") %></h2>
Petit problème ici, la création d'un fichier à part entraîne le breaking de toutes les locales de ce fichier (le fichier prend priorité par dessus fr.yml)
Je pense couper la poire en deux en namespaçant

2024-12-26 13:42 UTC, Samuelfaure commented on app/views/authorization_requests/new/api_impot_particulier.html.erb
> +    <h2 class="fr-h4"><%= t("authorization_requests.new.choose_form_title.sandbox") %></h2>
Petit problème ici, la création d'un fichier à part entraîne le breaking de toutes les locales de ce fichier (le fichier prend priorité par dessus fr.yml)
Je pense couper la poire en deux en namespaçant

2024-12-26 13:43 UTC, Samuelfaure commented on app/views/authorization_requests/new/api_impot_particulier.html.erb
> +    <h2 class="fr-h4"><%= t("authorization_requests.new.choose_form_title.sandbox") %></h2>
Petit problème ici, la création d'un fichier à part entraîne le breaking de toutes les locales de ce fichier (le fichier prend priorité par dessus fr.yml)
Je pense couper la poire en deux en namespaçant

2024-12-26 13:53 UTC, skelz0r commented on app/views/authorization_requests/new/api_impot_particulier.html.erb
> +    <h2 class="fr-h4"><%= t("authorization_requests.new.choose_form_title.sandbox") %></h2>
Les fichiers sont fusionnés avant d'être load, qu'il y est 1 ou 100 fichiers n'a aucune incidence, tu utilises sûrement une clé déjà existante ailleurs (et donc override)

2024-12-26 14:24 UTC, Samuelfaure commented on app/views/authorization_requests/new/api_impot_particulier.html.erb
> +    <h2 class="fr-h4"><%= t("authorization_requests.new.choose_form_title.sandbox") %></h2>
Oui, mais cette clef est dynamique.

Je pourrais copier-coller toutes les clefs issues de la clef dynamique et mettre ça en static dans un fichier à part, mais ça rajoute masse de copier-coller pour peu de chose

2024-12-27 12:05 UTC, Samuelfaure commented
Je re-request @skelz0r pour la partie technique
Je m'occupe du CSS, ça devrait aller vite

2024-12-27 13:42 UTC, Samuelfaure commented
@evaspae Pour l'espacement tu es OK que ça va également changer sur les autres selecteurs de formulaire de la même façon? (Api particulier, entreprise)

2024-12-30 12:00 UTC, Samuelfaure commented
Update UI

![image](https://github.com/user-attachments/assets/2f1540ba-740b-45d1-a759-3d30110b6c0f)

J'ai ajouté une variable pour ce format de carte pour que les modifications ne touchent pas ses autres utilisations (j'ai expérimenté plusieurs possibilités UI genre utiliser ce format compact partout, mais c'était moche)

2025-01-06 11:38 UTC, skelz0r submitted a review, later dismissed
juste le gros pavé sur la facade, mais imo go merge on itérera niveau UI après

2025-01-06 11:45 UTC, Samuelfaure commented on features/step_definitions/api_impot_particulier_steps.rb
> +Quand('je veux remplir une demande pour API Impot Particulier via le formulaire {string} en bac à sable') do |authorization_request_form_name|
C'est un cas spécifique à API Impot Part donc je crois pas

2025-01-06 11:47 UTC, Samuelfaure commented on spec/models/authorization_definition_spec.rb
> +    let(:instance) { described_class.find('api_impot_particulier') }
Bonne  question, je me souvient plus 🤔 je vais switch back, possible que ça soit des restes de modifs qui ont été revert

2025-01-06 12:59 UTC, merged

2025-01-07 08:37 UTC, evaspae commented
> @evaspae Pour l'espacement tu es OK que ça va également changer sur les autres selecteurs de formulaire de la même façon? (Api particulier, entreprise)
> 
> + j'ai fait une request pour etre editeur, apparemment je peux pas DL les pictos sans ça

Oui je suis ok avec ça, les maquettes sont identiques de mon côté !

2025-01-07 08:37 UTC, evaspae commented
> @evaspae Pour l'espacement tu es OK que ça va également changer sur les autres selecteurs de formulaire de la même façon? (Api particulier, entreprise)
> 
> + j'ai fait une request pour etre editeur, apparemment je peux pas DL les pictos sans ça

Normalement c'est bon, tu dois être éditeur maintenant. Je te laisse me dire si ça fonctionne

2025-01-07 08:57 UTC, evaspae commented
> Update UI
> 
> ![image](https://private-user-images.githubusercontent.com/14159757/399286555-2f1540ba-740b-45d1-a759-3d30110b6c0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyMzkyMzMsIm5iZiI6MTczNjIzODkzMywicGF0aCI6Ii8xNDE1OTc1Ny8zOTkyODY1NTUtMmYxNTQwYmEtNzQwYi00NWQxLWE3NTktM2QzMDExMGI2YzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA3VDA4MzUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxOTU3NzYxOTk5M2Y3ZDZjNDAxZjViOTM5M2QyMTkxMWNkODBjMjYxYTJjMTUyN2QxY2JmMWI3YmU3MDg0MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NWa8kSRmiJZPZbOT65mYeLP6yXlncTdHGEH4tD0aUsc)
> 
> J'ai ajouté une variable pour ce format de carte pour que les modifications ne touchent pas ses autres utilisations (j'ai expérimenté plusieurs possibilités UI genre utiliser ce format compact partout, mais c'était moche)
> 
> J'ai un doute sur le padding-bottom que j'ai ajouté, faudra vérifier si c'est pas moche avec des descriptions plus longues, mais pas grave ça se change easy

Pour que le composant sois clean et puisse être réutilisé partout, est-ce qu'on peut suivre cette structure : 
(le texte est centré mais les cartes sont ferrées à gauche, le formulaire demande libre est toujours en dernier)

<img width="1725" alt="Page _ cas d'usage" src="https://github.com/user-attachments/assets/e422d3f1-ca86-431f-a5bc-b52377c860fa" />

2025-01-07 11:14 UTC, skelz0r commented
Je me rends compte qu'il n'y a aucun test de complétion de formulaires, et il s'avère que ça ne marche pas.

2025-01-07 11:34 UTC, JeSuisUnCaillou commented
> Je me rends compte qu'il n'y a aucun test de complétion de formulaires, et il s'avère que ça ne marche pas.

Dommage ça. Tu as besoin que @Samuelfaure s'en occuppe ?

2025-01-07 11:36 UTC, Samuelfaure commented
> Je me rends compte qu'il n'y a aucun test de complétion de formulaires, et il s'avère que ça ne marche pas.

Whatdafuck j'ai fait les tests cucumber normalement 

Je m'y repenche après la reunion

2025-01-07 11:39 UTC, JeSuisUnCaillou commented
> Whatdafuck j'ai fait les tests cucumber normalement

Ptet qu'il manque juste des tests qui vont vraiment au bout de la soumission d'un formulaire

2025-01-08 07:41 UTC, skelz0r commented
Tu peux complètement t'inspirer de features/habilitations/france_connect.feature pour tous les faire.

2025-01-08 07:43 UTC, skelz0r commented
Pense à close https://errors.data.gouv.fr/organizations/sentry/issues/247508/ au passage