DAT_231 habilitation le taxi
etalab/data_pass pull request #64
Opened 2024-01-23 09:47 UTC by Isalafont

2024-01-23 15:45 UTC, Samuelfaure commented on app/views/authorization_request_forms/shared/_legal_api_le_taxi.html.erb
> +    <%= f.dsfr_text_area :cadre_juridique_nature, value: "Articles L. 3121-11-1 et R3121-24 à R3121-33 du Code des transports", required: true, rows: 2 %>
On va mettre ça dans les locales (le `value`)

2024-01-23 15:46 UTC, Samuelfaure commented on app/views/authorization_request_forms/shared/_legal_api_le_taxi.html.erb
> +    <%= f.dsfr_url_field :cadre_juridique_url, value: "https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000029528684&cidTexte=LEGITEXT000023086525;https://www.legifrance.gouv.fr/
Idem

2024-01-23 15:46 UTC, Samuelfaure commented on app/views/authorization_request_forms/shared/single_page/_api_le_taxi.html.erb
> +<%= authorization_request_form(@authorization_request) do |f| %>
pas fan des noms de variables à une lettre même si c'est commun, mettons `form` plutôt ça coute pas beaucoup plus cher

2024-01-24 08:31 UTC, Un3x commented on app/views/authorization_request_forms/shared/single_page/_api_le_taxi.html.erb
> +<%= authorization_request_form(@authorization_request) do |f| %>
Sur le fond t'as pas tord, mais dans le projet c'est partout `|f|` qui est utilisé, par consistence je laisserai (ou je changerai tout).

2024-01-24 08:59 UTC, Isalafont commented on app/views/authorization_request_forms/shared/single_page/_api_le_taxi.html.erb
> +<%= authorization_request_form(@authorization_request) do |f| %>
C'est la question que je me posais, est ce que l'on change tout dans tout le projet et dans ce cas là, cela nécessiterait de faire une PR dédiée, ou bien on laisse en l'état.

2024-01-24 09:01 UTC, Isalafont commented on app/views/authorization_request_forms/shared/_legal_api_le_taxi.html.erb
> +    <%= f.dsfr_text_area :cadre_juridique_nature, value: "Articles L. 3121-11-1 et R3121-24 à R3121-33 du Code des transports", required: true, rows: 2 %>
Ça aurait effectivement plus de sens de tout centraliser dans les locales !

2024-01-24 09:03 UTC, skelz0r commented on app/views/authorization_request_forms/shared/single_page/_api_le_taxi.html.erb
> +<%= authorization_request_form(@authorization_request) do |f| %>
C'est conventionnel d'utiliser f pour les forms dans rails, je suis  d'avis de laisser comme ça

2024-01-24 12:53 UTC, skelz0r requested changes
3 gros trucs pour moi:

1. Jarter le legal spécifique, et si il y a besoin de faire des vues spécifiques faire un système qui permet d'utiliser une vue custom
2. Transformer le `description` en 3 champs : pourquoi demander la donnée structurée dans un champ générique ? Ou alors y'a un truc qui m'échappe.
3. Le champ `cadre_juridique_url` qui prend 2 urls, faut trouver une solution car c'est pas optimal

Je pense que le 3. va faire qu'il va falloir trouver une solution pour 1.

2024-01-24 12:53 UTC, skelz0r commented on app/views/authorization_request_forms/shared/_legal_api_le_taxi.html.erb
> +<%= f.info_for(:legal_api_le_taxi) %>
Pourquoi ne pas avoir réutilisé le app/views/authorization_request_forms/shared/_legal.html.erb qui est strictement identique ?

2024-01-24 12:53 UTC, skelz0r commented on app/models/authorization_request/api_le_taxi.rb
> +  end
Pourquoi ne pas avoir utilisé `AuthorizationExtensions::CadreJuridique` ?

2024-01-24 12:53 UTC, skelz0r commented on app/models/authorization_request/api_le_taxi.rb
> +  end
Ok je comprends, c'est pour `legal_api_le_taxi`, mais du coup ça n'a pu lieu d'être.

D'ailleurs au passage je pense que c'est mieux de garder `legal` et trouver un moyen de customiser la vue (par exemple via la config du form, ou en mettant un dossier spécial) plutôt que d'introduire des noms bizarres comme ici.

2024-01-24 12:53 UTC, skelz0r commented on app/views/authorization_request_forms/shared/single_page/_api_le_taxi.html.erb
> +  </div>
1. Cette UI est bizarre, faudrait à minima l'aligner au milieu le bloc
2. Cette loop est overkill

2024-01-24 12:53 UTC, skelz0r commented on config/authorization_request_forms.yml
> +  api-le-taxi:
```suggestion
  api-le-taxi-chauffeur:
```

plus logique imo

2024-01-24 12:53 UTC, skelz0r commented on config/authorization_request_forms.yml
> +      cadre_juridique_url: "https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000029528684&cidTexte=LEGITEXT000023086525;https://www.legifrance.gouv.fr/affichCode.do?idSectionTA=L
C'est pas une url valide ça, faut changer le format.

2024-01-24 12:53 UTC, skelz0r commented on config/locales/authorization_request_forms.fr.yml
> +      description:
Pourquoi ne pas avoir fait 3 champs ici ? Au début j'aurais pensé que c'était parce ça change en fonction des formulaires, mais apparemment non.

2024-01-24 12:53 UTC, skelz0r commented on config/locales/authorization_request_forms.fr.yml
> +        hint: "Indiquer le nombre de taxis et courses mensuelles actuellement (approximatif), les villes desservies et la proportion de courses CPAM/Aéroport"
Keep it dry ici:

```suggestion
    api_le_taxi_client: 
      description: &api_le_taxi_description_common
        hint: "Indiquer le nombre de taxis et courses mensuelles actuellement (approximatif), les villes desservies et la proportion de courses CPAM/Aéroport"

    api_le_taxi_chauffeur_client:
      <<: *api_le_taxi_description_common

    api_le_taxi_appsolu_connexion:
      <<: *api_le_taxi_description_common

    api_le_taxi_appsolu_mise_en_regle:
      <<: *api_le_taxi_description_common

    api_le_taxi_axygest_connexion:
      <<: *api_le_taxi_description_common

    api_le_taxi_tessa_connexion:
      <<: *api_le_taxi_description_common
```

2024-01-24 13:50 UTC, skelz0r commented
Et aussi il manque un truc assez important: les scénarios cucumber.

2024-01-24 15:22 UTC, Isalafont commented on config/locales/authorization_request_forms.fr.yml
> +      description:
Effectivement pour les formulaires des editeurs, faire 3 champs prendrait tout son sens mais pour les formulaires en demande libre, est ce qu'il ne serait pas utile de toute de même garder le champs description tel quel ?

2024-01-24 15:26 UTC, skelz0r commented on config/locales/authorization_request_forms.fr.yml
> +      description:
Je ne comprends pas ta remarque vu que tu as mis sur tous les formulaires cette description.

2024-01-24 15:29 UTC, skelz0r commented on config/locales/authorization_request_forms.fr.yml
> +      description:
(enfin ce hint)

2024-01-24 15:49 UTC, Isalafont commented on config/locales/authorization_request_forms.fr.yml
> +      description:
On attend une réponse de Saliha, notre contact chez Api Le Taxi pour savoir ce qui serait toujours pertinent en champs, quoi garder, de quoi peut on se passer... 
Je l'ai mis sur tous les champs mais je me pose aussi la question de savoir si c'est vraiment nécessaire sur tous les formulaires ou si cela n'a d'intérêt que sur les forms éditeurs ?

2024-01-29 10:36 UTC, Isalafont commented on app/models/authorization_request/api_le_taxi.rb
> +  end
Tu entends quoi par dossier spécial ?

2024-01-29 10:38 UTC, Isalafont commented
> 3 gros trucs pour moi:
> 
> 1. Jarter le legal spécifique, et si il y a besoin de faire des vues spécifiques faire un système qui permet d'utiliser une vue custom
> 2. Transformer le `description` en 3 champs : pourquoi demander la donnée structurée dans un champ générique ? Ou alors y'a un truc qui m'échappe.
> 3. Le champ `cadre_juridique_url` qui prend 2 urls, faut trouver une solution car c'est pas optimal
> 
> Je pense que le 3. va faire qu'il va falloir trouver une solution pour 1.

est ce que faire des `nested_attributes` ici ne serait pas une solution ?

2024-01-29 10:42 UTC, skelz0r commented on app/models/authorization_request/api_le_taxi.rb
> +  end
Un dossier portant le nom de l'uid, genre `app/views/authorization_request_forms/api_le_taxi`

2024-01-29 10:43 UTC, skelz0r commented
> Nested attributes allow you to save attributes on associated records through the parent.

On parle de quelles associations ici ?

2024-01-29 10:47 UTC, skelz0r commented on app/models/authorization_request/api_le_taxi.rb
> +  end
Exemple -> https://github.com/etalab/data_pass/pull/69/commits/2bf19e117009b818838d15081a1b5764e1bdf55b#diff-933eb67689c0be7f81dc4aff7f7f6960057283780f3ad7fe8fe56306232f1df7R7

2024-01-29 10:58 UTC, Isalafont commented
> > Nested attributes allow you to save attributes on associated records through the parent.
> 
> On parle de quelles associations ici ?

Pour l'attribut description avec 3 champs, et finalement le principe pourrait aussi s'appliquer pour le cadre juridique avec 2 urls ?

2024-01-29 11:02 UTC, skelz0r commented
Une association au sens d'ActiveRecord c'est ajouter un nouveau modèle et de faire un belongs_to/has_many/has_one entre 2 modèles. Je ne pense pas qu'on veuille ça.

Ici il faut à mon sens:

1. Supprimer le champ `description` et faire 3 champs ;
2. Transformer la vue de `cadre_juridique url` et faire une vraie validation là dessus (si on en attend plusieurs ou un seul).

2024-04-15 07:25 UTC, Samuelfaure commented
On ferme ici?

2024-04-15 12:39 UTC, Isalafont commented
> On ferme ici?

ce serait peut être plus judicieux, tout a tellement changé depuis !! 
Par contre les infos de l'api sont valables elles...

2024-04-17 11:41 UTC, Samuelfaure commented
Ok! Je te laisse décider s'il vaut mieux reprendre ici ou fermer et cherry-pick les commits adéquats

2024-04-17 18:41 UTC, Isalafont commented
> Ok! Je te laisse décider s'il vaut mieux reprendre ici ou fermer et cherry-pick les commits adéquats

Api le Taxi risque d'être une Api que l'on implémentera bientôt, du coup, je vais peut être la mettre en Draft et la reprendre dans vraiment pas longtemps en fait 🤔

2024-07-18 14:30 UTC, JeSuisUnCaillou commented
Ca devient quoi cette PR ?

2024-07-18 14:51 UTC, skelz0r commented
Je pense qu'on peut closer et référencer cette PR dans une grosse issue Le Taxi v2 (comme HubEE)

2024-08-08 05:55 UTC, closed without merging