Api 2104 - Homepage
etalab/data_pass pull request #70
Opened 2024-01-31 10:11 UTC by Isalafont

<img width="1508" alt="Capture d’écran 2024-01-31 à 11 12 37" src="https://github.com/etalab/data_pass/assets/43042737/0b99170d-7a86-4bf7-82d9-0beb8ec76f2f">

2024-01-31 10:49 UTC, Samuelfaure requested changes
Je pense qu'en utilisant le DSFR tu peux te passer complètement de CSS

+ Il reste du texte qui n'est pas dans la config file

2024-01-31 10:49 UTC, Samuelfaure commented on app/assets/stylesheets/pages/home.css
> +}
Oulah je suis certain qu'on a pas besoin de tout ça avec le DSFR

2024-01-31 10:50 UTC, Samuelfaure commented on app/assets/stylesheets/pages/home.css
> +}
Surtout les media queries a mon avis on veut absolument s'en passer imo

2024-01-31 11:12 UTC, Isalafont commented on app/assets/stylesheets/pages/home.css
> +}
J'ai regardé sur le DSFR et je n'ai pas l'impression qu'il y ait un élément correspondant à ce type de cadre (ce n'est pas une tuile, ni reelement une card)

Mais après, on peut tester autre chose pour voir.

2024-01-31 11:25 UTC, skelz0r commented
Honnêtement la HP on peut faire du css custom. Après si c'est dans le DSFR go utiliser.

(Je n'ai pas lu le code encoree)

2024-01-31 12:17 UTC, Samuelfaure commented
En pure DSFR:

![image](https://github.com/etalab/data_pass/assets/14159757/4e91c72c-9592-478d-9ebb-25edefa48a36)

A voir si on veut du CSS custom pour les cadres, je serais d'avis que vaut mieux tenter d'utiliser les composants de base du DSFR donc trouver une alternative.

Besoin du retour d'Eva pour les espacements / la question des cadres

2024-02-05 11:24 UTC, Isalafont commented
En essayant de respecter au maximum le Dsfr
<img width="1508" alt="Capture d’écran 2024-02-05 à 12 23 14" src="https://github.com/etalab/data_pass/assets/43042737/12d25bd9-efbb-47df-844b-b289fa4a212d">

Lien vers le figma 
https://www.figma.com/file/ANSlIiYhXtQNnsDVWtePH3/Datapass?type=design&node-id=3240%3A377374&mode=design&t=c7C5Vk5EDZetcjwI-1

2024-02-06 10:08 UTC, skelz0r approved these changes

2024-02-06 10:08 UTC, skelz0r commented on app/assets/stylesheets/pages/home.css
> +p.fr-h6 {
Je ne comprends pas ce `h6` qui ne change que la couleur 🤷

2024-02-06 10:28 UTC, Isalafont commented on app/assets/stylesheets/pages/home.css
> +p.fr-h6 {
sans le css 
<img width="735" alt="Capture d’écran 2024-02-06 à 11 26 07" src="https://github.com/etalab/data_pass/assets/43042737/bac43514-46dd-4b29-b22a-625b06eb9c6e">

et avec le css pour caler au plus pres de la maquette d'Eva
<img width="735" alt="Capture d’écran 2024-02-06 à 11 27 28" src="https://github.com/etalab/data_pass/assets/43042737/eea90bcd-6bd8-4850-8258-2322c0a123cd">

Si on doit supprimer, on supprime :)

2024-02-06 10:32 UTC, Samuelfaure commented on app/views/pages/home.html.erb
> +          <p class="fr-h6">
Ça devrait être `<h2>` ici IMO

2024-02-06 10:32 UTC, Samuelfaure commented on app/views/pages/home.html.erb
> +          <p class="fr-h6">
```suggestion
          <h2>
```

2024-02-06 10:33 UTC, Samuelfaure commented on app/assets/stylesheets/pages/home.css
> +p.fr-h6 {
Supprime IMO cf mon commentaire

2024-02-06 10:33 UTC, Samuelfaure commented on app/assets/stylesheets/pages/home.css
> +}
Y'a pas un composant DSFR pour les line-breaks ?

2024-02-06 10:36 UTC, skelz0r commented on app/assets/stylesheets/pages/home.css
> +p.fr-h6 {
Mon point c'est le fait qu'on affecte une logique sémantique `h6` sans modifier la taille de typo, adossé à une balise `p`. Ça n'a pas de sens.

2024-02-06 10:37 UTC, skelz0r commented on app/assets/stylesheets/pages/home.css
> +}
imo non

2024-02-06 10:40 UTC, Samuelfaure requested changes

2024-02-06 10:40 UTC, Samuelfaure commented on app/views/pages/home.html.erb
> +        <div class="line-break">
Un line-break c'est `<br />`
Un line-separator (ou line-divider) c'est `<hr />`

2024-02-06 10:40 UTC, Samuelfaure commented on app/assets/stylesheets/pages/home.css
> +}
J'ai regardé dans le code, si tu veux un line-separator ils sont déjà stylisés dans le DSFR, utilise un simple `<hr />` et vire ce fichier

2024-02-06 10:51 UTC, Isalafont commented on app/assets/stylesheets/pages/home.css
> +}
Je n'arrive pas à trouver de composant correspondant a un line-breaks.

2024-02-06 10:51 UTC, Isalafont commented on app/assets/stylesheets/pages/home.css
> +}
Tu l'as trouvé le line-separator dans le DSFR, j'ai fait toutes les pages et je ne l'ai pas vu 🫣
Parceque c'est EXACTEMENT ce que je voulais

2024-02-06 10:55 UTC, Isalafont commented on app/assets/stylesheets/pages/home.css
> +p.fr-h6 {
donc je remplace mon <p> en <h2 class="fr-h6">

2024-02-06 10:59 UTC, Isalafont commented on app/views/pages/home.html.erb
> +          <p class="fr-h6">
Si je passe le titre en `h2` sans rajouter la class, ça fait un résultat vraiment pas beau
`h2` sans class vs `h2` avec la class `fr-h6`

<img width="796" alt="Capture d’écran 2024-02-06 à 11 58 33" src="https://github.com/etalab/data_pass/assets/43042737/4b79f677-3cdb-4d06-ab54-36273e90a10d">

2024-02-06 11:01 UTC, Isalafont commented on app/views/pages/home.html.erb
> +        <div class="line-break">
Effectivement, je n'ai pas le bon terme en plus
Merci pour la précision 👍🏻

2024-02-06 11:02 UTC, skelz0r commented on app/assets/stylesheets/pages/home.css
> +p.fr-h6 {
Le souci aussi c'est que `fr-h6` soit dans `pages/`. C'est une classe globale sans namespace, ça devrait être dans un composant ou une extension.

Si tu ne veux pas te prendre la tête je ferai un truc du genre `homepage-subtitle`

2024-02-06 11:06 UTC, Samuelfaure commented on app/assets/stylesheets/pages/home.css
> +}
J'ai regardé directement dans le code^^

2024-02-06 11:06 UTC, Isalafont commented on app/assets/stylesheets/pages/home.css
> +p.fr-h6 {
En gros tu ferais qq chose comme cela :
 ```
 <div class="homepage-subtitle">
   <h2 class="fr-h6">
     <%= t('.mcp_connexion').html_safe %>
   </h2>
</div>
```

2024-02-06 11:07 UTC, Samuelfaure commented on app/views/pages/home.html.erb
> +          <p class="fr-h6">
Je vois que une image ici

2024-02-06 11:11 UTC, Samuelfaure commented on app/views/pages/home.html.erb
> +          <p class="fr-h6">
Essaies:

  `<h2 class="fr-h6"> `

C'est ce qui est conseillé dans la doc

La couleur est pas bonne quand tu fais ça? Le cas échéant essaies fr-h5 maybe

2024-02-06 11:15 UTC, Isalafont commented on app/views/pages/home.html.erb
> +          <p class="fr-h6">
Quand on fait `<h2 class="fr-h6">` la couleur reste la bonne (ça changeait la couleur surement à cause du `<p>`
bon je garde avec le h6, ça correspond mieux à notre maquette plutot que le h5

2024-02-06 11:28 UTC, Isalafont commented on app/assets/stylesheets/pages/home.css
> +}
Ah bin voila... parceque c'est nul par dans la doc

2024-02-06 11:31 UTC, skelz0r commented
Y'a un petit souci avec ton rebase là.

2024-02-06 11:32 UTC, skelz0r commented on app/assets/stylesheets/pages/home.css
> +p.fr-h6 {
Non je ferai

```html
  <h2 class="homepage-subtitle">
    <%= t('.mcp_connexion').html_safe %>
  </h2>
```

2024-02-06 11:36 UTC, skelz0r commented
Y'a encore un souci avec ton rebase.

Je repartirai de develop, referai une branche, et un cherry pick de uniquement tes commits.

2024-02-06 11:37 UTC, Isalafont commented
@skelz0r ce rebase me donne du fil a retordre.... je crois qu'il vaut mieux que j'aille manger et je clean juste après parceque ÇA M'ENERVE 😵‍💫

2024-02-06 11:39 UTC, skelz0r commented
```sh
git checkout develop
git pull origin develop
git checkout -b API-2104/homepage-2
git cherry-pick SHA1 SHA2 ... SHAN
git branch -m API-2104/homepage API-2104/homepage-old
git branch -m API-2104/homepage-2 API-2104/homepage
git push origin -f. API-2104/homepage
```

2024-02-06 11:39 UTC, skelz0r commented
Y'a peut-être moyen de simplifier `git cherry-pick SHA1 SHA2 ... SHAN` (faut demander à chatgpt)

2024-02-06 12:55 UTC, Isalafont commented on app/assets/stylesheets/pages/home.css
> +p.fr-h6 {
Mais dans ce cas la, je dois reproduire la class `fr-h6` en css (font-size, line-height... et les changements inclus avec les media queries...)
Parceque le titre en `h2` est bien trop gros par rapport à ce l'on souhaite niveau design.

2024-02-06 12:57 UTC, Isalafont commented on app/assets/stylesheets/pages/home.css
> +p.fr-h6 {
> Le souci aussi c'est que `fr-h6` soit dans `pages/`. _C'est une classe globale sans namespace, ça devrait être dans un composant ou une extension_.
> 
> Si tu ne veux pas te prendre la tête je ferai un truc du genre `homepage-subtitle`

Sachant qu'en retravaillant la home page, pour le ticket suivant, ces 2 composants de button MCP et API.Gouv) seront dans des fichiers partagés.

2024-02-06 13:01 UTC, skelz0r commented on app/assets/stylesheets/pages/home.css
> +p.fr-h6 {
```htlm
  <div class="homepage-subtitle">
    <%= t('.mcp_connexion').html_safe %>
  </div>
```

🤷

2024-02-06 13:01 UTC, skelz0r commented on app/assets/stylesheets/pages/home.css
> +p.fr-h6 {
> Sachant qu'en retravaillant la home page, pour le ticket suivant, ces 2 composants de button MCP et API.Gouv) seront dans des fichiers partagés.

La réponse est dans ta phrase: c'est un composant.

2024-02-06 13:22 UTC, Un3x commented
Moi j'fais `git rebase develop` :O

2024-02-06 13:23 UTC, Un3x commented on app/views/pages/home.html.erb
> +          <p class="fr-h6">
IMO c'est pas un h2. Sémantiquement c'est pas un sous chapitre du h1 et c'est un composant partagé qui pourra être affiché à différent niveau dans une page.
Donc je mettrais pas un h2 html, après niveau style c'est un autre sujet. On fait une classe ou on utilise le style des `fr-h6` pour moi ca n'a pas vraiment d'importance.

2024-02-06 13:45 UTC, Isalafont commented
Finalement j'ai cherry-pick chaque commit individuellement, c'était plus simple et plus sure de ne perdre aucune info.

2024-02-06 14:02 UTC, Isalafont commented
> Moi j'fais `git rebase develop` :O

D'habitude je fais une `git rebase -i develop` mais je ne sais pas pourquoi ça a failed...

2024-02-12 10:18 UTC, merged