Feature/api 2106 page non connectee formulaire dhabilitation
etalab/data_pass pull request #77
Opened 2024-02-05 09:19 UTC by Isalafont

2024-02-05 09:20 UTC, skelz0r commented
Vous voulez pas d'abord merger https://github.com/etalab/data_pass/pull/70 et rebase dessus ?

2024-02-14 10:05 UTC, skelz0r requested changes
Le plus important:

1. Supprimer tous les `html_safe`, qui est paradoxalement pas safe du tout
2. Certains naming sont mauvais
3. Le visit générique en cucumber

2024-02-14 10:05 UTC, skelz0r commented on features/redirections.feature
> +    Quand je tente d'accéder à 'formulaires/api-entreprise/demande/nouveau'
Cette étape est trop technique.
Inspire toi des `visit` dans le fichier `features/step_definitions/authorization_requests_steps.rb` pour faire un truc du genre "Quand je veux remplir une demande pour "API Entreprise" via le formulaire "Demande libre"`

2024-02-14 10:05 UTC, skelz0r commented on features/redirections.feature
> +    Sachant que je suis un demandeur non connecté
Un demandeur n'est pas forcément connecté.

2024-02-14 10:05 UTC, skelz0r commented on features/step_definitions/web_steps.rb
> +Quand(%r{^je tente d'accéder à 'formulaires/([^']+)/demande/nouveau'$}) do |form_uid|
Cf plus haut, cette étape est trop technique.

2024-02-14 10:05 UTC, skelz0r commented on app/views/pages/shared/_mcp.html.erb
> +      <%= t('pages.home.mcp_connexion').html_safe %>
Je t'invite à aussi déplacer les wordings pour faire du lazy lookup https://guides.rubyonrails.org/i18n.html#lazy-lookup

2024-02-14 10:05 UTC, skelz0r commented on app/views/pages/custom.html.erb
> +              <div>S’identifier avec MonComptePro</div>
Pourquoi ce n'est pas dans un i18n ?

2024-02-14 10:30 UTC, Isalafont commented on app/controllers/authorization_request_forms_controller.rb
> +      render 'pages/custom'
tu parles de `pages/custom` ou du nom de la méthode `save_redirect_path` ?

2024-02-14 10:35 UTC, Isalafont commented on app/views/pages/custom.html.erb
> +          <%= t('pages.home.title').html_safe %>
Il y a du `html_safe` un peu partout dans l'app. Notamment dans `app/views/kaminari/_next_page.html.erb` ou dans les views instructions par exemple. 
Dans quel cas, peut on utiliser `html_safe` et dans quel cas ne doit on pas l'utiliser ?

2024-02-14 11:03 UTC, skelz0r commented on app/controllers/authorization_request_forms_controller.rb
> +      render 'pages/custom'
Je parle du render, sinon j'aurais commenté sur la ligne du dessus

2024-02-14 11:06 UTC, skelz0r commented on app/views/pages/custom.html.erb
> +          <%= t('pages.home.title').html_safe %>
> Dans quel cas, peut on utiliser html_safe et dans quel cas ne doit on pas l'utiliser ?

Si t'as besoin d'interprété du html. Là y'a pas besoin flip it imo.

2024-02-14 11:15 UTC, skelz0r commented on app/views/pages/custom.html.erb
> +          <%= t('pages.home.title').html_safe %>
(et en effet y'en a partout 🙄)

2024-02-19 12:00 UTC, Samuelfaure requested changes

2024-02-19 12:00 UTC, Samuelfaure commented on features/step_definitions/login_steps.rb
> +    Et que je clique sur "S’identifier avec MonComptePro"
vaut mieux garder le `'` que le `’` dans notre code imo (revert ici)

2024-02-27 16:35 UTC, skelz0r requested changes
Pour les test, j'en ferai 3:

1. Je consulte en tant qu'internaute une page de démarrage de formulaire simple
2. Je consulte en tant qu'internaute une page de démarrage de formulaire à plusieurs étapes
3. Je démarre en tant qu'internaute qui se connecte un formulaire d'habilitation

Je pense que dans un premier temps tu pourrais simplifier et fusionner 1. et 2. (et retirer cette notion de N étapes).

Globalement y'a plus grand chose à changer.

2024-02-27 16:35 UTC, skelz0r commented on features/redirections.feature
> +    Sachant que je suis un demandeur
Ce test est faux: un demandeur est un utilisateur connecté. 
Il faut retirer cette ligne.

Ce qui m'a mis la puce à l'oreille c'est le fait que `authorize @authorization_request_form, :new?` a peu de chance de passer en l'état (tout du moins c'est sûr que ça va fail sur le cas `unique?` à `false`.

2024-02-27 16:35 UTC, skelz0r commented on features/redirections.feature
> +    Quand je veux remplir une demande pour "API Entreprise"
C'est ~ish faux dans le vocabulaire et les notions. Ici on veut remplir un formulaire X pour une habilitation Y.

Du genre:

```
Quand je veux remplir une demande pour "API Entreprise" via le formulaire "Demande libre"
```

Et d'ailleurs dans ton code cela se voit:

```
form_uid: find_authorization_definition_from_name(authorization_request_name
```

Tu affectes à un id de form l'id d'une définition. Ici c'est tombé en marche car les 2 sont identiques.

2024-02-27 16:35 UTC, skelz0r commented on features/redirections.feature
> +    Et la page contient "Votre demande d’habilitation va se dérouler en 4 étapes"
C'est vrai ici pour le formulaire à étape, il faut faire aussi le test pour un formulaire sur une page donc.

2024-02-27 16:35 UTC, skelz0r commented on app/views/authorization_requests/unauthenticated_authorization_request_form_start.html.erb
> +<div class="fr-container">
Ce fichier devrait être dans `app/views/authorization_request_forms` (et je le nommerai `unauthenticated_form_start`

2024-02-27 16:35 UTC, skelz0r commented on config/locales/fr.yml
> +      sub_title: "Vous souhaitez accédez à l’<strong>%{api_name}</strong> \n Votre demande d’habilitation va se dérouler en 4 étapes"
Le "4 étapes" est variable: cela dépend des formulaires.

2024-02-27 16:35 UTC, skelz0r commented on features/redirections.feature
> +    Et la page contient "demandeur@gouv.fr"
Je déporterai ça dans un 2e test.

2024-02-27 16:35 UTC, skelz0r commented on app/controllers/authorization_request_forms_controller.rb
> +    end
Je descendrait le `authorize` dans le `else` ici

2024-02-27 16:35 UTC, skelz0r commented on app/assets/stylesheets/components/timeline_steps.css
> +.steps-timeline {
L'ensemble de tes classes sont trop génériques. Si tu veux garder ça dans un composant fait des namespacing pour éviter les conflits (tu peux t'inspirer de tous les autres composants).

2024-02-27 16:36 UTC, skelz0r commented on features/redirections.feature
> +    Et la page contient "Votre demande d’habilitation va se dérouler en 4 étapes"
( ou alors tu fais un wording générique pour simplifier )

2024-02-27 16:37 UTC, skelz0r commented on app/views/authorization_requests/unauthenticated_authorization_request_form_start.html.erb
> +<div class="fr-container">
Vu comment c'est rangé ça peut potentiellement rester dans ce dossier. Par contre le nom est redondant faut dans tous les cas renommer en `unauthenticated_form_start`

2024-02-27 16:38 UTC, skelz0r commented on features/redirections.feature
> +    Et la page contient "demandeur@gouv.fr"
En fait ce sont 2 scénarios en 1 (d'ailleurs je ne comprends pas comment ça peut marcher de faire du `Sachant` après un `Alors`, ça ne suit pas le gherkin).

2024-02-27 16:45 UTC, skelz0r commented on features/redirections.feature
> +    Sachant que je suis un demandeur
Je retire ce que j'ai dit 😅

2024-02-27 16:57 UTC, skelz0r commented on .rubocop.yml
> +  Max: 155
Je mettrais cette restriction directement sur le controller btw:

```ruby
# rubocop:disable Metrics/ClassLength
class Controller
end
# rubocop:enable Metrics/ClassLength
```

2024-02-28 15:01 UTC, mehdi-farsi approved these changes
LGTM

2024-02-28 15:11 UTC, skelz0r commented
Feel free de merger du coup @Isalafont ;)

2024-02-28 15:13 UTC, merged